### ISSUE TITLE
[Bug] versions with dots dont resolve

### ISSUE THREAD

**Issue by bepvte** [yarnpkg/berry#836] opened 2020-01-29 22:51 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

```json
{
  "dependencies": {
    "discord.js": "github:discordjs/discord.js"
  }
}
```
yarn install fails here with "isn't supported by any available resolver", while it works with packages that dont have dots in the url.

P.S.: Is the "username/reponame" alias to https://github.com/username/reponame.git going to be added to `yarn add` like in npm?

**Comment by arcanis** [comment] 2020-01-29 23:07
hey @bepvte! I'll close this issue as a duplicate of #832. Good news is, the fix is in master and you can try it out with `yarn set version from sources` 🙂

> P.S.: Is the "username/reponame" alias to https://github.com/username/reponame.git going to be added to yarn add like in npm?

For now you'll need to name it, so `yarn add package@username/reponame` will work. We might relax this requirement in a future release.

**Closed by arcanis** 2020-01-29 23:07 UTC
Labels: bug
