### ISSUE TITLE
[Bug?]: `yarn dlx @yarnpkg/sdks base` ignores SDKs needed by workspaces

### ISSUE THREAD

**Issue by roddypratt** [yarnpkg/berry#5129] opened 2022-12-09 11:23 UTC
### Describe the bug

I have package containing  yarn workspace folders. The workspace folders have Typescript as a `devDependency` in their respective `package.json` files, but Typescript is not in the root `package.json`.

Running `yarn dlx @yarnpkg/sdks base` from the root (or even a workspace folder) doesn't install the Typescript SDK.

```
PS C:\test> cat package.json    
{
  "name": "test",
  "packageManager": "yarn@3.3.0",
  "workspaces": [
    "foo"
  ]
}

PS C:\test> cat foo/package.json       
{
  "name": "foo",
  "packageManager": "yarn@3.3.0",
  "dependencies": {
    "typescript": "^4.9.4"
  }
}

PS C:\test> yarn dlx @yarnpkg/sdks base
...
➤ YN0000: ┌ Generating SDKs inside .yarn/sdks
➤ YN0000: │ • 6 SDKs were skipped based on your root dependencies


PS C:\test> yarn add typescript
...

PS C:\test> yarn dlx @yarnpkg/sdks base
...
➤ YN0000: ┌ Generating SDKs inside .yarn/sdks
➤ YN0000: │ ✓ Typescript
➤ YN0000: │ • 5 SDKs were skipped based on your root dependencies

``` 

I'd expect the Typescript SDK to be installed if it's required by any workspace. 
  

### To reproduce

```
mkdir test
cd test
yarn init

mkdir foo
cd foo
yarn init
yarn add typescript --dev
cd ..
```
Manually add `"workspaces":["foo"]` to package.json
```
yarn dlx @yarnpkg/sdks base
```
**Expected:** 
```
➤ YN0000: ┌ Generating SDKs inside .yarn/sdks
➤ YN0000: │ ✓ Typescript
➤ YN0000: │ • 5 SDKs were skipped based on your root dependencies
```
**Actual:**
```
➤ YN0000: ┌ Generating SDKs inside .yarn/sdks
➤ YN0000: │ • 6 SDKs were skipped based on your root dependencies
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Temp\xfs-1e160e7e\node.CMD
    Yarn: 3.3.0 - ~\AppData\Local\Temp\xfs-1e160e7e\yarn.CMD
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

Obviously the simple workaround is to add a dependency in the top-level package.json. But this issue caused a lot of head-scratching because I'd removed what I thought was a spurious dependency on Typescript from the root package several days ago. Things only fell apart when I needed to updated the SDKs...
_No response_

**Comment by merceyz** [comment] 2022-12-09 11:39
Note that this is documented behaviour and therefore not a bug https://yarnpkg.com/getting-started/editor-sdks/#tools-currently-supported.

**Comment by merceyz** [comment] 2022-12-09 11:42
Duplicate of https://github.com/yarnpkg/berry/issues/3113

**Closed by merceyz** 2022-12-09 11:42 UTC
Labels: bug
