### ISSUE TITLE
[Bug?]: fs.rmSync error with yarn PnP: The "path" argument must be of type string. Received an instance of Buffer

### ISSUE THREAD

**Issue by gutenye** [yarnpkg/berry#3903] opened 2021-12-23 12:41 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

[fs.rmSync](https://nodejs.org/api/fs.html#fsrmsyncpath-options) does not work with yarn PnP

### To reproduce

```
mkdir hello && cd hello
yarn init -2
yarn
mkdir -p a/b/c/d/e/f/g
vi a.js
  const fs = require('fs')
  fs.rmSync('./a', { recursive: true })
yarn node a.js
```

Got 

```
node:internal/fs/rimraf:202
      throw err;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.isAbsolute (node:path:1157:5)
    at VirtualFS.mapToBase (/private/tmp/a/.pnp.cjs:6104:24)
    at VirtualFS.rmdirSync (/private/tmp/a/.pnp.cjs:5936:39)
    at PosixFS.rmdirSync (/private/tmp/a/.pnp.cjs:5936:24)
    at URLFS.rmdirSync (/private/tmp/a/.pnp.cjs:5936:24)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 17.3.0 - /private/var/folders/lv/6_bkp55j2sg6m4j20nz53v1c0000gn/T/xfs-d93da319/node
    Yarn: 3.1.1 - /private/var/folders/lv/6_bkp55j2sg6m4j20nz53v1c0000gn/T/xfs-d93da319/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
```

### Additional context

rmSync is not in https://github.com/yarnpkg/berry/blob/8afcaa2a954e196d6cd997f8ba506f776df83b1f/packages/yarnpkg-fslib/sources/patchFs.ts#L8

**Comment by merceyz** [comment] 2022-01-20 18:30
Duplicate of https://github.com/yarnpkg/berry/issues/1818

**Closed by merceyz** 2022-01-20 18:30 UTC
Labels: bug
