### ISSUE TITLE
[Bug?]: if I use typescript, I can't import a module.

### ISSUE THREAD

**Issue by eungyeole** [yarnpkg/berry#3373] opened 2021-09-02 04:03 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

![image](https://user-images.githubusercontent.com/66717787/131779161-4d5cb6bd-fb88-4589-8f3a-8b45d5126a51.png)

As shown in the picture above, using TypeScript, I can't import a module.
Therefore, I added the node linker: node-modules to the .yarnc.yml file and it was imported normally. 

But this wasn't the way I wanted it to be.
So I downgrade the TypeScript version to 4.3.5, and this also solved the problem.

But this wasn't the way I wanted it either.
Is there any way to solve this?

### package.json
```json
{
  "name": "test",
  "packageManager": "yarn@3.0.1",
  "dependencies": {
    "immer": "^9.0.6",
    "typescript": "^4.4.2"
  }
}
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es2018",
    "lib": [
      "esnext"
    ],
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

### .yarnrc.yml
```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

```

### Environment

 System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.2.0 - /private/var/folders/0l/txz4jsg559s1681bszrjjxkr0000gn/T/xfs-4975a7ce/node
    Yarn: 3.0.1 - /private/var/folders/0l/txz4jsg559s1681bszrjjxkr0000gn/T/xfs-4975a7ce/yarn
    npm: 7.20.3 - /usr/local/bin/npm

**Comment by merceyz** [comment] 2021-09-02 06:49
Duplicate of https://github.com/yarnpkg/berry/issues/3350

**Comment by merceyz** [comment] 2021-09-02 06:50
The fix is to run the following command
```sh
yarn set version canary && yarn
```

**Closed by merceyz** 2021-09-02 06:49 UTC
Labels: bug
