### ISSUE TITLE
[Bug?]: Cannot find module ... when using tsc

### ISSUE THREAD

**Issue by andersonkyle** [yarnpkg/berry#3377] opened 2021-09-02 18:23 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

An extremely minimal project that uses Yarn w/ PnP and TypeScript fails to compile due to:
```
src/index.tsx:1:19 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

1 import React from "react"
                    ~~~~~~~


Found 1 error.
```

### Configuration

`.yarnrc.yml`
```
yarnPath: ".yarn/releases/yarn-berry.cjs"
```
`tsconfig.json`
```
{
    "compilerOptions": {
        "jsx": "react"
    }
}
```

`package.json`
```
{
  "name": "typescript-project",
  "packageManager": "yarn@3.0.1",
  "scripts": {
    "build": "tsc"
  },
  "devDependencies": {
    "typescript": "^4.4.2"
  },
  "dependencies": {
    "react": "^17.0.2"
  }
}
```

### Code

`index.tsx`
```
import React from "react"

const Greeting = () => (<div>Hello, World!</div>)
```

### Command
```
yarn build
```

### Environment

System:
  OS: Ubuntu 20.04 LTS (via WSL on Windows 10 Pro 19042.1202)
  CPU: Intel(R) Core(TM) i7-8550U
Binaries:
Node: 14.17.6 - /usr/bin/node
Yarn (global): 1.22.11 - /home/me/.npm-global/bin/yarn
npm: 6.14.15 - /usr/bin/npm

### Additional context

Per the [documentation](https://yarnpkg.com/features/pnp#native-support) TypeScript "natively" supports PnP (by way of a patch) so I'm unsure why this simple application isn't working.

If I enable `node_modules` by adding this to `.yarnrc.yml` it all works as expected:
```
yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
```

**Comment by merceyz** [comment] 2021-09-02 18:49
Duplicate of https://github.com/yarnpkg/berry/issues/3350

**Comment by merceyz** [comment] 2021-09-02 18:50
The fix is to run the following command
```sh
yarn set version canary && yarn
```

**Closed by merceyz** 2021-09-02 18:49 UTC
Labels: bug
