### ISSUE TITLE
Cannot add typescript with berry

### ISSUE THREAD

**Issue by ForgeModDev** [yarnpkg/berry#2546] opened 2021-03-01 23:16 UTC
When I try to add typescript package with yarn berry,it will produce an error said:
cannot apply hunk # 6 (set enableInlineHunks for details)
but when I use yarn classic,I can add it with no error.
How can I solve it??

**Comment by merceyz** [comment] 2021-03-01 23:17
Duplicate of https://github.com/yarnpkg/berry/issues/2514

**Closed by merceyz** 2021-03-01 23:17 UTC
