### ISSUE TITLE
[Bug?]: The `--topological-dev` parameter of yarn workspaces does not take effect

### ISSUE THREAD

**Issue by rxliuli** [yarnpkg/berry#3475] opened 2021-09-23 03:03 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I use the `--topological-dev` parameter, it will not run normally in the order of dependencies

```sh
$ yarn workspaces foreach -v -p --topological-dev run setup
➤ YN0000: [a]: Process started
➤ YN0000: [b]: Process started
➤ YN0000: [a]: a
➤ YN0000: [a]: Process exited (exit code 0), completed in 0s 88ms
➤ YN0000: [b]: b
➤ YN0000: [b]: Process exited (exit code 0), completed in 0s 82ms
➤ YN0000: Done in 0s 101ms
```

### To reproduce

> [Example github repository](https://github.com/rxliuli/yarn2-workspaces-error)

Steps to reproduce

1. `git clone https://github.com/rxliuli/yarn2-workspaces-error.git`
2. `cd yarn2-workspaces-error`
3. `yarn`
4. `yarn workspaces foreach -v -p --topological-dev run setup`

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 16.9.1 - ~\AppData\Local\Temp\xfs-d441c8c7\node.CMD
    Yarn: 3.0.2 - ~\AppData\Local\Temp\xfs-d441c8c7\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

This seems to be a regression error, only yarn3 will appear. Currently, yarn2 cannot be used to install the workspaces plugin. This is another error.

**Comment by seansfkelley** [comment] 2021-09-29 17:44
I was curious about this so I tried it as well. It does repro, but what you've pasted in the code same shows it working as intended. The output I get is

```
➤ YN0000: [a]: Process started
➤ YN0000: [b]: Process started
➤ YN0000: [b]: b
➤ YN0000: [b]: Process exited (exit code 0), completed in 0s 65ms
➤ YN0000: [a]: a
➤ YN0000: [a]: Process exited (exit code 0), completed in 1s 195ms
➤ YN0000: Done in 1s 199ms
```

which is wrong, since `b` depends on `a`. You can see that `a` starts first, however: and indeed, if you remove `-p`, it goes in the right order.

**Comment by seansfkelley** [comment] 2021-09-29 17:56
Oh wait, I figured it out. This isn't a bug so I think you can close this issue, @rxliuli.

`a` is a public package on npmjs.com. When you depend on `a@*` from `b`, Yarn is pulling the public package, not making a link between the local `a` and `b`. As such, they are not in a dependency relationship with one another, and can be run in whatever order they like.

If you change the dependency to be `workspace:*` and `yarn install`, it behaves as expected.

**Closed** 2021-09-30 01:50 UTC
Labels: bug
