### ISSUE TITLE
[Bug?]: Empty package pushed to NPM

### ISSUE THREAD

**Issue by kbobrowski** [yarnpkg/berry#4452] opened 2022-05-13 12:41 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Packages for version 3.2.1 were pushed with just package.json inside, e.g. https://github.com/yarnpkg/berry/packages/19319

This results in commands like `yarn dlx @yarnpkg/sdks vscode` failing with:

```
/tmp/xfs-a0d57e4a/dlx-64061/.pnp.cjs:9891
    throw firstError;
    ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
```

### To reproduce

`yarn dlx @yarnpkg/sdks vscode` in any yarn project

### Environment

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 16.15.0 - /tmp/xfs-6eb8a788/node
    Yarn: 3.2.0 - /tmp/xfs-6eb8a788/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

**Comment by merceyz** [comment] 2022-05-13 12:44
Duplicate of https://github.com/yarnpkg/berry/issues/4451

**Closed by merceyz** 2022-05-13 12:44 UTC
Labels: bug
