### ISSUE TITLE
[Bug] performance issue with yarn node

### ISSUE THREAD

**Issue by Ayc0** [yarnpkg/berry#2719] opened 2021-04-09 08:28 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

Since I switched to yarn berry, I noticed that we had a noticeable slowdown when running `yarn exec` commands:

For instance here is a comparison between `yarn node` and `node -r` for logging "red" in red with chalk:

(I have a lot of modules in my package but even with an empty package.json, we have the same issue, see reproduction section)

`Yarn node` | `node -r`
-|-
<img width="550" alt="Screen Shot 2021-04-09 at 9 52 49 AM" src="https://user-images.githubusercontent.com/22725671/114148774-6d7c6380-991a-11eb-8a78-a02a99ac4e86.png"> | <img width="549" alt="Screen Shot 2021-04-09 at 9 52 45 AM" src="https://user-images.githubusercontent.com/22725671/114148766-6c4b3680-991a-11eb-844b-bff499e483e9.png">

We can notice that there is a huge slowdown when running through `yarn`

**To Reproduce**

<details>
  <summary>Reproduction</summary>

  ```bash repro
  mkdir test
  cd test
  yarn init -y
  yarn set version berry
  time yarn node -e "console.log('red')"
  time node -r ./.pnp.js -e "console.log('red')"
  ```

**Screenshots**

Node -r | Yarn node
-|-
![image](https://user-images.githubusercontent.com/22725671/114152112-2b552100-991e-11eb-97c4-51256624e505.png) | ![image](https://user-images.githubusercontent.com/22725671/114152128-31e39880-991e-11eb-9408-b3e2b4290231.png)

</details>

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.15.7
 - Node version: Both `v15.14.0` and `v12.16.1`
 - Yarn version: both `2.4.0-git.20210210.hash-cb8c8d68` and `2.4.1`

**Additional context**

**Comment by arcanis** [comment] 2021-04-09 08:44
Master already contains various improvements. Likely duplicate of https://github.com/yarnpkg/berry/issues/2560#issuecomment-791353543

**Comment by Ayc0** [comment] 2021-04-11 22:04
Thanks, I'll try the new master!

**Comment by Ayc0** [comment] 2021-05-04 15:05
I don't think master improved the situation that much:

`yarn node -e "console.log('a')"` still takes more than 1s: 

![image](https://user-images.githubusercontent.com/22725671/117024964-c57c6f00-acfa-11eb-9dae-fef636d3e52d.png)

and I'm running yarn 3-rc2

![image](https://user-images.githubusercontent.com/22725671/117025096-e3e26a80-acfa-11eb-8889-61a01e4bf50c.png)

**Comment by merceyz** [comment] 2021-06-07 10:45
I'll close this as a duplicate of https://github.com/yarnpkg/berry/issues/2575 since `yarn node` goes through the same process as `yarn run`

**Closed by merceyz** 2021-06-07 10:45 UTC
Labels: bug, upholded
