### ISSUE TITLE
[Bug] postinstall fails leads to install fails

### ISSUE THREAD

**Issue by chengcyber** [yarnpkg/berry#2327] opened 2021-01-04 06:57 UTC
- [x] I'd be willing to implement a fix

**Describe the bug**

install with `swiper`. postinstall script fails

```
# This file contains the result of Yarn building a package (swiper@npm:4.4.2)
# Script name: postinstall

[eval]:1
console.log('u001b[35mu001b[1mLove Swiper? Support Vladimir's work by donating or pledging on patreon:u001b[22mu001b[39mn > u001b[32mhttps://patreon.com/vladimirkharlampidiu001b[0mn')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
```

it seems accident `'` early terminate the post install string...

swiper@4.4.2 package.json

```
  "postinstall": "node -e \"console.log('\\u001b[35m\\u001b[1mLove Swiper? Support Vladimir\\'s work by donating or pledging on patreon:\\u001b[22m\\u001b[39m\\n > \\u001b[32mhttps://patreon.com/vladimirkharlampidi\\u001b[0m\\n')\""
```

**To Reproduce**

[Playground](https://yarnpkg.com/playground?code=CmNvbnN0IHJlcyA9IGF3YWl0IHBhY2thZ2VKc29uQW5kSW5zdGFsbCh7CiAgZGV2RGVwZW5kZW5jaWVzOiB7CiAgICBbYHN3aXBlcmBdOiBgNC40LjJgCiAgfQp9KQoKYXdhaXQgZXhwZWN0KHJlcykucmVqZWN0cy50b1Rocm93KCk7)

**Screenshots**

![image](https://user-images.githubusercontent.com/16147702/103508972-096e7d00-4e9d-11eb-8502-3c5cb7642fed.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.14.6
 - Node version 12.19.1
 - Yarn version 2.4.0

**Additional context**

1. Why not upgrade

swiper depends by another modules, which fixed to version `4.4.2` https://github.com/NervJS/taro/blob/next/packages/taro-components/package.json#L47

2. is there a way to ignore some packages postinstall

Since the postinstall of `swiper` is advertisement, nothing else to modify original module. Could i setup in yarnrc.yml to ignore the specified lifecycle of a certain package?

such as 

```
# .yarnrc.yml
packageExtensions:
  swiper@*:
    scripts:
      postinstall: ""
```

**Comment by merceyz** [comment] 2021-01-04 07:59
Duplicate of https://github.com/yarnpkg/berry/issues/1356

> is there a way to ignore some packages postinstall
> Since the postinstall of swiper is advertisement, nothing else to modify original module. Could i setup in yarnrc.yml to ignore the specified lifecycle of a certain package?

> such as

Yes, use [dependenciesMeta.built](https://yarnpkg.com/configuration/manifest#dependenciesMeta.built)

**Closed by merceyz** 2021-01-04 07:59 UTC
Labels: bug
