### ISSUE TITLE
[Bug]: VSCode can't find base `tsconfig` when extending from a shared one

### ISSUE THREAD

**Issue by AlCalzone** [yarnpkg/berry#3115] opened 2021-07-12 19:47 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm not sure if this is actually a bug in yarn or the VSCode PnP SDK or because the paths are hardcoded in TypeScript, but I figured I'd start here. With Yarn PnP, go to source on a shared tsconfig (in my case @tsconfig/node12 from the https://github.com/tsconfig/bases/ repo), fails with this error
```
[Window Title]
Visual Studio Code

[Main Instruction]
"tsconfig.json" kann nicht geöffnet werden.

[Content]
Die Datei "c:\Repositories\node-zwave-js\node_modules\@tsconfig\node12\tsconfig.json" kann nicht gelesen werden (Error: Die nicht vorhandene Datei "c:\Repositories\node-zwave-js\node_modules\@tsconfig\node12\tsconfig.json" kann nicht aufgelöst werden.).

[Datei erstellen] [Abbrechen]
```
(sorry for the german, but you should get the gist of it)

The same happens after I unplugged the package with `yarn unplug @tsconfig/node12`.

### To reproduce

1. Use Yarn PnP
1. Install devDependency `@tsconfig/node12`
1. Have a tsconfig.json with the following content:
    ```json
    {
    	"extends": "@tsconfig/node12/tsconfig.json",
    	"compilerOptions": {}
    }
    ```
1. (optional) `yarn unplug @tsconfig/node12`
1. CTRL+Click on `@tsconfig/node12/tsconfig.json` to go to the source

### Environment

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 16.2.0 - ~\AppData\Local\Temp\xfs-0fa3a71e\node.CMD
    Yarn: 3.0.0-rc.6 - ~\AppData\Local\Temp\xfs-0fa3a71e\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by merceyz** [comment] 2021-07-14 20:18
Duplicate of https://github.com/yarnpkg/berry/issues/3115

**Closed by merceyz** 2021-07-14 20:18 UTC
Labels: bug
