### ISSUE TITLE
[Bug] PnP cannot find ava

### ISSUE THREAD

**Issue by FallingSnow** [yarnpkg/berry#1760] opened 2020-08-24 20:29 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

Using yarn's PnP feature with [AVA](https://github.com/avajs/ava) test tool results in strange `ava` not found when I try to import it. But it does say did you mean `ava-npm-3.11.1...`. I've also tried using `yarn pnpify ava` but it's the same issue.

```js
$ yarn run test      // "test": "ava"
Uncaught exception in test/database.spec.mjs

  Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ava' imported from /project/test/database.spec.mjs
  Did you mean to import ava-npm-3.11.1-eda34ac446-282cb94428.zip/node_modules/ava/index.js?

  › Did you mean to import ava-npm-3.11.1-eda34ac446-282cb94428.zip/node_modules/ava/index.js?
  › packageResolve (internal/modules/esm/resolve.js:620:9)
  › moduleResolve (internal/modules/esm/resolve.js:659:14)
  › Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:752:11)
  › Loader.resolve (internal/modules/esm/loader.js:97:40)
  › Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
  › ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:50:40)
  › link (internal/modules/esm/module_job.js:49:36)
```

**To Reproduce**

<details>
  <summary>database.spec.mjs</summary>

  ```js
import test from "ava";
import {resolve, basename} from "path";

import {Database} from "../lib/database.ts";

const db = new Database();

test("create user", async (t) => {
  const info = {
    firstName: "foo",
    lastName: "bar"
  }
  db.newUser(info);
});
  ```
</details>

<details>
  <summary>Package.json AVA settings</summary>

  ```js
"ava": {
    "require": [
      "ts-node/register"
    ],
    "babel": true,
    "files": [
      "test/**.spec.js",
      "test/**.spec.mjs"
    ]
}
  ```
</details>

**Environment if relevant (please complete the following information):**

 - OS: Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64 GNU/Linu
 - Node version: v14.4.0
 - Yarn version: 2.1.1
 - Typescript version: 4.0.2

**Comment by arcanis** [comment] 2020-08-24 20:36
Probably a duplicate of #638

**Closed by arcanis** 2020-08-24 20:36 UTC
Labels: bug
