### ISSUE TITLE
[Bug?]: Jest not starting with yarn 3.2.1 and pnp (works with 3.1.0 or node-modules linker)

### ISSUE THREAD

**Issue by elado** [yarnpkg/berry#4457] opened 2022-05-15 17:01 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

A very simple project with just `jest` as a dep, `nodeLinker: pnp` and yarn 3.2.1-
`yarn jest` halts and never exits. Possibly related to recent pnp changes?

### To reproduce

Repro:
https://github.com/elado/yarn-3.2.1-jest-bug

```
git clone https://github.com/elado/yarn-3.2.1-jest-bug.git
cd yarn-3.2.1-jest-bug
yarn
yarn jest
<endless wait>
```

Downgrade to 3.1.0 works
https://github.com/elado/yarn-3.2.1-jest-bug/tree/3.1.0

```
git switch 3.1.0
yarn
yarn jest
<works>
```

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.1 - /private/var/folders/8r/75v81kkd78x69n_wmwh_1c2h0000gp/T/xfs-710445b5/node
    Yarn: 3.1.0 - /private/var/folders/8r/75v81kkd78x69n_wmwh_1c2h0000gp/T/xfs-710445b5/yarn
    npm: 8.1.2 - ~/.nvm/version/npm
```

**Comment by merceyz** [comment] 2022-05-15 19:04
Duplicate of https://github.com/yarnpkg/berry/issues/4157

**Closed by merceyz** 2022-05-15 19:04 UTC
Labels: bug
