### ISSUE TITLE
[Bug] yarn 3.2.0 - jest suite hangs

### ISSUE THREAD

**Issue by vire** [yarnpkg/berry#4203] opened 2022-03-09 16:29 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After upgrading `3.1.1` to `3.2.2` jest tests started to hang without any output, when tests are run individually they all pass, when I run `yarn jest -c ./path/to/my/jest.config.js` it hangs.

### To reproduce

It's a private repo hard to reproduce, so I'm not able to reproduce easily

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1 Pro
  Binaries:
    Node: 14.15.5 
    Yarn: 3.2.0
    npm: 8.3.2
```

### Additional context

It's a yarn workspaces monorepo

**Comment by merceyz** [comment] 2022-03-09 16:36
Duplicate of https://github.com/yarnpkg/berry/issues/4157

**Closed by merceyz** 2022-03-09 16:36 UTC
Labels: bug
