### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by jim55167** [yarnpkg/berry#4727] opened 2022-08-10 07:05 UTC
Yarn version = 3.2.2
For Nuxt.js In Windows  IIS Server  Error： Cannot find module 'express'
![螢幕擷取畫面 2022-08-10 145926](https://user-images.githubusercontent.com/67188543/183836633-de2236a4-6df9-4e24-ab30-f2a3a431b166.png)

**Comment by RDIL** [comment] 2022-08-25 11:05
Whatever system you are using probably isn’t properly loading the PnP runtime patch.  Try doing `require("pnpapi")` before the express import to see if it’s being loaded or not.

**Comment by merceyz** [comment] 2022-08-25 13:06
Closing as unactionable since there is no reproduction steps.

**Closed by merceyz** 2022-08-25 13:06 UTC
