### ISSUE TITLE
[Bug?]: `workspaces foreach run` appearch not to skip workspaces/packages where a script does not exist 

### ISSUE THREAD

**Issue by mxro** [yarnpkg/berry#3494] opened 2021-09-24 23:23 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

After upgrading to the latest yarn version, a number of scripts that rely on `workspaces foreach` seem to have stopped working.

Specifically, `workspaces foreach run` would previously skip those workspaces/packages for which a specific script does not exist. 

```
    "generate:schema": "yarn workspaces foreach --topological-dev run generate:schema",
```

[package.json](https://github.com/goldstack/goldstack/blob/f93fa9606f06fffe6d223da0ddf08137bd4fb005/workspaces/templates-lib/package.json#L18)

So in the above, all packages that do not have the `generate:schema` script would be skipped.

Now I am receiving the following error:

```
➤ YN0000: Usage Error: Couldn't find a script named "generate:schema".
➤ YN0000: 
➤ YN0000: $ yarn run [--inspect] [--inspect-brk] <scriptName> ...
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 0s 383ms
```

This issue seems to indicate that skipping non-existing scripts should be the expected behaviour:

https://github.com/yarnpkg/yarn/issues/6894#issuecomment-646579736

### To reproduce

Run `foreach workspaces run --topological-dev [script]` across workspaces for which some of them do not have [script] defined (and a package that other packages depend upon is missing the [script]). 

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  Binaries:
    Node: 14.17.6 - ~\AppData\Local\Temp\xfs-b8a4675e\node.CMD
    Yarn: 3.0.2 - ~\AppData\Local\Temp\xfs-b8a4675e\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

~~Note this behaviour only seems to be the case when using the `--topological-dev` option.~~ No, found it also occurs when this option is not set.

**Comment by merceyz** [comment] 2021-09-25 08:44
Duplicate of https://github.com/yarnpkg/berry/issues/3048

**Closed by merceyz** 2021-09-25 08:44 UTC
Labels: bug
