### ISSUE TITLE
[Bug]: Typescript-patch cannot resolve type declarations inside workspaces

### ISSUE THREAD

**Issue by sushruth** [yarnpkg/berry#3780] opened 2021-11-22 08:24 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Type declarations do not work in yarn workspaces, even when types are installed both in workspace's `package.json` and root's `package.json`. This is true for both tsc and tsserver. See example repo here - https://github.com/sushruth/yarn-workspaces-ts-bug

This is how the error looks - 

![image](https://user-images.githubusercontent.com/2114206/142827257-12554c6e-fc22-4148-b339-d3f8489eccb8.png)

Somehow compile and declaration emit succeeds but the above error is shown.

### To reproduce

NA

### Environment

```shell
`envinfo` breaks on windows 11 (since `wmic` cli is no longer present). Could not collect this information.
```

**Comment by dobernike** [comment] 2021-11-22 08:39
reproduced with typescript 4.5

**Comment by merceyz** [comment] 2021-11-22 08:43
Duplicate of https://github.com/yarnpkg/berry/issues/3722

**Closed by merceyz** 2021-11-22 08:43 UTC
Labels: bug
