### ISSUE TITLE
[Bug]: Yarn workspace-tools foreach doesn't work with nodejs 16

### ISSUE THREAD

**Issue by tsapko3628** [yarnpkg/berry#3065] opened 2021-06-30 09:19 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn workspaces foreach run` doesn't work correctly with nodejs 16 (16.3, 16.4).
No output even with verbose mode.
Script running only in one package.

### To reproduce

[Repository](https://gitlab.com/hyper-graph/packages) to reproduce. Change nodejs version to 16.4 and run `build` script. Only one dist folder will be generated.

### Environment

```

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.4.0 - /private/var/folders/xb/yzs09_8s3szd9_q5789zd6kw0000gn/T/xfs-a4bfe42c/node
    Yarn: 2.4.2 - /private/var/folders/xb/yzs09_8s3szd9_q5789zd6kw0000gn/T/xfs-a4bfe42c/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
```

**Comment by merceyz** [comment] 2021-06-30 09:21
Duplicate of https://github.com/yarnpkg/berry/issues/2074

**Closed by merceyz** 2021-06-30 09:21 UTC
Labels: bug

**Comment by tsapko3628** [comment] 2021-06-30 09:22
```
$ yarn node -v
v16.4.0
```
I suppose it is another issue

**Comment by tsapko3628** [comment] 2021-06-30 09:25
And #2074 is closed, but bug is still available. Might be it reproduces only in nodejs v16, not in v15. It also means that it's another issue without resolution

**Comment by merceyz** [comment] 2021-06-30 09:26
No, it's the same issue, update to the latest RC to get the fix

```
yarn set version 3.0.0-rc.6 && yarn plugin import workspace-tools
```

**Comment by tsapko3628** [comment] 2021-06-30 09:30
Thanks! It solved my problem
