### ISSUE TITLE
[Bug] Cannot install package from github branch

### ISSUE THREAD

**Issue by raspy8766** [yarnpkg/berry#835] opened 2020-01-29 22:09 UTC
**Describe the bug**

Cannot install package from [github branch](github.com/alansouzati/vorpal/tarball/EXIT_ON_PARSE)
```
$ yarn add grommet-cli
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: vorpal@https://github.com/alansouzati/vorpal/tarball/EXIT_ON_PARSE isn't supported by any available resolver
at t.MultiResolver.getResolverByDescriptor (C:\Users\rasmussr\Downloads\temp\.yarn\releases\yarn-sources.js:24:41628)
at t.MultiResolver.bindDescriptor (C:\Users\rasmussr\Downloads\temp\.yarn\releases\yarn-sources.js:24:41082)
at Promise.all.u.map (C:\Users\rasmussr\Downloads\temp\.yarn\releases\yarn-sources.js:36:584334)
at process.internalTickCallback (internal/process/next_tick.js:77:7)
➤ YN0000: └ Completed in 0.02s
➤ YN0000: Failed with errors in 0.02s
```

**To Reproduce**
run `yarn add grommet-cli`

**Environment if relevant (please complete the following information):**

 - OS: Windows (using git bash)
 - Node version: 11.6.0
 - Yarn version: 2.0.0-rc.28

**Comment by paul-soporan** [comment] 2020-05-08 11:40
I'm going to close this as a duplicate of #885. (Even though this issue was opened first, the other one contains more information and has more participants.)

**Closed by paul-soporan** 2020-05-08 11:40 UTC
Labels: bug
