### ISSUE TITLE
[Bug] Slower link w/ the nm linker

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#1311] opened 2020-05-07 11:13 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

A simple require does not work because of hoisting.

**To Reproduce**

```
git clone git@github.com:bertho-zero/yarn-bug-repro.git
cd yarn-bug-repro/packages/package-1
yarn start
```

**Screenshots**

![image](https://user-images.githubusercontent.com/8525267/81288048-2596f180-9064-11ea-9014-6b2ff166a74d.png)

**Environment**

 - OS: Linux
 - Node version v12.16.1
 - Yarn version 2.0.0-rc.33

**Comment by larixer** [comment] 2020-05-07 15:01
@bertho-zero Should be fixed via #1313 To try it out you can use
`yarn set version from sources --branch 1313`

**Comment by bertho-zero** [comment] 2020-05-07 17:26
Looks good ! :+1:

**Comment by bertho-zero** [comment] 2020-05-11 07:50
It works correctly in the reproduction project but I have an out of memory error in the initial project.
The link step never ends even when going back to the version I previously pushed on git.

**Comment by larixer** [comment] 2020-05-11 08:15
@bertho-zero I see. I have noticed that even on your reproduction project the link step takes way too long (23 seconds), for your project size it should takes less than a second. So definitely this is not normal. I will be able to look into this problem later, hopefully next week, and will keep you informed. You can try to workaround this issue in the meantime via deduplicate plugin or via `resolutions`:
https://github.com/eps1lon/yarn-plugin-deduplicate

**Comment by larixer** [comment] 2020-05-11 08:23
@bertho-zero One question, does out of memory happens, when you use released berry? Not the berry from my PR? Is it the PR that leads to out of memory?

**Comment by bertho-zero** [comment] 2020-05-11 09:08
Yes it's also slow with released berry, in the reproduction repo I can see an improvement if in the root package.json I update jest from version 25 to 26.

With released berry:
42 seconds with jest@^25 in root package.json
16 seconds with jest@^26 in root package.json

With branch 1313:
40 seconds with jest@^25 in root package.json
16 seconds with jest@^26 in root package.json
2 minutes without jest in root package.json


If I use Jest@^26 in my real project I have a rather fast link and no out of memory.

**Comment by larixer** [comment] 2020-05-11 09:40
@bertho-zero Alright, so to summarise:
1. Out of memory happens on your real project with both released berry and branch 1313. So branch 1313 does not make things worser
2. Branch 1313 does not affect link step timings, stays roughly the same, but it links packages correctly.
3. Link step can be extraordinary slow and in the end lead to out of memory on some dependency trees, but that can be workaround if the dependency tree is somehow changed.

The point 3 needs serious investigation, you have provided enough info for this investigation to happen. I myself will be able to look into this hopefully starting next week.

**Comment by arcanis** [comment] 2020-05-12 14:01
Reopening to keep track of the memory issue

**Comment by eigilsagafos** [comment] 2020-05-28 11:43
I don't know if this is any value, but I have tried to move a monorepo with 20+ packages to berry a few times. Today I got stuck because of a library not having a peerDependency set. So I switched to `pnpMode: loose`. Before switching linking completed in 8 seconds. After switching I'm getting a memory error after 10+ minutes. (Node 12.13) `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by arcanis** [comment] 2020-05-28 11:45
That's a different issue; this one is only about the nm linker.

**Comment by eigilsagafos** [comment] 2020-05-28 11:47
Thanks @arcanis. Is it a known or tracked issue?

**Comment by larixer** [comment] 2020-05-28 12:24
@eigilsagafos @arcanis Well, I believe these issues have the same cause and I'm working to fix it. It will take some time though, because of hoisting problem complexity.

**Comment by larixer** [comment] 2020-06-02 12:37
@eigilsagafos @bertho-zero Could you check if using yarn from the linked PR fixes your issues with out of memory / super long linking time? You can do so by executing
`yarn set version from sources --branch 1429` inside your project. It would be great if you can provide feedback, thanks!

**Comment by eigilsagafos** [comment] 2020-06-02 12:55
@larixer Confirmed to work. Without loss mode link step takes 14.58s. With loose mode it now finished in 23.25s.

**Comment by larixer** [comment] 2020-06-02 13:05
@eigilsagafos Thank you!

**Comment by bertho-zero** [comment] 2020-06-02 14:42
In the repro repo I go from 28s to 11 seconds (without cache) and 1.7 seconds the second time. In my real repo the link is between 45s and 60s.

It works great!

**Comment by larixer** [comment] 2020-06-06 10:40
@eigilsagafos You might want to rebuild yarn from the PR, the loose mode link time should be only 1 or 2 seconds more than strict pnp link time

**Comment by eigilsagafos** [comment] 2020-06-06 12:31
Looking good @larixer! Cached I'm now seeing 5.55 seconds vs 6.46 seconds in loose mode

**Comment by merceyz** [comment] 2020-06-07 11:33
Memory issue fixed in https://github.com/yarnpkg/berry/pull/1429

**Closed by merceyz** 2020-06-07 11:33 UTC
Labels: bug, node-modules, reproducible
