### ISSUE TITLE
[Feature] execute non-JS executables via `yarn dlx`

### ISSUE THREAD

**Issue by cspotcode** [yarnpkg/berry#4587] opened 2022-06-29 15:23 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

See also: https://github.com/yarnpkg/berry/issues/882

**Describe the user story**

As a developer, I want to write a bash script to be executed by `npx` or `yarn dlx`.  I create an appropriate `package.json` with `bin` field and push it and the shell script to github.  The shell script has an appropriate `#!/usr/bin/env bash`.  This script is internal tooling meant for my team or my company, so it is safe to assume bash and a posix environment.

Unfortunately, yarn today attempts to execute bin scripts via `node` even when they are not js.

**Describe the solution you'd like**

When `yarn dlx` executes a bin entry which is not js, it is executed as a posix executable, not passed to `node`.

**Describe the drawbacks of your solution**

As far as I can tell, this will be backwards compatible.  node scripts will continue to execute via `node`.  But bin entries with non-node shebangs can be executed directly.  Native executables can also be executed directly, I don't think this will cause particular problems.  In https://github.com/evanw/esbuild/issues/237#issuecomment-655265240, it appears that esbuild is deliberately using a native executable and has done the work to do this correctly, with cross-platform supporrt.

**Describe alternatives you've considered**

The motivation for using `npx` or `yarn dlx` is simplicity.  Requiring a plugin is counter to this.

**Comment by merceyz** [comment] 2022-06-29 15:41
Duplicate of https://github.com/yarnpkg/berry/issues/882

**Closed by merceyz** 2022-06-29 15:41 UTC
Labels: enhancement
