### ISSUE TITLE
[Bug?]: ESmodule yarn pnp ts-node broken

### ISSUE THREAD

**Issue by Darkbladecr** [yarnpkg/berry#4335] opened 2022-04-07 17:26 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have [posted this bug with the ts-node team](https://github.com/TypeStrong/ts-node/issues/1709) as it appears to me to be an error with `ts-node/child-loader.mjs` but have been advised to open a ticket here as well as it may be yarn related.

### Expected Behavior
Able to run ts-node with yarn pnp for a simple typescript file.

### Actual Behavior
Breaking on initiation of the esm_loader => ts-node/child-loader
`yarn ts-node ./src/index.ts`

```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/stefan/ts-node/.yarn/__virtual__/ts-node-virtual-645473c738/0/cache/ts-node-npm-10.7.0-ef39b1d45e-2a379e43f7.zip/node_modules/ts-node/child-loader.mjs' imported from /Users/stefan/ts-node/
Did you mean to import /Users/stefan/ts-node/.yarn/__virtual__/ts-node-virtual-645473c738/0/cache/ts-node-npm-10.7.0-ef39b1d45e-2a379e43f7.zip/node_modules/ts-node/child-loader.mjs?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at initializeLoader (node:internal/process/esm_loader:74:49)
    at loadESM (node:internal/process/esm_loader:87:11)
    at runMainESM (node:internal/modules/run_main:51:21) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Steps to reproduce the problem
`yarn init -2`
`yarn install -D typescript ts-node tslib @types/node`
`package.json` - updated to have `"type": "module"` - for ESmodule setup
`touch tsconfig.json` -- see below
`mkdir src`
`touch src/index.ts` -- see below
`yarn ts-node src/index.ts`

### Minimal reproduction
Repo prepared here:
https://github.com/Darkbladecr/ts-node-pnp

package.json
```{
  "name": "ts-node",
  "packageManager": "yarn@3.2.0",
  "type": "module",
  "main": "./dist/index.js",
  "exports": {
    ".": "./dist/index.js",
    "./*": "./dist/*"
  },
  "typesVersions": {
    "*": {
      "main.d.ts": [
        "dist/index.d.ts"
      ],
      "*": [
        "dist/*"
      ]
    }
  },
  "devDependencies": {
    "@types/node": "^17.0.23",
    "ts-node": "^10.7.0",
    "tslib": "^2.3.1",
    "typescript": "~4.3"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "module": "ES2020",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "lib": ["es2020", "DOM"],
    "skipLibCheck": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "declaration": true,
    "baseUrl": ".",
    "removeComments": true,
    "downlevelIteration": true,
    "resolveJsonModule": true
  },
  "ts-node": {
    "esm": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.test.ts"]
}
```

src/index.ts
```
import path from "node:path";
console.log(path.resolve("."));
```

### Specifications

* ts-node version: "^10.7.0"
* node version: "v16.14.2"
* TypeScript version: have tried ~4.3, ~4.4, ~4.5, ~4.6
* tsconfig.json, if you're using one (see above)

* Operating system and version: OSX 12.3

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  Binaries:
    Node: 16.14.2 - /private/var/folders/sb/69xqlm_51qq07xr8ysv7tsfw0000gn/T/xfs-c2db04a1/node
    Yarn: 3.2.0 - /private/var/folders/sb/69xqlm_51qq07xr8ysv7tsfw0000gn/T/xfs-c2db04a1/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

### Additional context

If the package is reverted to commonJS (transpilation) instead of ESModules, then it works with pnp.
If the package is changed from pnp to `nodeLinker: node-modules` then ts-node also works.

However ESModules + pnp does not.

**Comment by merceyz** [comment] 2022-04-07 17:34
Duplicate of https://github.com/yarnpkg/berry/discussions/4044

**Closed by merceyz** 2022-04-07 17:34 UTC
Labels: bug
