### ISSUE TITLE
[Feature] Workspace Distribution / Packaging

### ISSUE THREAD

**Issue by j** [yarnpkg/berry#936] opened 2020-02-11 22:10 UTC
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

The biggest pain point with workspaces currently is that they're aimed towards library development and packaging for NPM.  It would be great if I could package a workspace and include all the modules (& other workspaces) within the output for deployments, etc.

I'm unsure if this is already supported, but if not, I'm wondering if this is something that can be added to yarn / plugin?

`yarn workspace package [workspace]` to create a deployable would be amazing. :)

**Comment by josephwegner** [comment] 2020-02-23 22:00
Seems a duplicate of #859 and #489.

The latter issue has an example of a plugin that apparently does much of the work required to get a "workspace package"... but I haven't even begun to wrap my head around how plugins work yet.

**Comment by merceyz** [comment] 2020-12-09 12:22
Closing as this seems to be solved by using either https://gitlab.com/Larry1123/yarn-contrib/-/tree/master/packages/plugin-production-install or https://yarn.build/

**Closed by merceyz** 2020-12-09 12:22 UTC
Labels: enhancement
