### ISSUE TITLE
[Bug]: Yarn fails to execute Rust binaries (but npm does)

### ISSUE THREAD

**Issue by milesj** [yarnpkg/berry#4146] opened 2022-02-21 19:17 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm working on a project that ships a Rust binary through npm's `bin` field. I have a PR up where I'm experimenting with this: https://github.com/milesj/moon/pull/56

For what it's worth, it currently _works_, but Yarn fails to execute the Rust binary as it throws this error:

```
����


SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

### To reproduce

Since my PR has not landed, you can test this with the [@parcel/css-cli](https://www.npmjs.com/package/@parcel/css-cli) package, which also ships a Rust binary.

```
yarn add --dev @parcel/css-cli
```

```
$ yarn parcel-css
/Users/milesj/Projects/moon/node_modules/@parcel/css-cli/parcel_css:1
����


SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

This works with npm:
```
$ npm run parcel-css
> css
> parcel-css

error: The following required arguments were not provided:
    <INPUT_FILE>

USAGE:
    parcel-css [OPTIONS] <INPUT_FILE>

For more information try --help
```

And also works with npx:
```
$ npx parcel-css
error: The following required arguments were not provided:
    <INPUT_FILE>

USAGE:
    parcel-css [OPTIONS] <INPUT_FILE>

For more information try --help
```

### Environment

```shell
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - /private/var/folders/3_/_4gw29kj089fh24k68n7gxx80000gn/T/xfs-e3bd9a20/node
    Yarn: 3.1.1 - /private/var/folders/3_/_4gw29kj089fh24k68n7gxx80000gn/T/xfs-e3bd9a20/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    jest: ^27.4.7 => 27.4.7
```

**Comment by merceyz** [comment] 2022-02-21 19:50
Duplicate of https://github.com/yarnpkg/berry/issues/882

**Closed by merceyz** 2022-02-21 19:50 UTC
Labels: bug
