### ISSUE TITLE
[Bug] `yarn workspaces foreach` only running in a single directory, on node 15

### ISSUE THREAD

**Issue by xsanda** [yarnpkg/berry#2475] opened 2021-02-13 20:01 UTC
- [x] I'd be willing to implement a fix

**Describe the bug**

`yarn workspaces foreach run` is only running in a single workspace, rather than in every workspace, when run with node 15.8.0. On Node 12 and Node 14, this works correctly.

**To Reproduce**

Install node 15.8.0 (e.g. with docker, by running `docker run -i mhart/alpine-node:15.8.0`), and run the following commands.

```shell
mkdir mwe; cd mwe
echo '{ "private": true, "workspaces": [ "w1", "w2" ] }' > package.json
yarn set version berry
yarn plugin import workspace-tools
mkdir w1 w2
echo '{ "name": "@mwe/w1", "scripts": { "test": "echo passed w1" } }' > w1/package.json
echo '{ "name": "@mwe/w2", "scripts": { "test": "echo passed w2" } }' > w2/package.json
yarn
yarn workspaces foreach run test
```

This only logs `passed w1`, compared to `passed w1 passed w2` on Node 14 and older versions.

I was not able to reproduce this in Sherlock, because (as far as I can see) it does not let you choose the version of Node.

**Screenshot**

Note that, for whatever reason, this Docker image does not have any characters at the start of the prompt. In these screenshots, all but the last line is pasted together, and then the final line is pasted after everything has run through.

![image](https://user-images.githubusercontent.com/8607022/107860155-9e1db080-6e35-11eb-86b5-254e78dadd76.png)

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.15.7, and [mhart/alpine-node](https://hub.docker.com/r/mhart/alpine-node)
 - Node version 15.8.0
 - Yarn version 2.4.0

**Comment by merceyz** [comment] 2021-02-13 20:02
Duplicate of https://github.com/yarnpkg/berry/issues/2214
Duplicate of https://github.com/yarnpkg/berry/issues/2074
Duplicate of https://github.com/yarnpkg/berry/issues/2396
Fixed in https://github.com/yarnpkg/berry/pull/2255

**Closed by merceyz** 2021-02-13 20:02 UTC
Labels: bug
