### ISSUE TITLE
[Feature] Yarn should look for yarn.lock files up until it finds a .yarn folder

### ISSUE THREAD

**Issue by willgriffiths** [yarnpkg/berry#631] opened 2019-12-12 20:18 UTC
- [ ] I'd be willing to implement this feature (Depends on the complexity :)

**Describe the user story**

As a yarn user I'm confused when I see the error:
```
Usage Error: The project in /Users/username/package.json doesn't seem to have been installed - running an install there might help
```
See: https://github.com/yarnpkg/berry/issues/625

**Describe the solution you'd like**

Yarn should only look for yarn.lock files up the file tree until it finds a .yarn folder? 

**Describe the drawbacks of your solution**

- No idea how complex it is to implement. 

**Describe alternatives you've considered**

A more descriptive error message that details exactly how to fix the problem. For example:
```
Usage Error: Yarn install was ran in /Users/username/projects/new-project but there is a lock file in a parent directory /Users/username/yarn.lock. Please clean this up and run yarn install again.
```

**Comment by arcanis** [comment] 2019-12-12 21:13
I'm not sure it would work - if there isn't a lockfile, there's probably no `.yarn` folder either 🤔

> Usage Error: Yarn install was ran in /Users/username/projects/new-project but there is a lock file in a parent directory /Users/username/yarn.lock. Please clean this up and run yarn install again.

The problem is that running `yarn install` in a subfolder of a project is a valid use case 🤔 Maybe we could simply start by blacklisting `$HOME` as project location?

**Comment by larixer** [comment] 2019-12-13 05:22
@arcanis Maybe we can check that both `yarn.lock` and `package.json` exist?

**Comment by willgriffiths** [comment] 2019-12-13 05:40
Yep, it makes sense that is probably no `.yarn` folder.

I had a yarn.lock in two parent folders and blacklisting $HOME would help with one case. 
```
~/yarn.lock
~/Projects/yarn.lock
``` 

Perhaps if the error also mentioned the `yarn.lock` as well as `package.json` it would be easier to track down and fix the error? 🤷‍♂

**Comment by srcspider** [comment] 2021-11-24 12:50
@willgriffiths 

When yarn has to go out of the current working directory and errors out in any way it should just print what it thought was the project root after whatever other error. That should solve any confusion, while not affecting some other use cases. _After all whenever you get an error you usually want the clear context of what exactly is going on anyway._ 

eg.

Instead of:
```bash
Usage Error: The project in /home/user/path/to/project/package.json doesn't seem to have been installed - running an install there might help

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
```
Should be:
```bash
Usage Error: The project in /home/user/path/to/project/package.json doesn't seem to have been installed - running an install there might help

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]

Warning: We assumed /home/user is your project's root directory because it has .yarnrc in it. Please remove those files if this is incorrect.
Warning: Your package.json is located in /home/user/path/to/project/package.json but we are using /home/user as the project root which doesn't have a package.json due to presence of .yarn in it.
Warning: The project root path yarn sees appears to be your system home directory. This is usually a mistake. Please remove .yarn / .yarnrc files from it.
```
The messages there are just an example, someone a lot more familiar with yarn can probable make it actually suggest a better solution then just removing files.

**Comment by srcspider** [comment] 2021-11-24 13:13
Something else weird is that I run `yarn set version berry` and it creates `.yarn` and `.yarnrc.yml`, all good so far. If I then run `yarn set version stable` (as per the docs: https://yarnpkg.com/getting-started/install) yarn will get out of the current project and create yarn stuff in the parent folder. I really don't understand what convoluted logic it's using but whatever it's trying to do is very unintuitive. 

Also when running `yarn init -2` on an empty folder it also initializes git it seems. It's fine if it was just creating a .gitignore or updating one, but whats with the random README.md, .editorconfig, and .git ? I actually use .editorconfig but still was wierd (and not really welcome) for yarn to just decide to throw it's own version there.

*It feels like the only sane way to get it setup is to set it up by hand and be extra careful with it.*

**Comment by merceyz** [comment] 2022-10-01 16:00
Closing as the described solution wouldn't work as `.yarn` isn't guaranteed to exist and the alternative solution has been implemented, the error message currently looks like the following:

```console
$ yarn
Usage Error: The nearest package directory (/home/foo/new-project) doesn't seem to be part of the project declared in /home/foo.

- If /home/foo isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /home/foo is intended to be a project, it might be that you forgot to list new-project in its workspace configuration.
- Finally, if /home/foo is fine and you intend new-project to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
```
Ref https://github.com/yarnpkg/berry/pull/4038

**Closed by merceyz** 2022-10-01 16:00 UTC
Labels: enhancement
