### ISSUE TITLE
[Bug] Unsupported option name ("--save") on yarn patch-commit

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#2602] opened 2021-03-15 09:43 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

A clear and concise description of what the bug is. A bug is **unintended**. A feature not being
implemented is **not a bug**, and your issue may be closed for misleading labeling.

As stated in documentation, https://yarnpkg.com/cli/patch-commit, yarn patch-commit can be run with --save flag to use patch in a given repo.

However, when run, it says there's no such option name:

```
% yarn patch react-vis                                                                    
➤ YN0000: Package react-vis@npm:1.11.7 got extracted with success!
➤ YN0000: You can now edit the following folder: /private/var/folders/h7/yd7dwy6x5fqgw_gkv2gb_vw80000gp/T/xfs-0ea81d2b
➤ YN0000: Once you are done run yarn patch-commit /private/var/folders/h7/yd7dwy6x5fqgw_gkv2gb_vw80000gp/T/xfs-0ea81d2b and Yarn will store a patchfile based on your changes.
➤ YN0000: Done in 0s 156ms

% yarn patch-commit --save /private/var/folders/h7/yd7dwy6x5fqgw_gkv2gb_vw80000gp/T/xfs-0ea81d2b 
Unknown Syntax Error: Unsupported option name ("--save").
```

$ yarn patch-commit <patchFolder>

**To Reproduce**

* `yarn patch SOME_DEP_HERE`
* `yarn patch-commit --save PATCH_FOLDER_HERE`

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] macOS Big Sur
 - Node version [e.g. 8.15.0, 10.15.1, ...] 15.11.0
 - Yarn version [e.g. 2.4.0, ...] 2.4.0

**Comment by paul-soporan** [comment] 2021-03-15 09:49
Duplicate of #2579.

**Closed by paul-soporan** 2021-03-15 09:49 UTC
Labels: bug
