### ISSUE TITLE
Unable to open type definitions on any platform.

### ISSUE THREAD

**Issue by TheGrimSilence** [yarnpkg/berry#1791] opened 2020-09-03 03:49 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

No matter Windows or Linux, I'm getting Errors when trying to access "Go To Definition" in TypeScript files. Specifically 
`Unable to open 'index.d.ts': Unable to read file 'vscode-remote://wsl+ubuntu/zip:/home/.../.yarn/cache/.../index.d.ts' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu/zip:/home/.../.yarn/cache/.../index.d.ts').`

I've tried updating all yarn dependencies but nothing works.

**Screenshots**

![Screenshot_21](https://user-images.githubusercontent.com/11479772/92069141-a944be80-ed76-11ea-80ae-61d9b67f6e81.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows && WSL2
 - Node version: 14
 - Yarn version: 2.1.1

**Comment by wozzo** [comment] 2020-09-03 07:44
I've got the same on yarn 2.2.2

**Comment by merceyz** [comment] 2020-09-03 07:50
Did you update vscode recently? If so, then it's this upstream issue https://github.com/microsoft/vscode/issues/105014

**Comment by wozzo** [comment] 2020-09-03 07:55
I just downgraded to 1.47.3 on Windows and still get the same issue.
@TheGrimSilence this issue appears to duplicate https://github.com/yarnpkg/berry/issues/1758 where there's more info.
I'll watch that issue thanks @merceyz

**Comment by TheGrimSilence** [comment] 2020-09-03 08:02
> Did you update vscode recently? If so, then it's this upstream issue https://github.com/microsoft/vscode/issues/105014

Just saw in the discord! Thank you

**Comment by merceyz** [comment] 2020-09-03 16:08
Closing as duplicate of https://github.com/yarnpkg/berry/issues/1758

**Closed by merceyz** 2020-09-03 16:08 UTC
Labels: bug
