### ISSUE TITLE
[Bug?]: Yarn 4 with nodeLinker pnpm doesn't add +x permission to binaries that don't end with .js

### ISSUE THREAD

**Issue by imballinst** [yarnpkg/berry#5886] opened 2023-10-28 01:46 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

It seems like, an extensionless binary file isn't given `+x` permission when I am using Yarn 4 (4.0.0) with `nodeLinker: pnpm`. It works well in Yarn 3 (3.6.4), though. As can be seen below, I tried to list the file and permissions, and the one in the `yarn3` folder have the `x` permission whereas the one in `yarn4` doesn't.

```
@imballinst ➜ /workspaces/yarn-4-pnpm-esbuild-binary-issue/yarn3-esbuild (main) $ ls -al node_modules/esbuild/bin
total 20
drwxr-xr-x+ 2 root root 4096 Jun 22  1984 .
drwxr-xr-x+ 5 root root 4096 Jun 22  1984 ..
-rwxr-xr-x  1 root root 9180 Jun 22  1984 esbuild

@imballinst ➜ /workspaces/yarn-4-pnpm-esbuild-binary-issue/yarn3-esbuild (main) $ ls -al ../yarn4-esbuild/node_modules/esbuild/bin 
total 20
drwxr-xr-x+ 2 root root 4096 Jun 22  1984 .
drwxr-xr-x+ 4 root root 4096 Jun 22  1984 ..
-rw-rw-rw-  2 root root 9180 Jun 22  1984 esbuild
```

This causes the following error:

```
➤ YN0000: · Yarn 4.0.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.19.5 must be built because it never has been before or the last one failed
➤ YN0009: │ esbuild@npm:0.19.5 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-cda089f1/build.log)
➤ YN0000: └ Completed in 0s 246ms
➤ YN0000: · Failed with errors in 0s 317ms

---

<ref *1> Error: spawnSync /workspaces/yarn-4-pnpm-esbuild-binary-issue/yarn4-esbuild/node_modules/.store/@esbuild-linux-x64-npm-0.19.5-26d0ff8fb5/package/bin/esbuild EACCES
```

Presumably because it doesn't have access to run the `esbuild` binary in Yarn 4, whereas in Yarn 3 it could.

### To reproduce

1. Clone https://github.com/imballinst/yarn-4-pnpm-esbuild-binary-issue
2. Run `yarn` in the `yarn3-esbuild` folder -- it should be successful
3. Run `yarn` in the `yarn4-esbuild` folder -- it should not be successful

The only dependency is `esbuild`. Probably the same also happens for other kind of dependencies which binary file doesn't have a `.js` extension. Not sure.

### Environment

```shell
System:
  OS: Linux 6.2 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  CPU: (2) x64 AMD EPYC 7763 64-Core Processor
Binaries:
  Node: 18.16.0 - /tmp/xfs-aca5b09d/node
  Yarn: 4.0.0 - /tmp/xfs-aca5b09d/yarn
  npm: 9.5.1 - /usr/local/bin/npm
  pnpm: 8.6.1 - /usr/local/share/npm-global/bin/pnpm
```

### Additional context

This bug doesn't happen when I use `nodeLinker: pnp` and `nodeLinker: node-modules`, both in Yarn 3 and Yarn 4.

**Comment by 7rulnik** [comment] 2023-10-28 15:13
Duplicates https://github.com/yarnpkg/berry/issues/5165

**Comment by arcanis** [comment] 2023-11-01 18:51
Closing as duplicate of #5165

**Closed by arcanis** 2023-11-01 18:51 UTC
Labels: bug
