### ISSUE TITLE
[Bug] killing yarn process should kill child process in scripts

### ISSUE THREAD

**Issue by albertywu** [yarnpkg/berry#2150] opened 2020-11-19 21:22 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

When running `yarn <cmd>`, the process spawned in package.json `scripts` is not terminated when the parent yarn process id is terminated using SIGTERM kill signal (`kill <pid>`). This is different from yarn v1 behavior, where a SIGTERM kill signal on the parent yarn process id would terminate processes spawned in scripts.

**To Reproduce**

https://github.com/albertywu/yarn2-termination-bug#repro

**Comment by merceyz** [comment] 2020-11-22 14:33
Duplicate of https://github.com/yarnpkg/berry/issues/1741

**Closed by merceyz** 2020-11-22 14:33 UTC
Labels: bug
