### ISSUE TITLE
[Bug?]: Yarn --cwd is ignored inside script

### ISSUE THREAD

**Issue by Rugvip** [yarnpkg/berry#4805] opened 2022-08-31 14:36 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Running `yarn --cwd <path> <command>` behaves differently if it's run within `"scripts"` compared to if it's run directly manually. It seems as though the `--cwd` flag is ignored within the script.

### To reproduce

Clone https://github.com/Rugvip/yarn-3-repro

Run `yarn say-hello`, you'd expect this to print `hello from subdir`, but it instead prints `hello from root`.

Run `yarn --cwd subdir run hello`, which prints `hello from subdir` as expected.

### Environment

```shell
System:
  OS: macOS 12.5.1
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 16.14.2 - /private/var/folders/ll/hcvgyy216t70dkjxwkk7csn00000gn/T/xfs-0e88568e/node
  Yarn: 3.2.3 - /private/var/folders/ll/hcvgyy216t70dkjxwkk7csn00000gn/T/xfs-0e88568e/yarn
  npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

**Comment by merceyz** [comment] 2022-08-31 15:57
Duplicate of https://github.com/yarnpkg/berry/issues/2346

**Closed by merceyz** 2022-08-31 15:57 UTC
Labels: bug
