### ISSUE TITLE
[Bug?]: Auto-import in VSCode not working

### ISSUE THREAD

**Issue by avwie** [yarnpkg/berry#5361] opened 2023-03-30 20:19 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I am writing a minimal example to show some architecture stuff to colleagues. However, I ran into the problem that VSCode doesn't suggest imports from other packages.

### To reproduce

A minimal example can be found here:
https://github.com/avwie/clean-architecture-poc/tree/minimal-autocomplete

When going into the `packages/features/soundfiles/src/index.ts` file you can see a `sayHello` function that is part of the `https://github.com/avwie/clean-architecture-poc/blob/minimal-autocomplete/packages/libraries/soundaware/src/index.ts`

After running `yarn build` it should be possible to resolve this to `@avwie/libraries-soundaware/dist`.

However, VSCode is unable to suggest the import. When `import {} from "@avwie/libraries-soundaware/dist"` is added, it will suggest to add `sayHello` to the import.

Is there something wrong in my `tsconfig` or is there some other issue? I have already configured VSCode to use the Typescript version of the workspace of course.

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.4.0 - /private/var/folders/y0/n5_y1nyx03dcxrz1hp9pf8xc0000gn/T/xfs-72e88b54/node
    Yarn: 3.5.0 - /private/var/folders/y0/n5_y1nyx03dcxrz1hp9pf8xc0000gn/T/xfs-72e88b54/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v18.4.0/bin/npm
```

**Comment by merceyz** [comment] 2023-03-31 07:51
Duplicate of https://github.com/yarnpkg/berry/issues/5345

**Closed by merceyz** 2023-03-31 07:51 UTC
Labels: bug

**Comment by avwie** [comment] 2023-03-31 10:59
Using `yarn set version from sources --branch 5351` from issue #5345 does _not_ solve the problem. So this isn't a duplicate.

**Comment by merceyz** [comment] 2023-03-31 15:52
I can reproduce the issue when switching your reproduction to `nodeLinker: node-modules` and explicitly building the `@avwie/libraries-soundaware` workspace with `yarn workspace @avwie/libraries-soundaware run -T tsc` so that part is a misconfiguration in the reproduction.

If I apply the following diff then VSCode is able to suggest `import { sayHello } from "@avwie/libraries-soundaware"`.

```diff
diff --git a/packages/libraries/soundaware/package.json b/packages/libraries/soundaware/package.json
index 5c55704..0510a1b 100644
--- a/packages/libraries/soundaware/package.json
+++ b/packages/libraries/soundaware/package.json
@@ -2,5 +2,6 @@
   "name": "@avwie/libraries-soundaware",
   "version": "1.0.0",
   "main": "index.js",
+  "types": "./dist/index.d.ts",
   "license": "MIT"
 }

```

The part that made me mark this as a duplicate of https://github.com/yarnpkg/berry/issues/5345 is if I then switch to `nodeLinker: pnp` again and update the SDK with `yarn dlx @yarnpkg/sdks vscode` VSCode doesn't suggest any imports.

Updating to the latest canary build of Yarn, which at the moment is almost the same as the `set version` you used, makes VSCode suggest the import again.

```sh
rm .yarnrc.yml
yarn set version canary
yarn
```
