### ISSUE TITLE
[Feature] just using npm install yarn to use  new yarn

### ISSUE THREAD

**Issue by John0King** [yarnpkg/berry#1969] opened 2020-10-13 14:19 UTC
- [ ] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin

**Describe the user story**
not everyone can access github without limit !  for example : CN,  can access 90% of github service with low bandwidth
```powershell
PS E:\demo> yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information provided in "E:\\demo\\yarn-error.log".      
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```
**Describe the solution you'd like**

just give me  the global binary with `npm install -g yarn`

**Describe the drawbacks of your solution**

None.

**Describe alternatives you've considered**

`npm install -g Yarn2`

**Additional context**

None

**Comment by arcanis** [comment] 2020-10-13 14:23
Duplicate of https://github.com/yarnpkg/berry/issues/982

**Closed by arcanis** 2020-10-13 14:23 UTC
Labels: enhancement
