### ISSUE TITLE
[Feature] Install all required plugins

### ISSUE THREAD

**Issue by codan84** [yarnpkg/berry#5405] opened 2023-04-24 09:43 UTC
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I add a plugin to my yarn config:
```
yarn plugin import @yarnpkg/plugin-workspace-tools
```

And commit `.yarnrc.yml` file with generated plugin section:
```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
```

Now I run in CI:
```
yarn install
```

And get an error (similar to this, ignore paths as I am replicating this locally):
```
yarn install      
Internal Error: Cannot find module '/Users/danielgruszczyk/workspace/homarus/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs'
Require stack:
- /Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js
Require stack:
- /Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/danielgruszczyk/.nvm/versions/node/v16.13.2/lib/node_modules/corepack/dist/vcc.js:170:20)
    at o4 (/Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js:390:12580)
    at pf (/Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js:390:13423)
    at D (/Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js:391:21733)
    at Function.find (/Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js:391:22339)
    at async i (/Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js:446:10705)
    at async t (/Users/danielgruszczyk/.node/corepack/yarn/3.5.0/yarn.js:446:10283)
```  
 
---

(discovered/added *after* initiall issue was created)
In fact, when the `.yarn` dir gets deleted, one can't run any yarn command any more, due to the missing plugin (can't even `yarn plugin import @yarnpkg/plugin-workspace-tools`)! the plugin section of `.yarnrc.yml` has to be removed and plugin re0imported. This surely must be a bug?!

---

**Describe the solution you'd like**

I'd like to have an option to run a command that would download all plugins required in `.yarnrc.yml`.  
Right now in CI I still have to run `yarn plugin import @yarnpkg/plugin-workspace-tools`, as obviously I do not commit `.yarn` to the repo.  
This is not a good design - a developer now has to remember to add the `yarn plugin import xyz` command to the CI script whenever a new plugin is added/used.  
  
Maybe something like `yarn install --fetch-plugins` would do?

**Describe the drawbacks of your solution**

I can't forsee any major issues with this. Save from 3rd party plugins (imported via URL) being deleted at the source, but that would break the `yarn plugin import xyz` command too.

**Describe alternatives you've considered**

Adding a section in my repos README spelling in big letters that we need to add `yarn plugin import xyz` commands if using a new yarn plugin. Not something I like as we can't guarantee a dev will read this section.

**Comment by merceyz** [comment] 2023-04-24 21:27
Duplicate of https://github.com/yarnpkg/berry/issues/4464

**Closed by merceyz** 2023-04-24 21:27 UTC
Labels: enhancement
