### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by jaydubb12** [yarnpkg/berry#3053] opened 2021-06-28 16:29 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

 As a developer I can leverage yarn workspaces without having to set the project values as <"private":true> to alleviate conflicts, issues and confusion with publishing packages.

**Describe the solution you'd like**

Remove the requirement that a package be set to <"private":true>, as this creates a challenge with publishing projects, as lerna, and command npm publish do allow for the package(s) to be published when this value is set in the package.json.   Conversely, workspaces cannot be used unless this value is set.

Error Message when package is published using npm publish --access restricted
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.

**Describe the drawbacks of your solution**

None known

**Describe alternatives you've considered**

None Known

**Comment by merceyz** [comment] 2021-06-28 16:33
Duplicate of https://github.com/yarnpkg/berry/issues/960

**Closed by merceyz** 2021-06-28 16:33 UTC
Labels: enhancement
