### ISSUE TITLE
[UX] Output quite noisy if empty cache

### ISSUE THREAD

**Issue by levrik** [yarnpkg/berry#860] opened 2020-01-31 14:40 UTC
![image](https://user-images.githubusercontent.com/9491603/73547725-d11a1f80-443f-11ea-997b-6a1a77ed9adb.png)

The output is quite noisy if the cache is empty.
I don't think that this is really useful information. Maybe in some verbose mode.
Also I'm completely lost now with finding the error that is mentioned in the last line. These are many many pages of cache "warnings".

**Comment by larixer** [comment] 2020-01-31 14:45
Duplicate of #816

**Closed by larixer** 2020-01-31 14:45 UTC

**Comment by levrik** [comment] 2020-01-31 14:49
@larixer Ah, sorry. Missed that one.

**Comment by larixer** [comment] 2020-01-31 14:58
@levrik No problems!
