### ISSUE TITLE
[Bug?]: missing cross platform packages with ZeroInstalls fail --immutable-cache check in CI

### ISSUE THREAD

**Issue by Unibozu** [yarnpkg/berry#4889] opened 2022-09-23 08:56 UTC
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

We use yarn3 with Zero Installs. `yarn install --immutable-cache` fails in CI (linux environment) due to a missing `linux` only package that was not installed when I ran `yarn add` on my macbook.

Yarn on my macbook installed `@msgpackr-extract/msgpackr-extract-darwin-arm64` in the cache folder.
Yarn in the CI (on linux) expected `@msgpackr-extract/msgpackr-extract-linux-x64` in the cache folder.

The failure in the CI seems sensible since the package is missing, but I have not found a way to force add this package to the cache using `yarn add`. Should yarn be aware of the environments it is expected to run so it can add the packages matching those conditions to the cache folder?

CI log

```
$ yarn install --immutable-cache
➤ YN0000: ┌ Resolution step
Resolution step
00:00
➤ YN0000: └ Completed in 0s 327ms
➤ YN0000: ┌ Fetch step
Fetch step
00:00
➤ YN0056: │ @msgpackr-extract/msgpackr-extract-linux-x64@npm:2.1.2: Cache entry required but missing for @msgpackr-extract/msgpackr-extract-linux-x64@npm:2.1.2
➤ YN0013: │ 1185 packages were already cached, one had to be fetched (@msgpackr-extract/msgpackr-extract-linux-x64@npm:2.1.2)
➤ YN0000: └ Completed in 0s 425ms
➤ YN0000: Failed with errors in 0s 845ms
```

Relevant entries from `yarn.lock`

```
"@msgpackr-extract/msgpackr-extract-darwin-arm64@npm:2.1.2":
  version: 2.1.2
  resolution: "@msgpackr-extract/msgpackr-extract-darwin-arm64@npm:2.1.2"
  conditions: os=darwin & cpu=arm64
  languageName: node
  linkType: hard

"@msgpackr-extract/msgpackr-extract-darwin-x64@npm:2.1.2":
  version: 2.1.2
  resolution: "@msgpackr-extract/msgpackr-extract-darwin-x64@npm:2.1.2"
  conditions: os=darwin & cpu=x64
  languageName: node
  linkType: hard

"@msgpackr-extract/msgpackr-extract-linux-arm64@npm:2.1.2":
  version: 2.1.2
  resolution: "@msgpackr-extract/msgpackr-extract-linux-arm64@npm:2.1.2"
  conditions: os=linux & cpu=arm64
  languageName: node
  linkType: hard

"@msgpackr-extract/msgpackr-extract-linux-arm@npm:2.1.2":
  version: 2.1.2
  resolution: "@msgpackr-extract/msgpackr-extract-linux-arm@npm:2.1.2"
  conditions: os=linux & cpu=arm
  languageName: node
  linkType: hard

"@msgpackr-extract/msgpackr-extract-linux-x64@npm:2.1.2":
  version: 2.1.2
  resolution: "@msgpackr-extract/msgpackr-extract-linux-x64@npm:2.1.2"
  conditions: os=linux & cpu=x64
  languageName: node
  linkType: hard

"@msgpackr-extract/msgpackr-extract-win32-x64@npm:2.1.2":
  version: 2.1.2
  resolution: "@msgpackr-extract/msgpackr-extract-win32-x64@npm:2.1.2"
  conditions: os=win32 & cpu=x64
  languageName: node
  linkType: hard
```

### To reproduce

The reproduction should be fairly easy but I couldn't find how to emulate platforms with sherlock or the code sandbox. Help needed - I will happily provide a sherlock reproduction if one can point me in the right direction.

https://www.npmjs.com/package/msgpackr-extract installs one of the platform-specific pre-build dependency.

1. Init local project with yarn 3 and zero installs
2. On a "mac" platform. `yarn add msgpackr-extract`. 
3. On linux/x64 platform. `yarn install --immutable --immutable-cache` should fail because `@msgpackr-extract/msgpackr-extract-linux-x64` is not in the cache folder

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.6.0 - /private/var/folders/wx/w_c3tqw561q_dbhxwx2g7bwm0000gp/T/xfs-2d4ce973/node
    Yarn: 3.2.2 - /private/var/folders/wx/w_c3tqw561q_dbhxwx2g7bwm0000gp/T/xfs-2d4ce973/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
```

**Comment by merceyz** [comment] 2022-09-23 09:01
Duplicate of https://github.com/yarnpkg/berry/issues/4514

**Closed by merceyz** 2022-09-23 09:01 UTC
Labels: bug
