### ISSUE TITLE
[Bug?]: Error when script name contains a colon "Couldn't find a script named "

### ISSUE THREAD

**Issue by paulrberg** [yarnpkg/berry#3489] opened 2021-09-24 15:12 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Script names that contain a colon cause yarn to not execute it. The context in which I am running the script is at the root of a monorepo maintained with the yarn workspaces plugin. The name of the script is used both at the root and in my packages.

### To reproduce

I don't think that I can reproduce this with Sherlock. The bug occurs in a yarn workspaces monorepo - I couldn't find a way to replicate that in a Sherlock Playground.

Here's the minimal reproductions I could come up with (it uses my project repository):

```bash
$ git clone git@github.com:hifi-finance/hifi.git
$ git checkout e034f9f2dd662edd9a88ef6e9fb7d47afaa4d87b
$ yarn install
$ yarn run clean:node_modules
```

### Environment

```shell
System:
  OS: macOS 11.5.2
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Binaries:
  Node: 16.6.1 - /private/var/folders/l9/26z2wy2x0_l5sm7v2y7cgp940000gq/T/xfs-bc43f169/node
  Yarn: 3.0.2 - /private/var/folders/l9/26z2wy2x0_l5sm7v2y7cgp940000gq/T/xfs-bc43f169/yarn
  npm: 7.23.0 - /var/folders/l9/26z2wy2x0_l5sm7v2y7cgp940000gq/T/fnm_multishells/26176_1632495562919/bin/npm
```

### Additional context

Error as I saw it on my machine:

<img width="518" alt="Yarn bug screenshot" src="https://user-images.githubusercontent.com/8782666/134696820-efc3dbdd-f473-417b-994b-6d0303cdb09d.png">

It seems like @merceyz is already aware of this bug:

<img width="973" alt="@merceyz message about bug on Discord" src="https://user-images.githubusercontent.com/8782666/134697186-087e6239-db2d-40d6-9a14-3f8d034fbfe8.png">

**Comment by merceyz** [comment] 2021-09-24 15:16
Duplicate of https://github.com/yarnpkg/berry/issues/3048

**Closed by merceyz** 2021-09-24 15:16 UTC
Labels: bug
