### ISSUE TITLE
[Bug?]: yarn exits with code 0 if run out of memory

### ISSUE THREAD

**Issue by clhuang** [yarnpkg/berry#4181] opened 2022-03-03 20:17 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

running `yarn install` in a memory-constrained environment exits with code 0, instead of an error code, causing Docker / CI platforms to think that the install succeeded. Proper behavior would be to throw an error of some sort.

Mirrors the behavior of https://github.com/yarnpkg/berry/issues/905 which was closed due to lack of repro.

### To reproduce

within this repo: https://github.com/clhuang/yarn-oom-repro
run `docker build . --no-cache --memory 1024m`

observe that `yarn install` exits partway through the fetch step and returns exit code 0.

### Environment

```shell
System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
  Binaries:
    Node: 16.13.0 - /tmp/xfs-592adca2/node
    Yarn: 3.1.1 - /tmp/xfs-592adca2/yarn
    npm: 8.1.0 - /tmp/fnm_multishells/6151_1646337413661/bin/npm
```

**Comment by RDIL** [comment] 2022-03-03 21:28
Duplicate of #3996

**Closed** 2022-03-03 21:53 UTC
Labels: bug
