### ISSUE TITLE
[Bug?]: Yarn pnp / sdk generation doesn't work with ESLint new flat config support

### ISSUE THREAD

**Issue by dbaeumer** [yarnpkg/berry#6219] opened 2024-04-11 10:32 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

ESLint's new flat config support fails to load when using flat config module files. It does work when using common JS config files.

This bahviour gor reported against the VS Code ESLint extension (see https://github.com/microsoft/vscode-eslint/issues/1620) but it is independent of the VS Code extension and can be reproduce using the eslint npm package standalone

### To reproduce

Setup:

`package.json`

```json
{
  "name": "yarn-eslint-test",
  "packageManager": "yarn@4.1.1",
  "type": "module",
  "scripts": {
    "eslint": "eslint test.js"
  },
  "devDependencies": {
    "@eslint/js": "^8.57.0",
    "eslint": "^8.57.0"
  }
}
```

`eslint.config.mjs`

```js
import js from "@eslint/js";

export default [
	js.configs.recommended,
	{
		files: ["**/*.js"],
		rules: {
			"no-var": "error",
		}
	}
];
```

`test.js`
```js
var x = 10;
```

Run the following commands in a shell:

```
> corepack enable
> yarn install
> yarn dlx @yarnpkg/sdks vscode
> export NODE_PATH=".yarn/sdks"
```

Setting the NODE_PATH is equivalent to setting the VS Code eslint.nodePath setting.

start node REPL and execute the following commands (to ensure to mimic the executing since a VS Code extension):

```
require.resolve('eslint');
```

We will load the eslint npm module from .yarn/sdks

```
const library = require('eslint');
```

```
async function main() { const eslint = new (await library.loadESLint({ useFlatConfig: true }))(); const report = await eslint.lintText(`var test = "hello";`); console.log(report); }
```

```
main().catch((error) => { console.error(error); process.exitCode = 1; });
```

You get:

![Image](https://github.com/yarnpkg/berry/assets/1931590/9e0f8be9-4ac5-4aef-85a8-071741a92040)

Expected behavior: the eslint.config.mjs can successfully be loaded. Converting the config file to cjs makes everything work. 

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
  Binaries:
    Node: 18.18.2 - /tmp/xfs-e72dc863/node
    Yarn: 4.1.1 - /tmp/xfs-e72dc863/yarn
    npm: 9.8.1 - ~/.nvs/default/bin/npm

**Comment by dbaeumer** [comment] 2024-05-06 08:20
Any news on this. This issue is basically blocking flat config adaption with VS Code / eslint extension.

**Comment by arcanis** [comment] 2024-05-06 09:48
I'm looking right now at migrating this repository to Eslint 9; I'll take a look at that at the same time.

**Comment by arcanis** [comment] 2024-05-06 16:49
I'm experimenting in https://github.com/yarnpkg/berry/pull/6278 - it seems to work with your (very detailed, thanks a lot!) reproduction, but it still fails in VSCode. Trying to figure out what might be different.

**Comment by arcanis** [comment] 2024-05-06 17:01
I think I figured it out - [v18.19.0 is the first version that supports `register`](https://nodejs.org/api/url.html#urlpathtofileurlpath-options) (to add ESM loaders at runtime), and [VSCode ships with Electron 28](https://github.com/microsoft/vscode/blob/e3d04f279f689a702b9e0939cb0d8dabbe309593/package.json#L151C18-L151C24), which is [tied to Node 18.18](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline). So unfortunately I'm afraid we can't do much right now 🫤

**Comment by dbaeumer** [comment] 2024-05-07 06:56
@arcanis thanks for looking into this.

Which node version is required to make this work. I tested the same steps under Node 20.10.0 and it produces the same exception.


![Image](https://github.com/yarnpkg/berry/assets/1931590/f886dc66-a77c-4d3e-9e9d-e78b18799df8)

**Comment by arcanis** [comment] 2024-05-07 09:34
You need both my PR (https://github.com/yarnpkg/berry/pull/6278) and [Node >v20.6.0, v18.19.0](https://nodejs.org/api/module.html#moduleregisterspecifier-parenturl-options); you can try it by cloning my branch and running your repro in this repo.

**Comment by dbaeumer** [comment] 2024-05-07 12:41
Thanks!

We will move to Electron 29 in the near future which will come with NodeJS 20.x

**Comment by dbaeumer** [comment] 2024-05-21 15:19
@arcanis do you have any timeline when this will show up in `yarn dlx`?

**Comment by arcanis** [comment] 2024-05-21 20:32
I'd like to confirm it works before merging it - is there a vscode build with an up-to-date Node.js?

**Comment by clemyan** [comment] 2024-05-22 01:35
> is there a vscode build with an up-to-date Node.js?

The insiders build has updated to Electron 29 with Node 20.9

**Comment by dbaeumer** [comment] 2024-05-22 05:23
@clemyan thanks for point it out.

@arcanis you can find the insider build here: https://code.visualstudio.com/insiders/

**Comment by n0099** [comment] 2024-06-06 02:57
https://github.com/yarnpkg/berry/issues/6219#issuecomment-2098317034
> We will move to Electron 29 in the near future which will come with NodeJS 20.x

https://code.visualstudio.com/updates/v1_90#_electron-29-update

https://github.com/yarnpkg/berry/issues/6219#issuecomment-2097869912
> You need both my PR (https://github.com/yarnpkg/berry/pull/6278) and [Node >v20.6.0, v18.19.0](https://nodejs.org/api/module.html#moduleregisterspecifier-parenturl-options); you can try it by cloning my branch and running your repro in this repo.

I can confirm this still won't work with extension [`dbaeumer.vscode-eslint@3.0.7`](https://github.com/microsoft/vscode-eslint/issues/1644#issuecomment-2031582679) on both `vscode@1.89` with `node@18.18`, `vscode@1.90` with `node@20.9` and `vscode-insider@1.91`, or even using my system wide [`node@22.2`](https://github.com/n0099/open-tbm/blob/07865ef099fce7f7e951f63bce18e1adc57d3366/fe/.vscode/settings.json#L12) via https://github.com/yarnpkg/berry/pull/6278#issuecomment-2149229422

**Comment by arcanis** [comment] 2024-06-06 15:07
@n0099 did you try with https://github.com/yarnpkg/berry/pull/6278? I just tried and this PR, together with vscode-insider, seems to work fine. I'll look at making a final merge and release soon.

**Comment by Sebbones** [comment] 2024-06-06 18:17
I can confirm the same as @n0099. I still get `ERR_MODULE_NOT_FOUND` using multiple setups with https://github.com/yarnpkg/berry/pull/6278:

- vscode-insider@1.91, dbaeumer.vscode-eslint@3.0.7, eslint@^9.4.0 - ❌
- vscode-insider@1.91, dbaeumer.vscode-eslint@3.0.7, eslint@^8.57.0 - ❌
- vscode-insider@1.91, dbaeumer.vscode-eslint@2.4.4 (`eslint.experimental.useFlatConfig: true`), eslint@^9.4.0 - ❌
- vscode-insider@1.91, dbaeumer.vscode-eslint@2.4.4 (`eslint.experimental.useFlatConfig: true`), eslint@^8.57.0 - ❌

I debugged a little and it is still unable to find `findPnpApi()` in the `resolve` hook for me when executed in the extension. Cli execution works fine.

Maybe i am missing something in my setup?

Happy to provide more info if needed 😊

**Comment by n0099** [comment] 2024-06-06 18:36
> @n0099 did you try with https://github.com/yarnpkg/berry/pull/6278?

Yes.

> * vscode-insider@1.91, dbaeumer.vscode-eslint@2.4.4 (`eslint.experimental.useFlatConfig: true`), eslint@^9.4.0 - ❌

I've also tried using old extension `dbaeumer.vscode-eslint@2.4.4` with `eslint.experimental.useFlatConfig: true`, but not for older `eslint@^8`

> Cli execution works fine.

btw did you did `yarn unplug eslint` before? For me cli can only be used with [`.yarn/unplugged/eslint-npm-*/node_modules/eslint/bin/eslint.js`](https://github.com/n0099/open-tbm/blob/07865ef099fce7f7e951f63bce18e1adc57d3366/fe/package.json#L10)

**Comment by Sebbones** [comment] 2024-06-06 18:53
> btw did you did `yarn unplug eslint` before? For me cli can only be used with [`.yarn/unplugged/eslint-npm-*/node_modules/eslint/bin/eslint.js`](https://github.com/n0099/open-tbm/blob/07865ef099fce7f7e951f63bce18e1adc57d3366/fe/package.json#L10)

No, i works with the 'plugged' version for me.

**Comment by n0099** [comment] 2024-06-06 19:10
I'm using `tsx` to run `eslint`: https://github.com/pzmosquito/eslint-import-resolver-vite/issues/12#issuecomment-1980058683, so it's required.

**Comment by Sebbones** [comment] 2024-06-07 10:13
I can reproduce this without the extension by running
```
node --import ./.yarn/sdks/eslint/lib/api.js ./eslint.config.mjs ❌
```
> `node@22.2.0`, `eslint@9.4.0` and `eslint@8.57.0`



If i run the extension through `yarn node` it can resolve all modules.
```
yarn node ./eslint.config.mjs ✅
```

**Comment by CaseyHofland** [comment] 2024-06-10 07:22
@Sebbones I'm implementing this on Wednesday and I find your findings really helpful. There's a bit of clutter now, could I ask you what steps you'd suggest to correctly install this in a clean project?

**Comment by n0099** [comment] 2024-06-10 07:41
> Instead build the cli from the correct branch [`mael`/eslint-flat-config](https://github.com/yarnpkg/berry/tree/mael/eslint-flat-config?rgh-link-date=2024-06-07T10%3A13%3A27Z) (`yarn build:cli`) yourself and link the new cli in your `.yarnrc.yml` with `yarnPath`. It should work.

> could I ask you what steps you'd suggest to correctly install this in a clean project?

#6278 is already merged 4 days ago, so just running `yarn dlx @yarnpkg/sdks vscode` should be enough by now.

**Comment by IvanHoliak** [comment] 2024-06-10 15:22
Is this not fixed yet? because I still have the same problem( `Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from`
node v22.1.0
yarn v4.2.2
eslint v9.4.0

**Comment by n0099** [comment] 2024-06-10 18:06
> `yarn dlx @yarnpkg/sdks vscode` should be enough by now.

Until a new version of [`@yarnpkg/cli`](https://npmjs.com/package/@yarnpkg/cli) is released, we may only do as in https://github.com/yarnpkg/berry/issues/6219#issuecomment-2154532216:

> Instead build the cli from the correct branch [`mael`/eslint-flat-config](https://github.com/yarnpkg/berry/tree/mael/eslint-flat-config?rgh-link-date=2024-06-07T10%3A13%3A27Z) (`yarn build:cli`) yourself and link the new cli in your `.yarnrc.yml` with `yarnPath`. It should work.

**Comment by arcanis** [comment] 2024-06-10 19:06
I just triggered a release. Using the 4.3.0 the original test case doesn't crash anymore. In case you still face issues, please make sure you use both Yarn 4.3 _and_ the SDK 3.1.3. If you do, open a **new** thread (let's not reuse this one, I'd like to keep investigation separate as something that may look related may be a completely different bug).

For reference, here's a script to easily run the commands from the op; note I updated `packageManager` to 4.3:

```bash
#!/usr/bin/env bash

cd $(mktemp -d)

cat > package.json <<EOF
{
  "name": "yarn-eslint-test",
  "packageManager": "yarn@4.3.0",
  "type": "module",
  "scripts": {
    "eslint": "eslint test.js"
  },
  "devDependencies": {
    "@eslint/js": "^8.57.0",
    "eslint": "^8.57.0"
  }
}
EOF

cat > eslint.config.mjs <<EOF
import js from "@eslint/js";

export default [
	js.configs.recommended,
	{
		files: ["**/*.js"],
		rules: {
			"no-var": "error",
		}
	}
];
EOF

cat > test.js <<EOF
var x = 10;
EOF

yarn install
yarn dlx @yarnpkg/sdks vscode
export NODE_PATH=".yarn/sdks"

node <<EOF
require.resolve('eslint');

const library = require('eslint');
async function main() { const eslint = new (await library.loadESLint({ useFlatConfig: true }))(); const report = await eslint.lintText('var test = "hello";'); console.log(report); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
EOF
```

**Closed by arcanis** 2024-06-10 19:06 UTC
Labels: bug

**Comment by kherock** [comment] 2024-06-26 20:20
@arcanis is this register behavior something that libraries are expected to implement when supporting PnP? Or should a `stylelint` SDK be re-added to help out with the vscode-stylelint library?

**Comment by psychobolt** [comment] 2024-07-09 20:39
In the past I think there was a vscode stylelint SDK. I don't see why not since the ecosystem supports it.

**Comment by Frederick888** [comment] 2024-09-23 06:34
Sorry for posting on a closed thread, but may I know if ESLint flat config can work with Yarn _**v3**_ + VSCode?

We use Node.js v18.20.4 with Yarn v3.8.4 + vscode-eslint 3.0.10, and our VSCode folks are seeing the error below on startup:

```
[Info  - 16:24:58] ESLint server is starting.
[Info  - 16:25:00] ESLint server running in node v18.20.4
[Info  - 16:25:00] ESLint server is running.
[Info  - 16:25:02] ESLint library loaded from: /path/to/project/.yarn/sdks/eslint/lib/api.js
[Error - 16:25:02] Calculating config file for file:///path/to/project/.vscode/settings.json) failed.
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from /path/to/project/eslint.config.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1206:11)
    at nextResolve (node:internal/modules/esm/hooks:864:28)
    at resolve$1 (file:///path/to/project/.pnp.loader.mjs:1962:12)
    at nextResolve (node:internal/modules/esm/hooks:864:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:302:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
```

settings.json:
```json
{
  "search.exclude": {
    "**/.yarn": true,
    "**/.pnp.*": true
  },
  "eslint.nodePath": ".yarn/sdks",
  "prettier.prettierPath": ".yarn/sdks/prettier/index.cjs",
  "typescript.tsdk": ".yarn/sdks/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "eslint.useFlatConfig": true,
  "eslint.runtime": "node"
}
```

Personally I use [LazyVim](https://www.lazyvim.org/)/[mason](https://github.com/williamboman/mason.nvim) + https://github.com/hrsh7th/vscode-langservers-extracted, and it's actually working perfectly for me. Now I'm puzzled about how we can get it working in VSCode too. Can someone give me a hand? Thanks!

**Comment by psychobolt** [comment] 2024-09-23 14:52
@Frederick888 Seems like a workspace issues from the error. First question is do you have '@eslint/js` installed and is that package defined relative to `eslint.config.mjs` ?

**Comment by psychobolt** [comment] 2024-09-23 15:03
@Frederick888 Based on https://github.com/yarnpkg/berry/issues/6219#issuecomment-2159100309 , have you tired Yarn v4.3?

**Comment by Frederick888** [comment] 2024-09-24 01:05
@psychobolt Thanks for the reply! I have created a small reproducer here: https://github.com/Frederick888/playground/tree/eslint-yarn3



> @Frederick888 Based on [#6219 (comment)](https://github.com/yarnpkg/berry/issues/6219#issuecomment-2159100309) , have you tired Yarn v4.3?

Yes, Yarn v4 did not have this issue (reproducer: https://github.com/Frederick888/playground/tree/eslint-yarn4), but due to [insert corporate reasons here lol], I'd like to stay on Yarn v3 if possible. So I'm just wondering if I can tell VSCode to work in the same way as vim.

**Comment by psychobolt** [comment] 2024-09-24 02:43
@Frederick888 Using the v4.3 CLI will get the SDK's register loaded properly for ESLint, but that is missing in `< v4.3 ` . 

Prior, to v4.3 a workaround was [passing the loader option](https://github.com/psychobolt/react-rollup-boilerplate/blob/main/DEVELOPMENT.md#troubleshooting-eslint-extension) to `vscode-eslint`'s runtime

**Comment by Frederick888** [comment] 2024-09-24 03:14
> @Frederick888 Using the v4.3 CLI will get the SDK's register loaded properly for ESLint, but that is missing in `< v4.3 ` .
> 
> Prior, to v4.3 a workaround was [passing the loader option](https://github.com/psychobolt/react-rollup-boilerplate/blob/main/DEVELOPMENT.md#troubleshooting-eslint-extension) to `vscode-eslint`'s runtime

@psychobolt Thanks again for the pointer. I added the loader option

```json
{
  "search.exclude": {
    "**/.yarn": true,
    "**/.pnp.*": true
  },
  "typescript.tsdk": ".yarn/sdks/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "eslint.nodePath": ".yarn/sdks",
  "eslint.useFlatConfig": true,
  "eslint.runtime": "node",
  "eslint.execArgv": [
    "--loader",
    "/path/to/playground/.pnp.loader.mjs"
  ],
  "prettier.prettierPath": ".yarn/sdks/prettier/index.cjs"
}
```

...and now getting a slightly different error

```
[Info  - 13:09:44] ESLint server is starting.
(node:91623) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("/path/to/playground/.pnp.loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
[Info  - 13:09:45] ESLint server running in node v22.7.0
[Info  - 13:09:45] ESLint server is running.
[Info  - 13:09:46] ESLint library loaded from: /path/to/playground/.yarn/sdks/eslint/lib/api.js
[Error - 13:09:46] Calculating config file for file:///path/to/playground/.vscode/settings.json) failed.
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from /path/to/playground/eslint.config.mjs
    at packageResolve (node:internal/modules/esm/resolve:839:9)
    at moduleResolve (node:internal/modules/esm/resolve:908:18)
    at defaultResolve (node:internal/modules/esm/resolve:1038:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolve$1 (file:///path/to/playground/.pnp.loader.mjs:1962:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolve$1 (file:///path/to/playground/.pnp.loader.mjs:1962:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
```

**Comment by psychobolt** [comment] 2024-09-24 03:20
Don't think the error is any different. Did you try an absolute path?

**Comment by Frederick888** [comment] 2024-09-24 04:00
@psychobolt 
> Don't think the error is any different. 

Sorry I was talking about the error stack trace: the one after adding `--loader` had two `.pnp.loader.mjs`.

> Did you try an absolute path?

Yes, I tried absolute path. (Relative path `./.pnp.loader.mjs` led to a `/.pnp.loader.mjs` not found error, something stripped off the leading dot.)

**Comment by psychobolt** [comment] 2024-09-24 14:45
@Frederick888 Ah I forgot about the `file://` . I also think on Windows, non-relative paths don't work.

**Comment by Frederick888** [comment] 2024-09-25 01:22
> @Frederick888 Ah I forgot about the `file://` . I also think on Windows, non-relative paths don't work. But the issue I ran into on my Windows machine was way back before Node v22 and Yarn v4.3

And just noticed that relative paths don't work on macOS either. And in fact I did not confuse myself, cos e.g. using `./.pnp.loader.mjs` under macOS leads to an `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/.pnp.loader.mjs' imported from /`.

**Comment by jbaccarelli-equinix** [comment] 2024-10-23 13:42
Why is this issue closed? it's definitely still happening and I don't see a fix? I'm having issues of peer-dependencies between eslint and the parsers and updating to the latest version seemed to be the fix, but then I have these issues with yarn 3 and imports...

**Comment by xyy94813** [comment] 2024-10-27 09:42
Is there any solution?
Or not use other packages manager?

**Comment by arcanis** [comment] 2024-10-27 11:16
Quoting https://github.com/yarnpkg/berry/issues/6219#issuecomment-2159100309:

> Using the 4.3.0 the original test case doesn't crash anymore. In case you still face issues, please make sure you use both Yarn 4.3 _and_ the SDK 3.1.3. If you do, open a **new** thread [with an updated reproduction].
