### ISSUE TITLE
[Bug?]: Empty packages published to the registry

### ISSUE THREAD

**Issue by EirikVea** [yarnpkg/berry#4451] opened 2022-05-13 12:34 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Creating new project and setting `nodeLinker: node-modules` causes installing of SDK to fail with the following error:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\<username>\AppData\Local\Temp\xfs-499dc81d\dlx-25528\node_modules\@yarnpkg\sdks\lib\cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### To reproduce

```bash
mkdir yarn2-bug && cd yarn2-bug
yarn init -2
```

Then add this line to `.yarnrc.yml`
```yml
nodeLinker: node-modules
```
Then
```bash
yarn install
yarn dlx @yarnpkg/sdks vscode
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\xfs-2238cdfb\node.CMD
    Yarn: 3.2.1 - ~\AppData\Local\Temp\xfs-2238cdfb\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by kbobrowski** [comment] 2022-05-13 12:43
Possibly duplicate of #4452

**Comment by merceyz** [comment] 2022-05-13 12:46
We're fixing it but you don't need the SDK when you're using the `node-modules` linker.

**Closed** 2022-05-13 13:29 UTC
Labels: bug
