### ISSUE TITLE
[Feature] Bring back the extra information added when running yarn scripts in yarn 1

### ISSUE THREAD

**Issue by bdwain** [yarnpkg/berry#2836] opened 2021-05-03 08:05 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**
As a developer, I liked the previews of the package.json scripts that were being executed that yarn 1 showed, and I would like to see them implemented in yarn 2.

**Describe the solution you'd like**

given these scripts in package.json
```
"foo": "echo foo",
"bar": "echo bar",
"foobar": "yarn foo && yarn bar",
```

running `yarn foobar` used to give the following

```
bwain@MyComputer test % yarn foobar
yarn run v1.22.10
$ yarn foo && yarn bar
$ echo foo
foo
$ echo bar
bar
✨  Done in 0.69s.

```

Now it gives no extra output. I found the extra data in yarn 1 helpful

```
bwain@MyComputer test % yarn foobar
foo
bar
```

**Describe the drawbacks of your solution**

I don't know of any.

**Describe alternatives you've considered**

We could just not do it. It's not critical in any way, but it was a nice improvement to the developer experience.

**Comment by arcanis** [comment] 2021-05-03 08:09
Duplicate of https://github.com/yarnpkg/berry/issues/1215#issuecomment-615386306

**Closed by arcanis** 2021-05-03 08:09 UTC
Labels: enhancement
