### ISSUE TITLE
[Bug?]: Yarn needlessly reformats package.json, even on CI

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#6282] opened 2024-05-08 11:37 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Given a package.json formatted differently than to Yarn's liking, Yarn will reformat it, even on CI, even with `--immutable` option passed.

### To reproduce

> **Note**
> https://yarnpkg.com/advanced/sherlock 404s.

> **Note**
> CodeSandbox link on https://v3.yarnpkg.com/advanced/sherlock is also dead.

* `yarn init`
* (make changes to package.json file, e.g. remove a new line)
* `yarn`
* `package.json` changes are reverted

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 22.0.0 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-40ef5ce1/node
    Yarn: 4.2.1 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-40ef5ce1/yarn
    npm: 10.5.1 - /usr/local/bin/npm
    bun: 1.1.6 - ~/.bun/bin/bun
```

### Additional context

It appears like package.json auto-formatting is undocumented and there is no way to turn it off. This causes [hard to debug issues](https://github.com/biomejs/biome/issues/2763) when working with Yarn & other tools, and possibly hurts the performance, too.

**Comment by arcanis** [comment] 2024-05-08 11:53
Duplicate of https://github.com/yarnpkg/berry/issues/6184

**Closed** 2024-05-08 11:53 UTC
Labels: bug

**Comment by wojtekmaj** [comment] 2024-05-08 12:52
Doesn't seem to be related…

```json
{
  "name": "test-yarn",
  "packageManager": "yarn@4.1.1",
  "bin": {
    "test-yarn": "./path/to/file"
  }
}
```
⬇️ 
```json
{
  "name": "test-yarn",
  "packageManager": "yarn@4.1.1",
  "bin": "./path/to/file"
}
```

vs.

```json
{
  "name": "test-yarn",
  "packageManager": "yarn@4.1.1",
  "files": ["./path/to/file", "./another/path"]
}
```
⬇️ 
```json
{
  "name": "test-yarn",
  "packageManager": "yarn@4.1.1",
  "files": [
    "./path/to/file",
    "./another/path"
  ]
}
```

are very different transformation. The former changes the structure, while the latter is formatting only.

**Comment by arcanis** [comment] 2024-05-08 13:54
Depends.

If you want to make this issue specifically about the `--immutable` flag taking the formatting into account, then it's not a bug.

The `--immutable` flag ensures that someone cloning your branch and running an install won't see spurious changes; whether those changes are semantic or syntactic doesn't matter: it'd be confusing either way ("should I commit those changes?").
