### ISSUE TITLE
Berry - .yarnrc.yml - yarnPath + npmScopes

### ISSUE THREAD

**Issue by petr-zatloukal** [yarnpkg/berry#4087] opened 2022-02-08 17:50 UTC
Hi,
I have a problem with using fontawesome private repository

if I use this configuration repository is not found
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
enableGlobalCache: true

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN}
```

But without yarnPath everything works fine

```yml
nodeLinker: node-modules
enableGlobalCache: true

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN}
```

Do you have any idea how to run it together?

**Comment by sgammon** [comment] 2022-08-03 07:14
is it a typo, as `fortawesome`?

**Comment by merceyz** [comment] 2023-06-03 22:26
Removing `yarnPath` makes Yarn use your global version which could be Yarn v1 using a different config file.

Closing as unactionable since there isn't enough information to reproduce the issue.

**Closed by merceyz** 2023-06-03 22:26 UTC
