### ISSUE TITLE
[Case Study] Huge file size in repository

### ISSUE THREAD

**Issue by rizkyramadhan** [yarnpkg/berry#1997] opened 2020-10-18 05:31 UTC
I am currently switching from old yarn to new yarn 2. I know we should check in our dependency to git repo, so we can take full advantage of yarn 2, but man... it is making my repo bigger.

I mean, in old yarn my git repository is usually in < 10mb when pulled, and it just take a few seconds to pull, and then maybe 15-30 secs to `yarn install`. 

But now I have to download 80+mb for that.  Yes, I don't need to `yarn install` it to fetch package dependencies. But I still need to execute it in case I didn't download cross-platform binary that some of my package needed, and that's not much different from my part.

And it is taking me more than a minute just to push initial commit, and then a minute for my colleagues to pull fresh install.  FYI this is a small Create-React-App project.

Yes, I know this is a trade-off, but somehow old yarn is better from caching things up and make initial setup for my project faster. 

Do we have options to *not* check in .yarn in repository ?

**Comment by arcanis** [comment] 2020-10-18 08:35
Duplicate of https://github.com/yarnpkg/berry/issues/180

Just don't check-in your artifacts if you don't want to.

**Closed by arcanis** 2020-10-18 08:35 UTC
Labels: case study

**Comment by rizkyramadhan** [comment] 2020-10-18 09:03
Ok got it, just ignore .yarn/cache folder... Apologize for the rant 🙌

**Comment by merceyz** [comment] 2020-10-18 11:15
I'll just leave this here https://yarnpkg.com/getting-started/qa/#which-files-should-be-gitignored
