### ISSUE TITLE
[Bug] nodeLinker node-modules not deduplicating Parcel v2 dependencies

### ISSUE THREAD

**Issue by lokshunhung** [yarnpkg/berry#2962] opened 2021-06-01 02:19 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

As mentioned in #1049 `parcel` relies on instantiating modules once only:

```js
import {register} from "@parcel/core";
class X {}
register("X", X);
```

When installing `parcel` with `nodeLinker: node-modules` in `yarn v2`, the dependencies of `parcel` are not deduplicated and hoisted such that there are multiple versions of them. A simplified `node_modules` file tree demonstrating `@parcel/fs`, `@parcel/package-manager` not deduplicated is as follows:

```
node_modules
    | - parcel                           (parcel@2.0.0-beta.2)
    | - @parcel
        | - core                         (@parcel/core@2.0.0-beta.2)
        |   | - node_modules
        |       | - @parcel
        |           | - fs               (@parcel/fs@2.0.0-beta.2)
        |           | - package-manager  (@parcel/package-manager@2.0.0-beta.2)
        | - fs                           (@parcel/fs@2.0.0-beta.2)
        | - package-manager              (@parcel/package-manager@2.0.0-beta.2)
```

When installing `parcel` in `yarn v1`, the deduplicating works, and the `@parcel/XXX` deps are hoisted to the highest level.

**To Reproduce**

[Here is a sample repo](https://github.com/lokshunhung/yarn2-parcel-dedupe-repro) containing `parcel v2` that could be bootstrapped when installed with `yarn v1` but not `yarn v2`. More details are available at the repo's readme.

<details>
  <summary>Reproduction</summary>

  ```sh
  $ git clone https://github.com/lokshunhung/yarn2-parcel-dedupe-repro.git
  $ cd yarn2-parcel-dedupe-repro
  $ node ./run-yarn-why.js
  $ cd using-yarn2/packages/parcel-app
  $ yarn start  # throws error
  $ cd ../../../
  $ cd using-yarn1/packages/parcel-app
  $ yarn start  # works
  ```
</details>

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: OSX 11.3.1
 - Node version: 15.12.0
 - Yarn version: 2.4.1

**Additional context**

N/A

**Comment by larixer** [comment] 2021-06-01 05:23
Duplicate of #2500, already fixed in `master`

**Closed by larixer** 2021-06-01 05:23 UTC
Labels: bug
