### ISSUE TITLE
[Bug] Missing resolver

### ISSUE THREAD

**Issue by JesusTheHun** [yarnpkg/berry#2511] opened 2021-02-24 11:49 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

While trying to [install](https://tailwindcss.com/docs/guides/create-react-app#install-tailwind-via-npm) the very popular `tailwindcss`, I run into this error : 

```bash
$ yarn add -D tailwindcss@npm:@tailwindcss/postcss7-compat @tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
➤ YN0001: │ Error: tailwindcss@npm:@tailwindcss/postcss7-compat isn't supported by any available resolver
...
```
**To Reproduce**

The commend above will trigger the error. I tried to run this into Sherlock but it seems broken itself :/

**Environment if relevant (please complete the following information):**

 - OS: OSX 11.2.1
 - Node version: 15.8.0
 - Yarn version: 2.4.0

**Comment by merceyz** [comment] 2021-02-24 12:46
> tailwindcss@npm:@tailwindcss/postcss7-compat

You're lacking a version, try
```sh
yarn add -D "tailwindcss@npm:@tailwindcss/postcss7-compat@*" @tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

Duplicate of https://github.com/yarnpkg/berry/issues/1816

**Closed by merceyz** 2021-02-24 12:46 UTC
Labels: bug

**Comment by JesusTheHun** [comment] 2021-02-24 12:50
Don't you think you should support that format as a compatibility feature ? Since the package manager next door support this syntax

**Comment by merceyz** [comment] 2021-02-24 12:58
> Don't you think you should support that format as a compatibility feature ?

Sure, the issue this is a duplicate of is still open for that reason
