### ISSUE TITLE
[Bug] Typescript 4.3.2 Cannot apply hunk #2

### ISSUE THREAD

**Issue by phuctm97** [yarnpkg/berry#2952] opened 2021-05-29 03:43 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

Can't install TypeScript v4.3.2.

Received this:

```
➤ YN0013: │ typescript@npm:4.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@patch:typescript@npm%3A4.3.2#builtin<compat/typescript>::version=4.3.2&hash=a45b0e can't be found in the cache and will be fetched from the disk
➤ YN0013: │ typescript@npm:4.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.3.2#builtin<compat/typescript>::version=4.3.2&hash=a45b0e: Cannot apply hunk #2 (set enableInlineHunks for details)
```

A clear and concise description of what the bug is. A bug is **unintended**. A feature not being
implemented is **not a bug**, and your issue may be closed for misleading labeling.

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep).
Note that bugs without minimal reproductions **will** be closed as non-actionable.

- Create a new repo
- `yarn init -2`
- `yarn`
- `yarn add -D typescript`

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] macOS Big Sur
 - Node version [e.g. 8.15.0, 10.15.1, ...] 14.17.0
 - Yarn version [e.g. 2.4.0, ...] 2.4.1

**Comment by merceyz** [comment] 2021-05-29 06:49
Duplicate of https://github.com/yarnpkg/berry/issues/2938

**Closed by merceyz** 2021-05-29 06:49 UTC
Labels: bug

**Comment by Paguiar735** [comment] 2023-01-01 22:17
I just encountered this issue when trying to install the latest version of NextJS v12 via [1], and I noticed [2] yielded the same error message as the one described in the [issue](https://github.com/yarnpkg/berry/issues/2952#issue-906330301), which I was able to reproduce by running the three commands the original poster provided.

[1] `yarn create-next-app@12 --ts`
[2] `npx create-next-app@12 --ts`

Once I removed the "--ts" flag, both of them worked without any errors, which further proves there's something wrong with the Typescript installation.

Upon closer inspection, I realized that it both [1] and [2] would default to install packages with Yarn since it's available globally on my machine. Once I uninstalled Yarn via [3] and ran [1], the NextJS installation proceeded via NPM without any errors.

[3] `npm -g uninstall yarn`

According to this (user)[https://github.com/yarnpkg/berry/issues/1221#issuecomment-647376648], Yarn patches TypeScript to add support for PnP, which sometimes goes bad. Since I don't have the expertise to make a pull request, here's my configuration [4] for anyone who's willing to work on that:

[4]
- OS: Fedora Linux 36 (Workstation Edition)
- Node: v18.12.1
- NPM: v8.19.2
- Yarn: v2.4.3
- Other: All the above are in the path and only Yarn is installed globally
