### ISSUE TITLE
[Bug] Unable to run commands with single ampersand

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#1667] opened 2020-08-03 05:19 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

Starting with Yarn 2, I'm unable to run commands with single ampersand in it ([to run two commands asynchronously](https://www.cyberciti.biz/faq/how-to-run-command-or-code-in-parallel-in-bash-shell-under-linux-or-unix/)). For example

```
  "scripts": {
    "start": "yarn db & yarn server"
  },
```

when ran using `yarn start`, will crash with the following error:

```
Syntax Error: Expected "$", "$(", "${", "&&", "'", ";", "<", "<<<", ">", ">>", "\"", "\\", "|", "|&", "||", [ \t], or end of input but "&" found (line 1, column 9).
    at ie (/Users/…/.yarn/releases/yarn-2.1.1.cjs:86:361659)
    at parse (/Users/…/.yarn/releases/yarn-2.1.1.cjs:86:371853)
    at i (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:413729)
    at F (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:443423)
    at i.configuration.reduceHook.script (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:339508)
    at /Users/…/.yarn/releases/yarn-2.1.1.cjs:2:339630
    at async a.mktempPromise (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:408207)
    at async Module.B (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:339248)
    at async Se.execute (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:78449)
    at async Se.validateAndExecute (/Users/…/.yarn/releases/yarn-2.1.1.cjs:2:551219)
```

This command will perfectly run with `yarn start` on Yarn 1, as well as on any version of npm.

**To Reproduce**

`package.json`
```
{
  "name": "async-crash",
  "version": "1.0.0",
  "scripts": {
    "crash": "echo \"1\" & echo \"2\"",
  }
}
```

Command:

```
yarn crash
```

Other commands that will crash:

* `echo test 2>&1`
* `echo test &`

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] macOS, Linux (Amazon S3)
 - Node version [e.g. 8.15.0, 10.15.1, ...] 14.5.0, 12 (Amazon S3)
 - Yarn version [e.g. 2.0.0-rc1, ...] 2.1.1

**Comment by merceyz** [comment] 2020-08-03 06:37
Duplicate of https://github.com/yarnpkg/berry/issues/1349

**Closed by merceyz** 2020-08-03 06:37 UTC
Labels: bug
