### ISSUE TITLE
[Bug?]: YN0001: │ RequestError: Socket connection timeout

### ISSUE THREAD

**Issue by shih-liang** [yarnpkg/berry#5419] opened 2023-05-02 08:20 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

➤ YN0001: │ RequestError: Socket connection timeout
    at ClientRequest.<anonymous> (/corepack/yarn/3.5.0/yarn.js:195:14340)
    at Object.onceWrapper (node:events:626:26)
    at ClientRequest.emit (node:events:523:35)
    at o.emit (.cache/node/corepack/yarn/3.5.0/yarn.js:190:90286)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at new NodeError (node:internal/errors:399:5)
    at internalConnectMultiple (node:net:1098:20)
    at Timeout.internalConnectMultipleTimeout (node:net:1637:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)

### To reproduce

set register server: https://registry.npmmirror.com/

and just type
```
yarn
```

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 20.0.0 - /private/var/folders/yp/fxvdfkln5rvgly46045nm35m0000gn/T/xfs-5c61cbad/node
    Yarn: 3.5.0 - /private/var/folders/yp/fxvdfkln5rvgly46045nm35m0000gn/T/xfs-5c61cbad/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
```

### Additional context

I can access this register server, and yarn runs normally on other machines of Windows in the same subnet. yarn v1 runs normally, too.

**Comment by shih-liang** [comment] 2023-05-02 09:36
Options like disturl is not exists anymore, and I think this is the cause of this error. By the way, the error report of RequestError should include url.

**Comment by steveetm** [comment] 2023-05-06 10:10
I get the same errors, sometimes. few minutes later it runs normally. I have no issues with older yarn. Any chance to add a bit of information about the error?

**Comment by spu95** [comment] 2023-05-07 08:17
Same problem here with macOS and installation via homebrew.

**Comment by steveetm** [comment] 2023-05-07 17:41
Okey, this is a bug in node v20+ (https://github.com/nodejs/node/issues/47822)

As a workaround you can use yarn from source (`yarn set version from sources`) and add this to the very fist line in `.yarn/releases/yarn-sources.cjs`:
```
const net = require('net');
net.setDefaultAutoSelectFamilyAttemptTimeout(20000);
```

**Comment by atcharles** [comment] 2023-05-12 09:26
Yes.
Configure environment variables
`export NODE_OPTIONS="--no-network-family-autoselection"`
It solved my problem

**Comment by mlaposta** [comment] 2023-05-12 21:24
> Yes. Configure environment variables `export NODE_OPTIONS="--no-network-family-autoselection" ` It solved my problem

Just ran into the same issue and this solved it for me as well

**Comment by simonjoom** [comment] 2023-06-09 02:24
thks for that, my connexion is bad, the node_options is the correct workaround

**Comment by shubh402** [comment] 2023-06-09 10:10
fixed with latest version

**Comment by shubh402** [comment] 2023-06-18 15:31
@arcanis please close this issue because it's fixed with latest version of nodejs

**Closed** 2023-06-19 05:16 UTC
Labels: bug

**Comment by flyon** [comment] 2023-08-27 09:24
@shubh402 would be good to know which version you refer to? a patch of stable, or latest? upgrading node is not always easy in every stack, so would be good to know what the minimum version is. Dealing with the same yarn socket connection timeout

**Comment by arcanis** [comment] 2023-08-27 10:35
Socket timeout errors are network errors, not software errors (otherwise they'd happen to everyone, which isn't the case).

Network errors aren't something Yarn can do anything about (since they are caused by your own infrastructure), so I'm going to lock this issue.
