### ISSUE TITLE
升级报错

### ISSUE THREAD

**Issue by git136975643** [yarnpkg/berry#4668] opened 2022-07-26 07:08 UTC
我使用命令 yarn set version from sources  然后报错了：
```
PS E:\study> yarn set version from sources
➤ YN0000: Fetching the latest commits

  $ git fetch origin --depth=1 master --force
  $ git reset --hard FETCH_HEAD
  $ git clean -dfx

➤ YN0000: Building a fresh bundle

Internal Error: resolve@patch:resolve@npm%3A^1.17.0#~builtin<compat/resolve>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at TR.getCandidates (C:\Users\13697\.yarn\releases\yarn-3.2.2.cjs:435:5226)
    at wd.getCandidates (C:\Users\13697\.yarn\releases\yarn-3.2.2.cjs:391:1281)
    at C:\Users\13697\.yarn\releases\yarn-3.2.2.cjs:439:7764
    at Lg (C:\Users\13697\.yarn\releases\yarn-3.2.2.cjs:390:11154)
    at ce (C:\Users\13697\.yarn\releases\yarn-3.2.2.cjs:439:7744)
➤ YN0001: Child yarn reported an error
➤ YN0001:   Exit Code: 1
➤ YN0000: Failed with errors in 3s 741ms
```

**Comment by RDIL** [comment] 2022-10-19 14:08
Does this issue still occur?

**Comment by merceyz** [comment] 2022-10-19 14:12
Duplicate of https://github.com/yarnpkg/berry/issues/2187

**Closed by merceyz** 2022-10-19 14:12 UTC
Labels: can't repro
