### ISSUE TITLE
[Feature]: Update dependencies from git

### ISSUE THREAD

**Issue by richard-ejem** [yarnpkg/berry#3891] opened 2021-12-20 08:43 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

It seems it is not possible to update a package installed from private git repository.

`package.json` entry:

```
"@foo/utils": "git+https://gitlab+deploy-token-...:...@gitlab.com/foo/bar.git#ISSUE-6652-some-git-branch",
```

`yarn up @foo/utils` results in the following error.

Expected: `@foo/utils` is updated to latest commit in branch `ISSUE-6652-some-git-branch`

Actual:
```
➤ YN0027: @foo/utils@git+https://gitlab+deploy-token-...:...@gitlab.com/foo/bar.git#ISSUE-6652-some-git-branch can't be resolved to a satisfying range

Internal Error: The remote server failed to provide the requested resource
```

This is weird since when I remove the entry from `yarn.lock` and run just `yarn`, it does exactly what I needed (see Expected above).

### To reproduce

I'm sorry for not providing Sherlock steps to reproduce as this is related to private repo.

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.3 - /private/var/folders/zb/tvdb_z5s1394t2j6gmry6mkc0000gn/T/xfs-4536a3f2/node
    Yarn: 3.1.0 - /private/var/folders/zb/tvdb_z5s1394t2j6gmry6mkc0000gn/T/xfs-4536a3f2/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  npmPackages:
    jest: 26.4.2 => 26.4.2
```

**Comment by arcanis** [comment] 2021-12-20 09:50
This is a feature request, not a bug.

**Comment by clemsos** [comment] 2021-12-23 14:18
+1 that will be a very useful feature. Maybe this could also be achieved with a syntax like `"@foo/utils": "git+https://<some repo>@latest"` ?

**Comment by paul-soporan** [comment] 2021-12-23 21:29
Duplicate of https://github.com/yarnpkg/berry/issues/1492.

> yarn up @foo/utils results in the following error.

It's only broken if you don't specify a range. If you do, `yarn up '@foo/utils@git+https://gitlab+deploy-token-...:...@gitlab.com/foo/bar.git#ISSUE-6652-some-git-branch'` should update it to the latest commit.

> Maybe this could also be achieved with a syntax like `"@foo/utils": "git+https://<some repo>@latest"` ?

I'm not sure what that syntax would be supposed to do - Yarn never silently updates your dependencies unless you run `yarn up`, so a `package.json` syntax wouldn't make sense since all dependencies get locked after the first time they are resolved.

**Closed by paul-soporan** 2021-12-23 21:29 UTC
Labels: enhancement

**Comment by richard-ejem** [comment] 2021-12-24 09:26
@paul-soporan `yarn up '@foo/utils'` should update the dependency to latest version that satisfies the constraint in `package.json`, in this case to latest commit in given branch, shouldn't it? I think that is pretty intuitive and commonly wanted case.

**Comment by paul-soporan** [comment] 2021-12-26 20:54
@richard-ejem

> yarn up '@foo/utils' should update the dependency to latest version that satisfies the constraint in package.json, in this case to latest commit in given branch, shouldn't it?

Indeed it should and that's what https://github.com/yarnpkg/berry/issues/1492 is about. What I said in my comment is just a workaround that can be used until that issue gets fixed:

> It's only broken if you don't specify a range. If you do, yarn up '@foo/utils@git+https://gitlab+deploy-token-...:...@gitlab.com/foo/bar.git#ISSUE-6652-some-git-branch' should update it to the latest commit.
