### ISSUE TITLE
[Bug?]: Unable to set version 2

### ISSUE THREAD

**Issue by radube** [yarnpkg/berry#3190] opened 2021-07-27 20:57 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I used to be able to set yarn to version 2 in a project using `yarn set version berry` but today I had to rebuild a project and instead of version 2 I got version 3.0.0.
Based on the documentation(https://yarnpkg.com/cli/set/version) I should also be able to set a specific version using something like this `yarn set version 2.4.2` but when I do that I get this error:
```
Resolving 2.4.2 to a url...
error An unexpected error occurred: "Release not found: 2.4.2".
info If you think this is a bug, please open a bug report with the information provided in "/app/nightwatch/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```

Weird thing is that when I tried `yarn set version 2` I didn't get that error but version 3.0.0 was installed. So, I think this is a bug since the documentation says that I would be able to set a specific version but I'm getting an error instead and the workaround is only updating to 3.0.0 which is breaking my project.

Yarn error log:
[yarn-error.log](https://github.com/yarnpkg/berry/files/6888554/yarn-error.log)

### To reproduce

```
cd your_project
yarn set version 2.4.2
```

### Environment

Arguments: 
  /usr/local/bin/node /opt/yarn-v1.22.5/bin/yarn.js set version 2.4.2

PATH: 
  /app/node_modules/.bin:/var/www/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.5

Node version: 
  14.17.3

Platform: 
  linux x64

Trace: 
  Error: Release not found: 2.4.2
      at /opt/yarn-v1.22.5/lib/cli.js:90297:17
      at Generator.next (<anonymous>)
      at step (/opt/yarn-v1.22.5/lib/cli.js:310:30)
      at /opt/yarn-v1.22.5/lib/cli.js:321:13
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

npm manifest: 
  {
    "name": "CHaDKids",
    "version": "1.0.0",
    "description": "Test suite for CHaDKids",
    "devDependencies": {
      "chromedriver": "^91.0.1",
      "nightwatch": "^1.7.7"
    },
    "license": "ISC"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by merceyz** [comment] 2021-07-27 20:58
Duplicate of https://github.com/yarnpkg/berry/issues/3180

**Closed by merceyz** 2021-07-27 20:58 UTC
Labels: bug
