### ISSUE TITLE
[Bug?]: `@yarnpkg/builder` plugin missing outputs

### ISSUE THREAD

**Issue by mskelton** [yarnpkg/berry#3181] opened 2021-07-27 03:20 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The `@yarnpkg/builder` is missing the `lib` folder in the output.  I develop a Yarn plugin which I'm trying to update to Yarn 3 but there seems to be an issue with the 3.0 release of the builder plugin which does not contain a lib folder.

I'm using the node modules linker.

### To reproduce

I'm not sure how to reproduce something with `node_modules` using Sherlock, but installing `@yarnpkg/builder` in a new folder with a fresh manifest will exhibit this behavior.

### Environment

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 14.16.0 - /private/var/folders/cj/22br0t1d2xlcqyncvdm5q3mc0000gn/T/xfs-468aec58/node
    Yarn: 3.0.0 - /private/var/folders/cj/22br0t1d2xlcqyncvdm5q3mc0000gn/T/xfs-468aec58/yarn
    npm: 7.20.0 - /usr/local/bin/npm
  npmPackages:
    jest: ^27.0.6 => 27.0.6

**Comment by paul-soporan** [comment] 2021-07-27 12:28
Duplicate of #3179 (the same release build issue).

@arcanis Can you also deprecate `3.0.0` and move `latest` for `@yarnpkg/builder`?

**Closed by paul-soporan** 2021-07-27 12:28 UTC
Labels: bug
