### ISSUE TITLE
[Bug?]: The vscode pnp integration is completely broken (type info, go to definition, etc)

### ISSUE THREAD

**Issue by danieltroger** [yarnpkg/berry#3745] opened 2021-11-18 19:33 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

It is impossible to get yarn pnp to work with the latest vscode and typescript.
Zipfs works but imports aren't typed and go to definition doesn't work.

### To reproduce

[follow the editor guide](https://next.yarnpkg.com/getting-started/editor-sdks) on a freshly setup user and you'll see it doesn't work.

Here is a video of me following every step and showing that it doesn't work. Please watch it thoroughly and tell me what I'm doing wrong or fix so that it works:

https://youtu.be/UPdtk7Mi6Ew (it's probably still processing if it's blurry)

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 17.0.1 - /private/var/folders/q_/xzl9z_1x2g17_4gvys67mfqw0000gn/T/xfs-c8f67124/node
    Yarn: 3.1.0 - /private/var/folders/q_/xzl9z_1x2g17_4gvys67mfqw0000gn/T/xfs-c8f67124/yarn
    npm: 8.1.0 - /usr/local/bin/npm
```

**Comment by paul-soporan** [comment] 2021-11-18 19:38
Duplicate of https://github.com/yarnpkg/berry/issues/3722. The TS PnP patch hasn't been updated to cover TS 4.5 yet, that's why it can't resolve imports.

**Closed by paul-soporan** 2021-11-18 19:38 UTC
Labels: bug

**Comment by danieltroger** [comment] 2021-11-18 19:50
@paul-soporan Ok. It would be great if you could inform users about it in the guide. I made it easy for you, just click "merge" on https://github.com/yarnpkg/berry/pull/3746.
