### ISSUE TITLE
npm_package_ environments variables not set when running scripts

### ISSUE THREAD

**Issue by yinzara** [yarnpkg/berry#1991] opened 2020-10-17 01:33 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

See:
https://docs.npmjs.com/misc/scripts#packagejson-vars
https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js

When a "script" is run, there are a set of environment variables that are supposed to be set by the package manager about the package being run.

Yarn 1 does this correctly as shown in the above js file.

Yarn 2 does not do this at all.

**To Reproduce**

Create a new directory with `package.json` with the following contents and run `yarn set version berry` then`yarn`:
```json
{
  "name": "npm_package_test",
  "version": "0.0.0",
  "main": "index.js",
  "license": "MIT",
  "config": {
  	"port": 8080
  },
  "scripts": {
    "test:name": "node -e 'console.log(process.env.npm_package_name)'",
    "test:version": "node -e 'console.log(process.env.npm_package_version)'",
    "test:config": "node -e 'console.log(process.env.npm_package_config_port)'"
  }
}
```

Run: `yarn test:name`
Expected: prints `npm_package_test`
Actual: prints `undefined`

Run: `yarn test:version`
Expected: prints `0.0.0`
Actual: prints `undefined`

Run: `yarn test:config`
Expected: prints `8080`
Actual: prints `undefined`

Running the same test with `npm run --silent test:name`, `npm run --silent test:version`, and `npm run --silent test:config` all match the expected values as does the same on Yarn 1.0

**Comment by paul-soporan** [comment] 2020-10-17 08:12
Duplicate of #1659

**Closed by paul-soporan** 2020-10-17 08:12 UTC
Labels: bug
