### ISSUE TITLE
[Bug] Scaffold-eth reading parent .pnp.js for pnpApi when enableGlobalCache is false

### ISSUE THREAD

**Issue by iafhurtado** [yarnpkg/berry#2785] opened 2021-04-21 19:44 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have been trying to start a yarn command on a project called scaffold-eth (https://github.com/austintgriffith/scaffold-eth) to set up a local Ethereum environment to play around with smart contracts, but after trying start the yarn it throws off an error very similar to another bug already closed in thise project https://github.com/yarnpkg/berry/issues/2470

**To Reproduce**

Clo

1. Clone scaffold-eth repo
2. yarn install
3. yarn start
4. error
```
C:\Users\jaibo\scaffold-eth>yarn start
Internal Error: Unable to locate pnpapi, the module 'C:\Users\jaibo\scaffold-eth\.pnp.js' is controlled by multiple pnpapi instances.
This is usually caused by using the global cache (enableGlobalCache: true)

Controlled by:
  C:\Users\jaibo\scaffold-eth\.pnp.js
  C:\Users\jaibo\.pnp.js
This is usually caused by using the global cache (enableGlobalCache: true)

Controlled by:
  C:\Users\jaibo\scaffold-eth\.pnp.js
  C:\Users\jaibo\.pnp.js
    at Object.findApiPathFor (C:\Users\jaibo\scaffold-eth\.pnp.js:39920:13)
    at Function.external_module_.Module._resolveFilename (C:\Users\jaibo\scaffold-eth\.pnp.js:38892:182)
    at Function.external_module_.Module._load (C:\Users\jaibo\scaffold-eth\.pnp.js:38781:48)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at S (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:419420)
    at Module.k (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:419525)
    at S.findPackageLocation (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:266361)
    at C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:426140
    at Function.openPromise (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:490328)

```

![image](https://user-images.githubusercontent.com/65864145/115611597-8efe2780-a2ea-11eb-9156-a6d300da42f9.png)

**Environment if relevant (please complete the following information):**

 - Windows 10

Any tips to set up the right path?

**Comment by merceyz** [comment] 2021-04-21 20:05
Duplicate of https://github.com/yarnpkg/berry/issues/2470

Looks like you've run an install in your home directory, you should avoid that otherwise everything under `C:\Users\jaibo` belongs to that pnpapi

**Closed by merceyz** 2021-04-21 20:05 UTC
Labels: bug
