### ISSUE TITLE
[Bug?]: Expected the root to be registered when build docusaurus

### ISSUE THREAD

**Issue by tisonkun** [yarnpkg/berry#4756] opened 2022-08-16 08:04 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0001: │ Error: Assertion failed: Expected the root to be registered
    at lUe (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:448:4565)
    at Ke.resolveEverything (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:441:8306)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:444:2138
    at async Fe.startTimerPromise (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:412:3730)
    at async Ke.install (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:444:2077)
    at async /Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:573:1994
    at async Fe.start (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:412:2287)
    at async uf.executeUpRecursive (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:573:1924)
    at async uf.execute (/Users/chenzili/.node/corepack/yarn/3.1.0/yarn.js:573:1165)
➤ YN0000: └ Completed in 53s 333ms
➤ YN0000: Failed with errors in 53s 336ms

### To reproduce

1. Checkout https://github.com/korandoru/open-source-town/tree/yarn3
2. Run `yarn install`

### Environment

```shell
OS macOS 12.5
CPU M1

Node: v18.7.0
Yarn: 3.1.0
npm: 8.15.0
```

**Comment by tisonkun** [comment] 2022-08-16 11:43
Emmm...Perhaps I should report this in Discussions. But I don't have the privilege to transfer this issue now.

**Comment by merceyz** [comment] 2022-08-16 12:31
Duplicate of https://github.com/yarnpkg/berry/issues/4625

**Closed by merceyz** 2022-08-16 12:31 UTC
Labels: bug
