### ISSUE TITLE
[Bug?]: Yarn Berry fails to `yarn install` when `optionalDependencies` do not exist in the source repository or when `yarn add` non-existing packages even if `--optional` is set

### ISSUE THREAD

**Issue by kristian** [yarnpkg/berry#4306] opened 2022-03-31 16:29 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

This issue is similar to a long-open issue / PR in Yarn 1, see https://github.com/yarnpkg/yarn/pull/6510.

Generally the problem has not been solved with upgrading to Yarn 2+ / Berry. When trying to install a `package.json` that contains an `optionalDependency` that is not available in the source repository, the `yarn install` will fail:

```
PS <path>> yarn install
➤ YN0000: ┌ Resolution step
➤ YN0035: │ <package>@npm:^<version>: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: <URL>
➤ YN0000: └ Completed in 0s 366ms
➤ YN0000: Failed with errors in 0s 371ms
```

Same is true (I guess for the same reason, because the log output looks very similar), if you try to do a `yarn add --optional ...` for a package that does not exist in the source repository. My expectation would be that any non-existent package in the source should *not* fail the `yarn install` and not fail to `yarn add` if the `--optional` flag is set, as the NPM documentation [1] explicitly suggests:

> If a dependency can be used, but you would like npm to proceed **if it cannot be found** or fails to install, then you may put it in the optionalDependencies object.

If you agree and this can be considered a bug and behavior of the resolution in case of optional dependencies should be changed, I would try to suggest a PR for this. I think allowing to add optional packages to `package.json` and not failing `yarn install` would be a better approach, what do you think?

[1] https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies

### To reproduce

I do expect `yarn install` not to fail if a optional dependency does not exist:

```js repro
await packageJson({
  optionalDependencies: {
    [`any_non_existing_package`]: `x`
  }
});

await expect(yarn(`install`)).resolves.not.toThrow(`Command failed`);
```

Similarly I do expect `yarn add --optional ...` to not fail for the same reason and `package.json` to be updated accordingly:

```js repro
const {promises: {readFile}} = require(`fs`);

await packageJsonAndInstall({});

await expect(yarn(`add`, `--optional`, `any_non_existing_package`)).resolves.not.toThrow(`Command failed`);

const pkgJson = JSON.parse(await readFile(`package.json`, `utf8`));
expect(pkgJson.optionalDependencies).toHaveProperty(`any_non_existing_package`);
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz      
  Binaries:
    Node: 14.18.3 - ~\AppData\Local\Temp\xfs-ad6eca41\node.CMD  
    Yarn: 3.2.0.dev - ~\AppData\Local\Temp\xfs-ad6eca41\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

One potential use case for this is having multiple scoped repositories, like we do. In some repositories some artifacts do not exist, thus we want to put them as `optionalDependencies` without failing the install / add.

**Comment by arcanis** [comment] 2022-03-31 16:50
This behaviour is intended. Optional dependencies must be resolvable, even if they aren't compatible with the system. If they can't be resolved they can't be in the lockfile, and if they can't be in the lockfile they can't be locked, which isn't something Yarn allows.

**Comment by kristian** [comment] 2022-03-31 17:51
Like, also from a end-user perspective I would like to understand if you‘d be willing to reconsider if this *could* be treated as a bug or not? Here is my current line of reasoning:

As a user I essentially don‘t care „why“ a optional package is not installed… optional means „optional“ to me, meaning: „I don‘t care if the package is available after installation, or not“. This for sure also includes packages that are „not present“, because for me this is one of the things I want to express, when I say it is „optional“.

So I as a user clearly think this is a bug, because also how it‘s documented currently. 

Do you currently consider this as „not a bug“ and „intended behavior“ because it doesn‘t fit into the current software design / architecture of Yarn and/or the lock file format (which for sure, I am sure, you want to keep as stable as possible), or do you consider it „intended“ for any other purpose / corner case that I maybe don‘t understand at the moment? E.g. adding a „null-hash for packages that are optional and do not exist“ to the lock file, could cause intended scenario <insert scenario here> to break, if fhe behaviour is changed to what is more closely expected from end-users point of view?

Looking forward hearing your thoughts on this!

**Comment by kristian** [comment] 2022-04-02 18:14
I provided a plugin that hooks into the `wrapNetworkRequest` hook. I had to take some shortcuts, because often times in the hooks I e.g. did not have access to the `project` or `workspace`... However it does indeed work. As I did not want to modify the lockfile format, I did "fake" only the package metadata and made Yarn think that the package (if 404ed) indeed does exist. I also provided a `beforeWorkspacePacking` hook, that again removed the (non-existent) optional packages, so the package can be released without any issues. If I would have had the chance to hook into the resolution logic itself, I am sure I could have solved it nicer than this. But this does the trick for now I hope! 👍 Anyways, I don't think this issue is resolved yet, for this reason I will leave it open for now.

**Comment by merceyz** [comment] 2022-04-02 23:16
Duplicate of https://github.com/yarnpkg/berry/issues/2425

**Closed by merceyz** 2022-04-02 23:16 UTC
Labels: bug, reproducible, not a bug, waiting for feedback

**Comment by kristian** [comment] 2022-04-02 23:37
I am sorry @merceyz, I find it „strange“ to just close this issue without any answer to the discussion points I raised? I clearly put effort into this, so just closing it feels a little „rude“ to me, I am sorry.

In my humble oppinion just closing this won‘t do the issue raised justice either. I don‘t think many of the arguments in #2425 and here provide a reasonable answer some of the key points that I raised in my recent comments. I understand many of the things @arcanis commented, however, none of the additional things that I broght up have been adressed.

One of the main points Maël expressed here and in #2425 is that Yarn does not allow not found dependencies because they cannot be locked. I cannot fully follow the reasoning here. A non-found dependency could simply be assigned a null-hash and locked anyways. As soon as a package is found, the lockfile is updated / changed, thus tinkering, as described by Maël in #2425 would not be possible. If installing from a lockfile, Yarn would have to simply respect the lockfiles decision *not* to download a package with a null-hash.

In the plugin I created, this is achieved by serving Yarn a „dummy package“, which works just fine. I think you could easily implement that in the resolution itself very consistently. Also as already raised above, why just buntly ignore the fact that this is the way `optionalDependencies` *should* be handled, according to the NPM spec.? I understand that „Yarn is different“, however just ignoring a feature that could easily just be considered a „warning“? I mean if the build of an optional package fails, you also manage to print a warning via the Yarn report… so why not doing the same thing, for optional packages that cannot be found?
