### ISSUE TITLE
[Bug?]: Typescript 4.5.2 cant find type declarations

### ISSUE THREAD

**Issue by kputnins** [yarnpkg/berry#3802] opened 2021-11-26 08:32 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a project using
- React
- Typescript
- yarn2 `3.1.0` with `nodeLinker: pnp`

Updating TypeScript 4.4.4 => 4.5.2 broke TS typing - TS can't resolve type declarations from packages
![image](https://user-images.githubusercontent.com/36342248/143549538-0301d1f6-e09d-4496-ae9c-9868cd99e746.png)

Even though they are there and were working on TS 4.4.4
![image](https://user-images.githubusercontent.com/36342248/143549652-a0c506fd-71aa-4898-b770-5e90de50d2a8.png)

I double checked that with `nodeLinker: node-modules` TS has no problems and finds the typings in the `node_modules` folder, so this feels like somethings wrong with yarns `pnp` linker

### To reproduce

Repo with minimal React app setup and all required dependencies
https://github.com/kputnins/ts-yarn-bug

You can run `yarn tsc` to run the projects TS with `--noEmit` to see the problems
![image](https://user-images.githubusercontent.com/36342248/143550669-616ceafe-2fec-477b-880f-0b730afefc58.png)

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 16.9.1 - ~\AppData\Local\Temp\xfs-bff7c140\node.CMD
    Yarn: 3.1.0 - ~\AppData\Local\Temp\xfs-bff7c140\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by merceyz** [comment] 2021-11-26 10:11
Duplicate of https://github.com/yarnpkg/berry/issues/3722

**Closed by merceyz** 2021-11-26 10:11 UTC
Labels: bug
