### ISSUE TITLE
[Bug] `yarn up "@scope/*"` errors for github ssh dependencies

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/berry#2925] opened 2021-05-24 12:22 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

In a project with github ssh dependencies, the `yarn up "@scope/*"` command errors wen trying to resolve the github deps

```
➤ YN0027: @org/proj1@git+ssh://git@github.com/org/proj1#lint-deps can't be resolved to a satisfying range

HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/Users/me/Projects/proj/.yarn/releases/yarn-berry.cjs:23:10082)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

➤ YN0027: @org/proj2@git+ssh://git@github.com/org/proj2#semver:^2.1.0 can't be resolved to a satisfying range

HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/Users/me/Projects/proj/.yarn/releases/yarn-berry.cjs:23:10082)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**To Reproduce**

<details>
  <summary>Reproduction</summary>

package.json:
```json
{
  "name": "yarn2test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@me/micromatch": "git+ssh://git@github.com/rally25rs/micromatch.git#semver:^4.0.0"
  }
}
```

yarn install output:
```
$ yarn
➤ YN0000: ┌ Resolution step
➤ YN0013: │ @me/micromatch@git+ssh://git@github.com/rally25rs/micromatch.git#commit=bdd32f41e07f401b12ae7c8b04d22b275c88c84b can't be found in the cache and will be fetched from the rem
➤ YN0000: └ Completed in 2s 303ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @me/micromatch@git+ssh://git@github.com/rally25rs/micromatch.git#commit=bdd32f41e07f401b12ae7c8b04d22b275c88c84b can't be found in the cache and will be fetched from the rem
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 2s 341ms
```

yarn up output:
```
$ yarn up
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 79ms
```

yarn up with a scope output:
```
$ yarn up "@me/*"
➤ YN0027: @me/micromatch@git+ssh://git@github.com/rally25rs/micromatch.git#semver:^4.0.0 can't be resolved to a satisfying range

HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/Users/jvalore/Projects/yarn2/.yarn/releases/yarn-berry.cjs:23:10082)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

➤ Errors happened when preparing the environment required to run this command.
```
</details>

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v12.18.3
 - Yarn version v2.4.1

**Comment by merceyz** [comment] 2021-05-24 13:41
Closing as a duplicate of https://github.com/yarnpkg/berry/issues/2926 even though it was opened after this one, they're both the same issue except that `@me/micromatch` doesn't exist so it's a 404

**Closed by merceyz** 2021-05-24 13:41 UTC
Labels: bug
