### ISSUE TITLE
Yarn berry does not seem able to pick up custom env variables (used to define alternative sites for some binary packages)

### ISSUE THREAD

**Issue by chadi-kazan** [yarnpkg/berry#4891] opened 2022-09-23 14:12 UTC
### Discussed in https://github.com/yarnpkg/berry/discussions/4819

<div type='discussions-op-text'>

<sup>Originally posted by **chadi-kazan** September  5, 2022</sup>
I am migrating from npm to yarn berry. my company blocks installation of some packages with native bindings like node-sass and canvas, so what we do is download them and host them on an internal mirror and set variables in .npmrc 

something like this
```json
sass_binary_site=http://internalurl.company.com/repos/node-sass/raw/releases/download
puppeteer_skip_chromium_download=true
canvas_binary_host_mirror=http://internalurl.company.com/repos/mirrors/raw/node-canvas/releases/download
```
I obviously can no longer set those in .yarnrc.yml and it doesn't pick them up if i define them as env variables ( or maybe i am doing that wrong?)
can anyone help please?
thanks</div>

I tested this with yarn 1.x, it works. it is able to acknowledge such variables and work with them. not berry though.
I expect it to be backwards compatible and at least pick up env variables when I define them, but this does not seem to be the case. 
Our corporate proxy/firewall blocks us from accessing these resources, setting up mirrors locally within the intranet was a good away around this.
Has support for this custom environment variables dropped?

**Comment by arcanis** [comment] 2022-09-23 14:47
Duplicate of #4819

**Closed by arcanis** 2022-09-23 14:47 UTC
