### ISSUE TITLE
[Bug?]: `yarn workspaces foreach run` doesn't ignore scripts that contain colons

### ISSUE THREAD

**Issue by ldiqual** [yarnpkg/berry#3292] opened 2021-08-14 05:12 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

With the following workspaces:
 - `packages/a` contains `foo:bar` and `foo` scripts
 - `packages/b` has no script

Running `yarn workspaces foreach --verbose run foo:bar` via a root script fails (it does not ignore `b`):

```
[ldiqual@ldiqual-mbp-siteline yarn-foreach]$ yarn foo:bar
➤ YN0000: [a-1a2bd2]: Process started
➤ YN0000: [a-1a2bd2]: foo:bar
➤ YN0000: [a-1a2bd2]: Process exited (exit code 0), completed in 0s 45ms

➤ YN0000: [b-c0f23f]: Process started
➤ YN0000: [b-c0f23f]: Usage Error: Couldn't find a script named "foo:bar".
➤ YN0000: [b-c0f23f]:
➤ YN0000: [b-c0f23f]: $ yarn run [--inspect] [--inspect-brk] <scriptName> ...
➤ YN0000: [b-c0f23f]: Process exited (exit code 1), completed in 0s 14ms
➤ YN0000: Done in 0s 66ms
```

While running `yarn workspaces foreach --verbose run foo` via a root script properly ignores the `b` workspace:

```
[ldiqual@ldiqual-mbp-siteline yarn-foreach]$ yarn foo
➤ YN0000: [a-1a2bd2]: Process started
➤ YN0000: [a-1a2bd2]: foo
➤ YN0000: [a-1a2bd2]: Process exited (exit code 0), completed in 0s 43ms
➤ YN0000: Done in 0s 47ms
```

### To reproduce

Run `yarn foo:bar` and `yarn foo` in this project:

[yarn-foreach.zip](https://github.com/yarnpkg/berry/files/6985925/yarn-foreach.zip)

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  Binaries:
    Node: 14.17.5 - /private/var/folders/hr/v4vtphl130zczzkbpdkbs7qm0000gn/T/xfs-9e2b9f09/node
    Yarn: 3.0.0 - /private/var/folders/hr/v4vtphl130zczzkbpdkbs7qm0000gn/T/xfs-9e2b9f09/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm

**Comment by merceyz** [comment] 2021-08-14 08:13
Duplicate of https://github.com/yarnpkg/berry/issues/3048

**Closed by merceyz** 2021-08-14 08:13 UTC
Labels: bug
