### ISSUE TITLE
[Bug?]: Yarn 3 unable to add nuxt-bridge package

### ISSUE THREAD

**Issue by funkel1989** [yarnpkg/berry#5098] opened 2022-11-25 22:56 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Run the following command:

yarn add --dev @nuxt/bridge@npm:@nuxt/bridge-edge

get the following error:
```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @nuxt/bridge@npm:@nuxt/bridge-edge isn't supported by any available resolver                                                                                              
    at Wf.getResolverByDescriptor (D:\code\git\battleline\Integra-v2\.yarn\releases\yarn-3.3.0.cjs:391:1647)
    at Wf.bindDescriptor (D:\code\git\battleline\Integra-v2\.yarn\releases\yarn-3.3.0.cjs:391:1036)
    at Z (D:\code\git\battleline\Integra-v2\.yarn\releases\yarn-3.3.0.cjs:439:6905)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 15ms
```

this works with yarn 1 and npm and pnpm. Is there a way to make this work with yarn 2/3

### To reproduce

simply run yarn add --dev @nuxt/bridge@npm:@nuxt/bridge-edge

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 16.15.1 - ~\AppData\Local\Temp\xfs-ebb878b3\node.CMD
    Yarn: 3.3.0 - ~\AppData\Local\Temp\xfs-ebb878b3\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by arcanis** [comment] 2022-11-25 23:17
Duplicate of https://github.com/yarnpkg/berry/issues/5094

**Closed by arcanis** 2022-11-25 23:17 UTC
Labels: bug
