### ISSUE TITLE
yearning for 'naive' steps that start a fresh new app using 'modern yarn'

### ISSUE THREAD

**Issue by kay-o** [yarnpkg/berry#4523] opened 2022-06-05 02:12 UTC
### Discussed in https://github.com/yarnpkg/berry/discussions/4522

<div type='discussions-op-text'>

<sup>Originally posted by **kay-o** June  4, 2022</sup>
Can I use CLI tools like create-react-app to start a new project with **modern yarn**, no migration?

If I follow Yarn 'getting started' instructions and want to create a new react app, as best I can understand I have to go through installing in Yarn 1, then migrating. Is that my best option or is there a more direct alternative?

The more important question: if I want the headline benefits of Yarn 2 like Zero-installs and Plug-n-Play, what are the minimal reliable steps for getting there? Ideally instructions serve just as a minimalist reminder of step 1, step 2, step 3, ... step n.

A while back I "read the manual" thoroughly, cheering as I did, and I successfully started "modern yarn" projects soon after said thorough reading. Now when I return to the Getting Started docs, hoping not to do another thorough reading, I simply can't make headway. (The docs contain boatloads of info, and the actual steps are challenging to extract, even if you've extracted them in the past).</div>

**Comment by merceyz** [comment] 2022-07-15 17:49
No need to create both a issue and a discussion, people will respond when they have time.
Closing as a duplicate of https://github.com/yarnpkg/berry/discussions/4522

**Closed by merceyz** 2022-07-15 17:49 UTC
