### ISSUE TITLE
[Feature] Support WebStorm/IntelliJ editor SDK

### ISSUE THREAD

**Issue by leyanlo** [yarnpkg/berry#2610] opened 2021-03-18 19:51 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Add support for WebStorm/IntelliJ SDK in
https://yarnpkg.com/getting-started/editor-sdks

After installing the VSCode SDK, I see WebStorm complain:
```
Initialization error (ESLint). Cannot find module '<my-repo>/.yarn/sdks/eslint/lib/options'
```

Seems like WebStorm expects a options.js file to live in `.yarn/sdks/eslint/lib/`. Workaround at the moment is to comment out this expectation from `/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js`, e.g. replace
```js
function ESLintPlugin(state) {
  ...
  this.options = requireInContext(eslintPackagePath + "lib/options", state.packageJsonPath);
  ...
}

ESLintPlugin.prototype.invokeESLint = function (requestArguments, additionalOptions) {
  ...
  var parsedCommandLineOptions = translateOptions(this.options.parse(requestArguments.extraOptions || ""));
  ...
};
```

with

```js
function ESLintPlugin(state) {
  ...
  this.options = {};
  ...
}

ESLintPlugin.prototype.invokeESLint = function (requestArguments, additionalOptions) {
  ...
  var parsedCommandLineOptions = {};
  ...
};
```

**Comment by merceyz** [comment] 2021-03-18 19:55
cc @segrey

**Comment by wdfinch** [comment] 2021-03-18 21:30
plus 1

**Comment by ylemkimon** [comment] 2021-05-22 09:59
This seems to be fixed in the latest WebStorm. Could you check it's still an issue?

**Comment by leyanlo** [comment] 2021-05-27 23:35
Verified that this is still an issue on 2021.1 and 2021.2 EAP. Without the workaround from my comment above, I see errors:
```
Initialization error (ESLint). Qualified path resolution failed - none of those files can be found on the disk.

Source path: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options.js
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options.json
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options.node

Require stack:
- /Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js
- /Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin-provider.js
- /Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js
Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options.js
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options.json
Not found: /Users/leyan/src/web-code/.yarn/sdks/eslint/lib/options.node

Require stack:
- /Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js
- /Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin-provider.js
- /Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js
    at Function.external_module_.Module._resolveFilename (/Users/leyan/src/web-code/.pnp.cjs:245214:55)
    at Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.external_module_.Module._load (/Users/leyan/src/web-code/.pnp.cjs:245028:36)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireInContext (/Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:187:12)
    at new ESLintPlugin (/Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:48:24)
    at ESLintPluginFactory.create (/Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin-provider.js:9:34)
    at Interface.<anonymous> (/Applications/WebStorm 2021.2 EAP.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js:82:52)
    at Interface.emit (events.js:314:20)
Process finished with exit code -1
```

**Comment by ylemkimon** [comment] 2021-05-28 02:25
There seem to be similar issues tracked in the WebStorm bug tracker: [WEB-43384](https://youtrack.jetbrains.com/issue/WEB-43384) and [WEB-47366](https://youtrack.jetbrains.com/issue/WEB-47366). Could you [check the package manager is set to Yarn](https://youtrack.jetbrains.com/issue/WEB-47366#focus=Comments-27-4744537.0-0) in `Languages & Frameworks > Node.js and NPM`?

**Comment by leyanlo** [comment] 2021-05-28 16:01
![image](https://user-images.githubusercontent.com/1285326/119922088-f4fe5000-bf23-11eb-849e-1baf0c2e6287.png)
Yes, package manager is set to Yarn.

**Comment by titanium-cranium** [comment] 2021-07-01 14:17
Have exactly the same issue.  @leyanlo workaround solved my problem and I also have yarn set as package manager.

**Comment by titanium-cranium** [comment] 2021-07-14 01:33
@ylemkimon Any progress with this issue?

**Comment by segrey** [comment] 2021-07-14 07:23
Guys, sorry for the delay. Unfortunately, I couldn't reproduce the issue in WebStorm 2021.1.3. ESLint reports errors in the editor:
![image](https://user-images.githubusercontent.com/607109/125579831-d3ea7c40-6965-4807-8d0c-897b820321db.png)

![image](https://user-images.githubusercontent.com/607109/125579920-2d4f3a78-39df-44bc-ae60-7bc7c1e5b377.png)

Please double check:
* Install the latest yarn build from master: `yarn set version from sources`
* Install dependencies in project: `yarn install`
* Restart IDE

If it doesn't help, please provide a small example project reproducing the issue and I'll investigate further. Thanks.

**Comment by RDIL** [comment] 2022-10-01 02:05
WebStorm and IntelliJ-based IDEs have PnP support built-in, and have for a while.  Feel free to open a new issue if this is still the case.

**Closed by RDIL** 2022-10-01 02:05 UTC
Labels: enhancement
