### ISSUE TITLE
[Bug] `yarn up packageName` replaces github dependencies with real npm registry

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/berry#2926] opened 2021-05-24 12:28 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

In a project with a github ssh dependency, running `yarn up depName` will remove the github dep and put in a normal semver version.

The expected behavior (and what yarn v1 does) would be that if you have a github dependency
```
"micromatch": "git+ssh://git@github.com/rally25rs/micromatch.git#semver:^4.0.0"
```
then `yarn up micromatch` should check the `rally25rs/micromatch` github repo to find the latest commit-ish that matches `^4.0.0` semver range, and update to it. package.json should probably remain unchanged.

Actual behavior is that the github dep is removed and replaces with real npm registry latest version, and `package.json` is changed to
```
"micromatch": "^4.0.4"
```

**To Reproduce**

<details>
  <summary>Reproduction</summary>

start with a package.json
```json
{
  "name": "yarn2test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "micromatch": "git+ssh://git@github.com/rally25rs/micromatch.git#semver:^4.0.0"
  }
}
```

then run `yarn up micromatch`
  ```
$ grep micro package.json
    "micromatch": "git+ssh://git@github.com/rally25rs/micromatch.git#semver:^4.0.0"

$ yarn up micromatch
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ micromatch@npm:4.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0019: │ micromatch-git+ssh-c9604e0ed5-6549da53ff.zip appears to be unused - removing
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 156ms

$ grep micro package.json
    "micromatch": "^4.0.4"
  ```
</details>

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v12.18.3
 - Yarn version v2.4.1

**Comment by rally25rs** [comment] 2021-05-24 12:41
funny bit of yarn history; the very first issue I ever filed against yarn v1, which led me to start contributing to yarn, was this same bug 😆 

https://github.com/yarnpkg/yarn/issues/2501

**Comment by merceyz** [comment] 2021-05-24 13:47
Duplicate of https://github.com/yarnpkg/berry/issues/1492

**Closed by merceyz** 2021-05-24 13:47 UTC
Labels: bug
