### ISSUE TITLE
[Feature] VSCode integration

### ISSUE THREAD

**Issue by jacklaurencegaray** [yarnpkg/berry#950] opened 2020-02-14 05:07 UTC
**Describe the user story**

As a user, I'd like to be able to view the source code [definitions] of a dependency via VSCode to check out some parts of the dependency. This can be achieved normally with just yarn v1, as the vscode jumps to the source file upon holding CMD and then clicking the line. Because of the nature of yarn PnP, that is -- dependencies are in the form of zip files, this is no longer possible.

As a user, I'd also like to be able to allow my IDE to predict/autocomplete some of the lines. This was once possible with yarn v1.

**Comment by arcanis** [comment] 2020-02-14 19:42
Duplicate of #806

**Closed by arcanis** 2020-02-14 19:42 UTC
Labels: enhancement
