### ISSUE TITLE
[Bug?]: Installed module not found (monorepo)

### ISSUE THREAD

**Issue by The-Code-Monkey** [yarnpkg/berry#5694] opened 2023-08-25 08:12 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Updating to yarn 3 or even yarn canary to use zero installs. On monorepo

yarn install runs fine.

but when i run yarn build it says

```
@techstack/tcm-cli: src/createBuildConfigs.ts(1,19): error TS2307: Cannot find module 'chalk' or its corresponding type declarations.
@techstack/tcm-cli: src/errors/extractErrors.ts(8,38): error TS2307: Cannot find module '@babel/parser' or its corresponding type declarations.
@techstack/tcm-cli: src/index.ts(7,19): error TS2307: Cannot find module 'chalk' or its corresponding type declarations.
@techstack/tcm-cli: src/logError.ts(1,19): error TS2307: Cannot find module 'chalk' or its corresponding type declarations.
@techstack/tcm-cli: src/messages.ts(1,19): error TS2307: Cannot find module 'chalk' or its corresponding type declarations.
```

The thing is though is that, not only is chalk in the yarn.lock file, it is also in the .yarn/cache. which means its installed. Yes no installed directly by myself, but if a package I am using uses a package I should be able to use it without installing yet another version of the same package.

### To reproduce

https://github.com/The-Code-Monkey/TechStack

```bash
yarn && yarn build
```

### Environment

```shell
System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 20.5.1 - /private/var/folders/tw/_w_8z911785_95r8mmks1hyw0000gn/T/xfs-c827f2ff/node
    Yarn: 4.0.0-rc.50 - /private/var/folders/tw/_w_8z911785_95r8mmks1hyw0000gn/T/xfs-c827f2ff/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
```

**Comment by merceyz** [comment] 2023-08-25 08:19
Closing as this is working as intended.

> but if a package I am using uses a package I should be able to use it without installing yet another version of the same package.

No, see https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies.

**Closed by merceyz** 2023-08-25 08:19 UTC
Labels: bug

**Comment by The-Code-Monkey** [comment] 2023-08-25 08:25
Ah ok thank you for explaining @merceyz

**Comment by The-Code-Monkey** [comment] 2023-08-25 08:37
@merceyz sorry to bother you again, after fixing the chalk error im getting this error

```
(typescript) RollupError: src/index.ts:3:24 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

import * as React from 'react';

```

Here is my yarn.lock for that package
```
"@techstack/react-lazy-named@workspace:*, @techstack/react-lazy-named@workspace:packages/react-lazy-named":
  version: 0.0.0-use.local
  resolution: "@techstack/react-lazy-named@workspace:packages/react-lazy-named"
  dependencies:
    "@techstack/tcm-cli": "workspace:*"
    "@testing-library/react": "npm:14.0.0"
    "@types/react": "npm:^18.2.21"
    jest-environment-jsdom: "npm:29.6.2"
    lodash: "npm:4.17.21"
    lodash-es: "npm:4.17.21"
    react: "npm:^18.2.0"
  languageName: unknown
  linkType: soft
```

My problem is that both react and types/react are installed and linked to that package directly. Any idea whats causing this?
