### ISSUE TITLE
yarn run xxx script slow[Bug?]: 

### ISSUE THREAD

**Issue by baozi510** [yarnpkg/berry#5984] opened 2023-11-19 14:39 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

yarn run script slow

### To reproduce

  "scripts": {
    "test": "echo test"

  },
 time yarn run test
test

real    0m1.030s
user    0m1.025s
sys     0m0.347s

### Environment

```shell
Node.js v20.9.0

yarn --version
4.0.2
```

**Comment by merceyz** [comment] 2023-11-19 15:31
Duplicate of https://github.com/yarnpkg/berry/issues/2575

**Closed by merceyz** 2023-11-19 15:31 UTC
Labels: bug
