### ISSUE TITLE
[Bug] yarn workspace foreach not looping through workspaces

### ISSUE THREAD

**Issue by BjornVanslembrouck** [yarnpkg/berry#2396] opened 2021-01-21 20:38 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

I just updated our project to berry so I could start using the `foreach` functionality on workspaces to avoid having empty commands in the script property of my `package.json` files across my workspaces.

Problem I have is that when I run the command `yarn workspaces foreach -v run build` it only executes the command in the first workspace of my root folder and skips the rest.

If I delete that specific workspace, the new first one in the list gets build, but then it stops again.

I followed the migration documentation but it doesn't seem to work.

**To Reproduce**

I attached a very small sample project that demonstrates the issue.
If you run `yarn workspaces list `, you get the following result:
```
➤ YN0000: .
➤ YN0000: packages/workspace1
➤ YN0000: packages/workspace2
➤ YN0000: packages/workspace3
➤ YN0000: Done in 0s 1ms
```

If however you run `yarn workspaces foreach -v run build`, it only comes back with:
```
➤ YN0000: [workspace1]: workspace1
```

**Screenshots**

Sample project attached

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v15.2.1
 - Yarn version: 2.4.0

**Sample project**
[temp.zip](https://github.com/yarnpkg/berry/files/5852008/temp.zip)

**Comment by merceyz** [comment] 2021-01-21 20:49
Duplicate of https://github.com/yarnpkg/berry/issues/2214
Duplicate of https://github.com/yarnpkg/berry/issues/2074
Fixed in https://github.com/yarnpkg/berry/pull/2255

**Closed by merceyz** 2021-01-21 20:49 UTC
Labels: bug
