### ISSUE TITLE
[Bug?]: Dynamic import does not use the PnP API when importing a ESM from CommonJS

### ISSUE THREAD

**Issue by flying-sheep** [yarnpkg/berry#4045] opened 2022-01-31 12:56 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Trying to use the https://github.com/xojs/vscode-linter-xo extension with yarn 2, I ran into problems in the past, see #3708. With nodejs 17.4, one blocker is gone, but it doesn’t work yet:

The yarn PNP loader doesn’t seem to be used when a dynamic import from a commonjs module imports a ESM [like in this dynamic import](https://github.com/xojs/vscode-linter-xo/blob/ddc03f4cbcf47a1e5332dc15bc7daa70c838aeda/server/server.js#L489):

```js
const { Files } = require('vscode-languageserver/node')
const { URI } = require('vscode-uri')

async function main() {
	const xoFilePath = await Files.resolve('xo', undefined, '.')
	const xoUri = URI.file(xoFilePath).toString()
	await import(xoUri)
}

main()
```

### To reproduce

Sadly I don’t think reproducing using sherlock is possible, as this requires running `node` with `NODE_OPTIONS` set, and sherlock [doesn’t seem to support that](https://github.com/yarnpkg/berry/blob/3214bfa879fe7867dcd3313b50f326edcd3b88c5/scripts/actions/sherlock-prepare.js#L79). I made a reproducer in https://github.com/flying-sheep/repro-yarn-xo

1. `git clone https://github.com/flying-sheep/repro-yarn-xo.git && cd repro-yarn-xo`
2. `yarn start` (i.e. `bash .yarn/sdks/xo/node.sh import-xo.js`)
3. See the following error:

	  ```
	  node:fs:1538
	    handleErrorFromBinding(ctx);
	    ^
	  
	  Error: ENOTDIR: not a directory, stat '/home/phil/Dev/Web/repro-yarn-xo/.yarn/cache/xo-npm-0.47.0-3e655742d0-5bd4d72322.zip/node_modules/xo/index.js'
	      at statSync (node:fs:1538:3)
	      at tryStatSync (node:internal/modules/esm/resolve:160:13)
	      at finalizeResolution (node:internal/modules/esm/resolve:387:17)
	      at moduleResolve (node:internal/modules/esm/resolve:944:10)
	      at defaultResolve (node:internal/modules/esm/resolve:1041:11)
	      at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
	      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
	      at ESMLoader.import (node:internal/modules/esm/loader:332:22)
	      at importModuleDynamically (node:internal/modules/cjs/loader:1036:29)
	      at importModuleDynamicallyWrapper (node:internal/vm/module:437:21) {
	    errno: -20,
	    syscall: 'stat',
	    code: 'ENOTDIR',
	    path: '/home/phil/Dev/Web/repro-yarn-xo/.yarn/cache/xo-npm-0.47.0-3e655742d0-5bd4d72322.zip/node_modules/xo/index.js'
	  }
	  
	  Node.js v17.4.0
	  ```

### Environment

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 17.4.0 - /tmp/xfs-b43fe39f/node
    Yarn: 3.1.1 / 3.2.0-rc2 - /tmp/xfs-b43fe39f/yarn
    npm: 8.4.0 - /usr/bin/npm
```

**Comment by merceyz** [comment] 2022-01-31 14:04
It's because the PnP linker explicitly lists `.yarn/sdks/**` as a folder it shouldn't control
https://github.com/yarnpkg/berry/blob/a248d0be7aa21cd4753374c1e333320858c06c1e/packages/plugin-pnp/sources/PnpLinker.ts#L280

Maybe @arcanis remembers why its there

**Comment by flying-sheep** [comment] 2022-01-31 14:15
I don’t think that applies, as the script within `.yarn/sdks` is a bash script. The JS code isn’t in there. Moving the bash script out of `.yarn/sdks` doesn’t prevent the error.

**Comment by arcanis** [comment] 2022-01-31 14:26
> The solution would be to remove it but maybe @arcanis remembers why its there

Was added in https://github.com/yarnpkg/berry/pull/646; I don't find a reference to NODE_PATH anymore, so perhaps this isn't needed anymore?

**Comment by merceyz** [comment] 2022-01-31 14:30
Ah, I was looking at the repro from https://github.com/yarnpkg/berry/issues/3708 sorry about that.

This was fixed in https://github.com/yarnpkg/berry/pull/3667 so this is a duplicate of https://github.com/yarnpkg/berry/issues/3687

**Closed by merceyz** 2022-01-31 14:30 UTC
Labels: bug

**Comment by flying-sheep** [comment] 2022-01-31 14:39
Thanks! I actually did `yarn set version canary` but forgot to do `yarn` after before trying.
