### ISSUE TITLE
[Bug]: `.pnp.cjs` fails when `toPortablePath` is provided a `Buffer`

### ISSUE THREAD

**Issue by CharlesStover** [yarnpkg/berry#4913] opened 2022-09-27 18:18 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When I call `rmSync('./path/to/directory')` on Windows, in some instances I get this error:

```
    TypeError: p.replace is not a function

      16678 |   if (process.platform !== `win32`)
      16679 |     return p;
    > 16680 |   p = p.replace(/\\/g, `/`);
            |         ^
      16681 |   let windowsPathMatch, uncWindowsPathMatch;
      16682 |   if (windowsPathMatch = p.match(WINDOWS_PATH_REGEXP))
      16683 |     p = `/${windowsPathMatch[1]}`;

      at Object.toPortablePath (../../.pnp.cjs:16680:9)
      at PosixFS.mapToBase (../../.pnp.cjs:19251:18)
      at PosixFS.rmdirSync (../../.pnp.cjs:19162:39)
      at URLFS.rmdirSync (../../.pnp.cjs:19162:24)
          at Array.forEach (<anonymous>)
      at Object.rmSync (src/coverage.test.ts:18:7)
```

**Notes:**
* The original function call is `fs.rmSync('./path/to/directory', { force: true, recursive: true })`.
* This does not happen for all calls to `rmSync` (another call in this same file, to a directory with `force` and `recursive`, worked fine).
* This is not easily reproducible. I created a separate script that does nothing but `rmSync` this same directory, and it successfully removed it.
* This is a `jest` `afterEach` cleanup script that does nothing but `rmSync` the temporary files.

I debugged this to see the value of `p` by editing `.pnp.cjs` like so:
```
if (!p.replace) {
  throw new Error(JSON.stringify(p));
}
```

I received:
```
{"type":"Buffer","data":[...]}
```

So I stringified the Buffer:

```
if (typeof p !== 'string') {
  throw new Error(p.toString());
}
```

And I received:
```
\\?\C:\path\to\directory\a-nested-directory-here
```

**Notes:**
* I don't know why the path is prefixed with `\\?`.
* It may be relevant that it was trying to delete a nested directory from the original path.
* It _should_ delete the nested directory from the original path, because it is `recursive`.
* The other `rmSync` (that succeeds) in the original script does not have a nested directory.

I added this hot fix to `.pnp.cjs` to see if it worked:
```
if (typeof p !== 'string') {
  p = p.toString();
}
```

Lo and behold, it worked. The `rmSync` call now succeeds successfully.

### To reproduce

Unfortunately, I cannot reproduce this outside of the full-featured Jest test. Hopefully the debug code examples above can help.

```
// Windows
rmSync('./path/to/directory', {
  force: true,
  recursive: true,
});
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 18.9.1 - ~\AppData\Local\Temp\xfs-bb0f7773\node.CMD
    Yarn: 3.2.3 - ~\AppData\Local\Temp\xfs-bb0f7773\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by merceyz** [comment] 2022-09-27 19:29
Duplicate of https://github.com/yarnpkg/berry/issues/1818

**Closed by merceyz** 2022-09-27 19:29 UTC
Labels: bug
