### ISSUE TITLE
[Feature] "reverseResolve", for TypeScript support

### ISSUE THREAD

**Issue by pauldraper** [yarnpkg/berry#548] opened 2019-10-24 22:19 UTC
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

I'm not 100% sure what the right answer is, but there is a strong intersection here of pnp and TS expertise that should be able to arrive at it.

**Describe the user story**

AFAIK, pnp cannot (fully) support the TypeScript compiler needs in creating declaration files.

a/thing module

```ts
import { SomeType } from './some';

export const a = new SomeType();
```

b module

```ts
import { a } from 'a/thing';
export const b = a;
```

The TypeScript compiler produce the following typed declaration file for the b module:

```ts
declare export const b: import('a/some').SomeType;
```

The TypeScript compiler applies some heuristics to obtain this; sometimes a portable path is not possible and it produces an error.

**Describe the solution you'd like**

I think this requires a `reverseResolve` function or something similar.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

Don't support inferred imports for TypeScript declaration files.

**Additional context**

Also my remarks in the TypeScript project: https://github.com/microsoft/TypeScript/issues/28289#issuecomment-529126737

**Comment by arcanis** [comment] 2019-10-25 06:00
I'm not sure I fully understand the problem that happens (we publish TS type declarations and they seem to work fine) - do you have a reproduction repo to highlight the behavior that regressed?

**Comment by pauldraper** [comment] 2019-11-05 22:28
> we publish TS type declarations and they seem to work fine

Yes it works with pnpify.

With pnpify, tsc still performs the same resolution and reverse resolution logic, so the output is of course the same.

If you wanted tsc to support PnP using pnpapi, you would soon find that it requires "reverse resolution" to synthesize type import() statements in declaration files.

**Comment by arcanis** [comment] 2019-11-28 09:48
I'm going to close this issue since I don't understand how to reproduce the problem (https://github.com/Microsoft/TypeScript/issues/28289 seemed to work just fine and was using the API directly).

If you get the chance to make a standalone repo I can clone and run a command in to see what should work and what doesn't, feel free to reopen!

**Closed by arcanis** 2019-11-28 09:48 UTC
Labels: enhancement
