### ISSUE TITLE
[Bug?]: peerDependencies not supporting npm: protocol

### ISSUE THREAD

**Issue by manoraj** [yarnpkg/berry#6209] opened 2024-04-06 16:59 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

We have monorepo with workspaces. For easier bumping of packages across our organization, we have the next packages pointing to the next version that we plan to bump. To support this, we have peerDependencies with the npm protocol.

For example:

```javascript
{
    "name": "package-a",
    "private": true,
    "version": "0.0.0",
    "peerDependencies": {
          "react-next": "npm:react@^16.8.6"
    }
}
``` 

But, yarn does not support this as it is complaining `package-a: Invalid dependency range for 'react-next'`  and converting the version to `*` upon `yarn install`

```javascript
"peerDependencies": {
      "react-next": "npm:react@^16.8.6"
 }
``` 

### To reproduce

1. Add peerDependencies to the existing workspace with the `npm:` protocol (Ex: `"react-next": "npm:react@^16.8.6"`)
2. Run `yarn install`

Expected:
`yarn install` command should complete without any warning
Actual:
`yarn install` command changes `react-next` version from `"react-next": "npm:react@^16.8.6"` to `"react-next": "*`

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.17.1 - /private/var/folders/x2/2sz9b9b9655ct3zqnwfhfpmh0000gn/T/xfs-ab7c4ffe/node
    Yarn: 3.6.1 - /private/var/folders/x2/2sz9b9b9655ct3zqnwfhfpmh0000gn/T/xfs-ab7c4ffe/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    bun: 1.0.2 - /opt/homebrew/bin/bun
```

**Comment by arcanis** [comment] 2024-04-06 17:12
Duplicate of https://github.com/yarnpkg/berry/issues/6113#issuecomment-1943284207

**Closed by arcanis** 2024-04-06 17:12 UTC
Labels: bug
