### ISSUE TITLE
[Bug] yarn set version berry does not set v2

### ISSUE THREAD

**Issue by domoritz** [yarnpkg/berry#2713] opened 2021-04-07 21:18 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

```
❯ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/dominik/Code/vega-lite/.yarn/releases/yarn-berry.cjs...
Updating /Users/dominik/Code/vega-lite/.yarnrc.yml...
Done!
❯ yarn --version
1.22.10
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v15.14.0
 - Yarn version: 1.22.10

**Additional context**

I am running yarn installed via homebrew on fish, version 3.2.2. 

I tried migrating https://github.com/vega/vega-embed as described in https://yarnpkg.com/getting-started/migration#why-should-you-migrate.

**Comment by merceyz** [comment] 2021-04-07 21:23
I'm guessing you have a `.yarnrc.yml` or `.yarnrc` file in your home directory that is overriding it

Duplicate of https://github.com/yarnpkg/berry/issues/1635

**Closed by merceyz** 2021-04-07 21:23 UTC
Labels: bug
