### ISSUE TITLE
[Bug?]: Upgrading from v3.1.1 to v3.2.0 causes TS Webpack to hang without error/output

### ISSUE THREAD

**Issue by awdyson** [yarnpkg/berry#4208] opened 2022-03-11 00:16 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Title says about as much as I can about the bug here.
No amount of "verbose" settings or command line flags were getting me more than dev-server's "wait until bundle finished".
I'm also really unsure as to why Yarn would cause an issue like this.
That said, running `yarn set version stable` and `yarn` before `yarn start` causes the issue, and the same set with `3.1.1` replacing `stable` fixes it.

I figured maybe there was an issue with directory references being "better-respected" now.
Something like `/` instead of `./` causing the whole filesystem to be parsed.
However, I combed through my code and couldn't find a path starting with `/`.

### To reproduce

My Webpack config if it helps, run with a special tsconfig file: `TS_NODE_PROJECT='tsconfig.webpack.json' webpack serve`
``` typescript
import ReactRefreshWebpackPlugin from '@pmmmwh/react-refresh-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import ReactRefreshTypescript from 'react-refresh-typescript';
import { Configuration, WatchIgnorePlugin, WebpackPluginInstance } from 'webpack';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
import { Configuration as DevServer } from 'webpack-dev-server';

const loaders = {
  reactRefresh: require.resolve('react-refresh/babel'),
  sourceMap: require.resolve('source-map-loader'),
  svg: require.resolve('svg-url-loader'),
  ts: require.resolve('ts-loader'),
  url: require.resolve('url-loader'),
};

const root = process.cwd();
const src = `${root}/src`;
const dist = `${root}/dist`;

interface Argv {
  env: { analyzeBuild: boolean };
  mode: string;
}

type Config = Configuration & { devServer: DevServer };
export default function makeConfig(_: unknown, argv: Argv): Config {
  console.info('argv: ', argv);

  const isDev = argv.mode === 'development';
  const analyzeBundle = argv.env.analyzeBuild;

  return {
    devServer: {
      historyApiFallback: true,
      hot: true,
      port: 5200,
    },
    devtool: isDev ? 'eval-cheap-module-source-map' : 'source-map',
    entry: [`${src}/index.tsx`],
    // ⬇ Left as an example
    // ignoreWarnings: [{ module: /material-ui-lab/, message: /@mui\/unstyled/ }],
    mode: isDev ? 'development' : 'production',
    module: {
      rules: [
        // Raw files
        {
          test: /\.(png|jpg|gif)$/i,
          use: [{ loader: loaders.url }],
        },
        // SVGs
        {
          test: /\.svg$/i,
          use: [{ loader: loaders.svg }],
        },
        {
          // Source maps
          enforce: 'pre',
          exclude: [/@reduxjs\/toolkit/],
          test: /\.js$/,
          use: [loaders.sourceMap],
        },
        {
          // TypeScript
          exclude: /node_modules/,
          test: /\.tsx?$/,
          use: [
            {
              loader: loaders.ts,
              options: {
                getCustomTransformers: () => ({
                  before: isDev ? [ReactRefreshTypescript()] : [],
                }),
                onlyCompileBundledFiles: true,
                transpileOnly: true,
              },
            },
          ],
        },
      ],
    },
    optimization: { usedExports: true },
    output: {
      path: dist,
    },
    plugins: [
      new ForkTsCheckerWebpackPlugin(),
      new HtmlWebpackPlugin({ publicPath: './', template: `${src}/index.ejs` }),
      new WatchIgnorePlugin({ paths: [/\.js$/, /\.d\.ts$/] }),
      ...(isDev ? [new ReactRefreshWebpackPlugin({ overlay: false })] : []),
      ...(analyzeBundle ? [new BundleAnalyzerPlugin() as unknown as WebpackPluginInstance] : []),
    ],
    resolve: {
      alias: { '~': `${src}/` },
      extensions: ['.ts', '.tsx', '.json', '.js', '.jsx', '.mjs'],
    },
    target: 'web',
  };
}
```

### Environment

```shell
System:
    OS: macOS 11.6.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.16.1 - /private/var/folders/_1/3y0l6b0x0xd7_2vhtt4n089184gr2c/T/xfs-71cdc61f/node
    Yarn: 3.2.0 - /private/var/folders/_1/3y0l6b0x0xd7_2vhtt4n089184gr2c/T/xfs-183926a8/yarn
    npm: 7.11.2 - ~/.local/share/nvm/v14.16.1/bin/npm
```

### Additional context

I like to keep my dependencies super up-to-date, but I haven't had time to work on this project for a couple months.
The above issue occurs with the latest package versions from 2 months ago and the latest versions from 2 minutes ago.

**Comment by merceyz** [comment] 2022-03-11 11:05
Duplicate of https://github.com/yarnpkg/berry/issues/4157

**Closed by merceyz** 2022-03-11 11:05 UTC
Labels: bug

**Comment by awdyson** [comment] 2022-03-11 20:29
From the issue linked above, upgrading to node v16 fixed the issue for me.
