### ISSUE TITLE
[Bug]: Internal Error: The package @yarnpkg/monorepo@workspace:. isn't supported by any of the available linkers

### ISSUE THREAD

**Issue by joeldenning** [yarnpkg/berry#2187] opened 2020-11-29 19:34 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

**To Reproduce**

When I run `yarn set version from sources`, I get the following error:

```
➤ YN0000: Fetching the latest commits

  $ git fetch origin master --force
  $ git reset --hard FETCH_HEAD
  $ git clean -dfx

➤ YN0000: Building a fresh bundle

Internal Error: The package @yarnpkg/monorepo@workspace:. isn't supported by any of the available linkers
    at fn (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/packages/yarnpkg-core/sources/scriptUtils.ts:281:13)
    at Function.openPromise (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/packages/yarnpkg-fslib/sources/ZipOpenFS.ts:36:20)
    at Object.hasPackageScript (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/packages/yarnpkg-core/sources/scriptUtils.ts:273:26)
    at RunCommand.execute (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/packages/plugin-essentials/sources/commands/run.ts:77:31)
    at RunCommand.validateAndExecute (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1118:26)
    at Cli.run (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1371:24)
    at EntryCommand.execute (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/packages/plugin-essentials/sources/commands/entries/run.ts:18:14)
    at EntryCommand.validateAndExecute (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1118:26)
    at Cli.run (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1371:24)
    at Cli.runExit (/private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1388:28)
➤ YN0001: Error: Child "yarn" exited with exit code 1
    at ChildProcess.<anonymous> (/Users/joeldenning/code/musashi-root-config/.yarn/releases/yarn-berry.cjs:2:378609)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
➤ YN0000: Failed with errors in 5s 128ms
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5524384/100551632-2204cb00-323f-11eb-9bdc-09b27217c601.png)

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] OSX Big Sur
 - Node version [e.g. 8.15.0, 10.15.1, ...] 14.15.0
 - Yarn version [e.g. 2.0.0-rc1, ...] 2.3.3

**Additional context**

**Comment by larixer** [comment] 2020-11-30 11:45
@joeldenning How can we reproduce the problem, can you upload the repo somewhere on which we can reproduce the problem, or can you provide precise repro steps?

**Comment by joeldenning** [comment] 2020-11-30 17:56
> can you upload the repo somewhere

This error is not related to running yarn in a code repository - it occurs whenever I run `yarn set version from sources` inside of any directory.

> can you provide precise repro steps?

For me:

```sh
npm i -g yarn
yarn set version berry
yarn set version from sources
```

I imagine that on other computers those commands don't throw an error - I don't know what about my environment would cause it to fail.

**Comment by merceyz** [comment] 2020-12-09 13:17
Do you have a `.yarnrc.yml` file in your home directory that sets an invalid `nodeLinker` option?

**Comment by joeldenning** [comment] 2020-12-09 18:15
I do have a `.yarnrc` in my home directory with the following contents:

```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
```

I tried `yarn set version from sources` again and no longer receive the nodeLinker error, but receive a new error now:

```sh
~ [1] $ yarn set version from sources
➤ YN0000: Fetching the latest commits

  $ git fetch origin master --force
  $ git reset --hard FETCH_HEAD
  $ git clean -dfx

➤ YN0000: Building a fresh bundle

Usage Error: Unrecognized or legacy configuration settings found: changesetIgnorePatterns - run "yarn config -v" to see the list of settings supported in Yarn (in /private/var/folders/74/8gbl9tds5h7fmjz4cxjvywyr0000gn/T/yarnpkg-sources/d0a670/.yarnrc.yml)

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
➤ YN0001: Error: Child "yarn" exited with exit code 1
    at ChildProcess.<anonymous> (/Users/joeldenning/.yarn/releases/yarn-berry.cjs:2:403919)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
➤ YN0000: Failed with errors in 1s 256ms
~ [1] $ cat .yarnrc.yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
~ $ cat ../.yarnrc.yml
cat: ../.yarnrc.yml: No such file or directory
~ [1] $ cat ../../.yarnrc.yml
cat: ../../.yarnrc.yml: No such file or directory
~ [1] $ pwd
/Users/joeldenning
```

**Comment by merceyz** [comment] 2020-12-09 18:31
As https://yarnpkg.com/getting-started/install mentions you should be running that command in your project, not the home directory (i.e. remove `yarnPath` from your global config). Will keep this open as there does seem to be a bug when installed globally

**Comment by merceyz** [comment] 2022-10-19 14:20
Duplicate of https://github.com/yarnpkg/berry/issues/2121

**Closed by merceyz** 2022-10-19 14:20 UTC
Labels: bug, upholded
