### ISSUE TITLE
[Bug?]: version is still 1.22.11 even after yarn set version berry

### ISSUE THREAD

**Issue by joker-777** [yarnpkg/berry#3321] opened 2021-08-19 12:24 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Hi, on our ubuntu box we tried to upgrade yarn to berry but it somehow doesn't want to work. Even after running `yarn set version berry` it still says

```
yarn --version
1.22.11
```

The strange thing is that I can't switch to the latest version manually either

```
yarn set version 3.0.1
Resolving 3.0.1 to a url...
error An unexpected error occurred: "Release not found: 3.0.1".
info If you think this is a bug, please open a bug report with the information provided in "/var/local/test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```

### To reproduce

```
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \ 
 && wget https://github.com/yarnpkg/yarn/releases/download/v1.22.11/yarn_1.22.11_all.deb \
 && dpkg -i yarn_1.22.11_all.deb \
 && apt-get update -qq && apt-get install -y nodejs
mkdir test
cd test
npm init
yarn set version berry
```

### Environment

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

yarn versions v1.22.11
{
  yarn: '1.22.11',
  node: '14.17.5',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

**Comment by ylemkimon** [comment] 2021-08-21 22:22
Yarn 2 is installed on per-project basis, i.e., running `yarn set version berry` will install Yarn 2 on the current working directory (`test` in your case) and the global Yarn would still be Yarn 1. See the [installation docs](https://yarnpkg.com/getting-started/install) for more information.

**Comment by gingerlime** [comment] 2021-08-22 13:21
@ylemkimon I work with @joker-777 

The problem is that the version in the test directly is still 1.22.11, even after running `yarn set version berry`. See the reproduction steps that @joker-777 mentioned. Here's the output of the last 3 commands

```
root@server:/tmp# mkdir test
root@server:/tmp# cd test
root@server:/tmp/test# npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to /tmp/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes)
root@server:/tmp/test# yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...

Saving it into /tmp/test/.yarn/releases/yarn-berry.cjs...
Updating /tmp/test/.yarnrc.yml...
Done!
root@server:/tmp/test# yarn --version
1.22.11
```
☝️

**Comment by merceyz** [comment] 2021-08-22 14:16
Check `~/.yarnrc(.yml)` for a `yarnPath` config that is overriding the one in the project

**Comment by gingerlime** [comment] 2021-08-22 14:22
Thanks @merceyz. I think this is the reason.

I'm very confused however. Why would the home folder `~/.yarnrc.yml` take precedence over the project-specific `./.yarnrc.yml` ?

**Comment by merceyz** [comment] 2021-08-22 14:51
Duplicate of https://github.com/yarnpkg/berry/issues/2121

**Comment by merceyz** [comment] 2021-08-22 14:51
> Why would the home folder ~/.yarnrc.yml take precedence over the project-specific ./.yarnrc.yml ?

It's a bug in Yarn 1.x that hasn't been addressed yet

**Closed by merceyz** 2021-08-22 14:51 UTC
Labels: bug
