### ISSUE TITLE
[Bug] `yarn add` does not respect `latest` tag

### ISSUE THREAD

**Issue by SimenB** [yarnpkg/berry#2206] opened 2020-12-03 15:01 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

`yarn add husky` right now will put `^4.3.0` (which is `latest`) into `package.json`, but install `4.3.1` which is _not_ marked as `latest`.

**To Reproduce**

https://github.com/SimenB/yarn-install-latest

All I did was

```sh-session
$ yarn init -y
$ yarn add -D husky
$ yarn policies set-version berry
$ yarn
$ rm yarn.lock && yarn
```

(plus some `.gitignore` stuff)

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: macOS
 - Node version 14.15.0
 - Yarn version 2.4.0

**Additional context**

N/A

**Comment by arcanis** [comment] 2020-12-03 15:19
Same problem as always when `latest` is involved: the registry lies, the latest stable version isn't what `latest` reports (`4.3.0`), it's `5.0.4` (or `4.3.1` for the 4.x branch). I assume Husky either forgot to change the tag to `4.3.1`, or perhaps they tried reverting it to an older release for some reason. Regardless, the behavior is expected:

- `yarn add` resolves `latest` (to `4.3.0`, what the registry tells us), then injects it into the package.json as a range (`^4.3.0`)
- then the install sees the range we created, finds the list of versions (from which we have `4.3.1`), and uses the highest compatible one - ie `4.3.1`. Since `latest` is just a tag like any other (and has been fulling resolved long before we reach this point anyway), there's nothing that prevents us from doing so (the `4.3.1` release isn't even marked as deprecated).

It's confusing, but not a bug - imo the registry really shouldn't let `latest` be anything else than the latest stable semver release, or shouldn't have `latest` in the first place (and let the clients pick the highest themselves) 😕

**Closed by arcanis** 2020-12-03 15:19 UTC
Labels: bug

**Comment by SimenB** [comment] 2020-12-03 15:33
How is it not considered a bug that `yarn add something` installs a version _not_ `latest` of `something`? I get that it's two different parts of the system (one being "what's latest?" and the other "install the range") but IMO they should just communicate that restraint somehow.

I didn't ask yarn to install "highest version of v4" I asked it to install `latest`. Yarn v1, pnpm and npm all do it correctly.

---

Whether or not `latest` is a good concept or not is a philosophical discussion.

**Comment by arcanis** [comment] 2020-12-03 15:48
> they should just communicate that restraint somehow

That's exactly what I mean - the `latest` tag is no constraint.

Basically, there are various possible behaviors (on top of the current one):

- Either `latest` get stored as `latest` in the `package.json`, then we have issues from people telling us they don't want tags in their manifests.

- Either `latest` get stored as a strict semver (ie `4.3.0`, not `^4.3.1`), then we have issues from people telling us they don't understand why that happens, it has to be a bug.

- Either `latest` get stored as `^4.3.0` but we don't actually use this range in the following install, then we get issues from people telling us that followup `upgrade-interactive` still suggest `^4.3.1` (same thing as this issue, essentially).

All of them end up with people being confused. The `latest` concept isn't just a philosophical discussion, but merely me pointing out that the bug lies higher in the stack, and expectations have to be tuned accordingly. Whatever Yarn1, pnpm, npm do, it has its own drawbacks, and it ends up being a matter of tradeoffs.

Not saying the current behavior is the best, just that in this case, there's no good one, and regardless of what you want it'll come with its own poison.

**Comment by arcanis** [comment] 2020-12-04 00:18
Opened a thread about this here: https://github.com/npm/feedback/discussions/109
