### ISSUE TITLE
[Bug]: Can't run script before install with nodeLinked: node-modules

### ISSUE THREAD

**Issue by natcohen** [yarnpkg/berry#4197] opened 2022-03-08 09:38 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I run a script (from my `package.json` file) before I run `yarn install`. The script sets up the configuration for a private package. In my `.yarnrc.yml`, I have `nodeLinker: node-modules`.

When I run `yarn run myscript` I have the following error:

    Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
    
    $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

A script should be able to be run before `install` is run for configuring private packages.

### To reproduce

Run `yarn run myscript` with the following files before `yarn install`

package.json
```
{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "main": "app.js",
  "type": "module",
  "scripts": {
    "myscript": "echo 'hello'"
  }
  "dependencies": {
    "express": "^4.17.1"
  }
}
```

.yarnrc.yml

```
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs
```

### Environment

```shell
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.1 - /private/var/folders/xp/3hdr9q512vbdv0hmdf7wsm5w0000gn/T/xfs-08c5b722/node
    Yarn: 3.2.0 - /private/var/folders/xp/3hdr9q512vbdv0hmdf7wsm5w0000gn/T/xfs-08c5b722/yarn
    npm: 8.1.2 - /usr/local/bin/npm
```

**Comment by larixer** [comment] 2022-03-09 15:48
Duplicate of #2701

**Closed by larixer** 2022-03-09 15:48 UTC
Labels: bug
