### ISSUE TITLE
[Feature] Add `cafile` support to the config file 

### ISSUE THREAD

**Issue by manolakis** [yarnpkg/berry#1765] opened 2020-08-26 09:56 UTC
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Doing a PoC about the use of yarn 2 I found that I can't use it at my company because we have our own registry with a self-signed certificate and, as yarn 2 didn't read the `.npmrc` there is no way to specify the ca file for the certificate.

**Describe the solution you'd like**

It would be great to read some options from the `.npmrc` like the registry, the auth token or the ca file, because those options also depends on the user and environment in which yarn 2 are going to be executed. If that's not an option, at least adding the cafile in the `.yarnrc.yaml` would be great.

**Describe the drawbacks of your solution**

Makes yarn 2 impossible to use in some environments where security is a must and owns their own internal registry.

**Comment by arcanis** [comment] 2020-08-26 10:01
Duplicate of #798 - but yes it would be nice!

**Closed by arcanis** 2020-08-26 10:01 UTC
Labels: enhancement
