### ISSUE TITLE
[Meta] Changelog & Versioning

### ISSUE THREAD

**Issue by rkistner** [yarnpkg/berry#1538] opened 2020-07-02 14:59 UTC
The current release status is quite confusing to me:

 * There was an [announcement](https://dev.to/arcanis/introducing-yarn-2-4eh1) in January on the first stable release of Yarn 2.
 * Installing Yarn 2 appears to retrieve the latest version from the master branch, which is currently 2.0.0-rc.36.
 * I'm assuming the above version is referring to the version of `@yarnpkg/cli`, but this is not clear.
 * The documentation site is for Yarn 2 by default.
 * I cannot find any indication of a changelog or release history on the documentation site or this repo (other than the commit history, which is not practical to read).

Is there any plan to start using a "stable" versioning scheme and changelog at some point?

**Comment by arcanis** [comment] 2020-07-05 09:39
Duplicate of https://github.com/yarnpkg/berry/issues/1316#issuecomment-626649567

**Closed by arcanis** 2020-07-05 09:39 UTC
