### ISSUE TITLE
[Bug?]: Cannot open file in dependencies of yarn v2 after upgraded to win11

### ISSUE THREAD

**Issue by LOLBRUHNICE** [yarnpkg/berry#3563] opened 2021-10-12 23:53 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After I upgraded to win 11,when I try to use `Go to Definition` of a variable imported from dependency,it will give me an error
Something like:
`
Unable to open 'XXX.d.ts': Unable to read file '\^zip:\d:\Path_to_your_project\.yarn\cache\XXXX.zip\XXX\index.d.ts' (Error: Unable to resolve nonexistent file '\^zip:\d:\Path_to_your_project\.yarn\cache\XXXX.zip\XXX\index.d.ts').
`

### To reproduce

/

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.11.0 - ~\AppData\Local\Temp\xfs-e4b99682\node.CMD
    Yarn: 3.0.2 - ~\AppData\Local\Temp\xfs-e4b99682\yarn.CMD
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by merceyz** [comment] 2021-10-12 23:54
Duplicate of https://github.com/yarnpkg/berry/issues/3539

**Closed by merceyz** 2021-10-12 23:54 UTC
Labels: bug
