### ISSUE TITLE
[Bug?]: The path cannot be recognized if it contains multibyte characters.

### ISSUE THREAD

**Issue by logue** [yarnpkg/berry#4499] opened 2022-05-27 02:59 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When the path of a project using Yarn3 contains multibyte characters such as Japanese, the path is garbled and a MODULE_NOT_FOUND error occurs.

### To reproduce

```ps
PS D:\Documents\日本語のパス\vite-vue2-starter> yarn run dev
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\Documents\譌･譛ｬ隱槭・繝代せ\vite-vue2-starter\node_modules\vite\bin\vite.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)     
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
  Binaries:
    Node: 17.9.0 - ~\AppData\Local\Temp\xfs-bc1cb82d\node.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

In this case, it seems that the error is that the module cannot be found because the "日本語のパス" in yarn recognizes the garbled path as "譌･譛ｬ隱槭・繝代せ".

I moved this project to a path that doesn't contain multibyte characters and checked it and it worked fine.

It did not occur in Yarn1.

**Comment by merceyz** [comment] 2022-05-27 13:30
Duplicate of https://github.com/yarnpkg/berry/issues/4448

**Closed by merceyz** 2022-05-27 13:30 UTC
Labels: bug
