### ISSUE TITLE
[Bug?]: Nodejs 18.6.0 breaks ESM

### ISSUE THREAD

**Issue by espoal** [yarnpkg/berry#4632] opened 2022-07-16 14:11 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After updating nodejs to 18.6.0 several features stop working. E.g. see [this issue](https://github.com/evanw/esbuild/issues/2392). The ESM loader is mostly affected, but also without that some external deps stop working.

### To reproduce

```js repro

mkdir estest && cd estest
yarn init -2
printf "pnpEnableEsmLoader: true" >> .yarnrc.yml
yarn add esbuild

```

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 18.6.0 - /tmp/xfs-9ed41e1d/node
    Yarn: 3.2.1 - /tmp/xfs-9ed41e1d/yarn
```

### Additional context

Switching to nodejs 18.4.0 temporarly fixes the issue.

**Comment by merceyz** [comment] 2022-07-16 14:12
Duplicate of https://github.com/yarnpkg/berry/issues/4629

**Closed by merceyz** 2022-07-16 14:12 UTC
Labels: bug
