### ISSUE TITLE
[Bug] Can't install plugins on "from sources"

### ISSUE THREAD

**Issue by Peeja** [yarnpkg/berry#2961] opened 2021-05-31 21:33 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

When running Yarn from sources, plugins cannot be installed.

**To Reproduce**

```sh
yarn init
yarn set version from sources
yarn plugin import typescript
```

Output:

```
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/@yarnpkg/cli/3.0.0-rc.2.git.20210530.hash-2b6ea767/packages/plugin-constraints/bin/%40yarnpkg/plugin-constraints.js
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://github.com/yarnpkg/berry/raw/@yarnpkg/cli/3.0.0-rc.2.git.20210530.hash-2b6ea767/packages/plugin-constraints/bin/%40yarnpkg/plugin-constraints.js
➤ YN0000: Failed with errors in 1s 658ms
```

(I had trouble getting Sherlock to run this, but I think the cause of the issue is clear anyhow.)

**Additional context**

The `yarn plugin import` is failing because there's nothing at that URL, because the git tag `@yarnpkg/cli/3.0.0-rc.2.git.20210530.hash-2b6ea767` doesn't exist. I'm not sure what the best resolution is for that, but this issue can be a starting point to decide. Some options I see:

* Make `yarn plugin import` clever enough to use the latest actual release as the tag to fetch from.
* Expect that `from sources` can't install plugins.
  * But it would be nice to have this documented somewhere (if it is already, I missed it), and
  * Right now, that leaves no way to install the latest version of TypeScript, because [the new patch for 4.3](https://github.com/yarnpkg/berry/commit/a01852b8e686650025c4241f40bdc96bc6c4f918) hasn't been released yet.

**Comment by merceyz** [comment] 2021-05-31 21:34
Duplicate of https://github.com/yarnpkg/berry/issues/2951

**Closed by merceyz** 2021-05-31 21:34 UTC
Labels: bug
