### ISSUE TITLE
[Bug] Git Urls with : are not supported

### ISSUE THREAD

**Issue by halaei** [yarnpkg/berry#2877] opened 2021-05-11 13:39 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**
According to https://docs.npmjs.com/cli/v7/configuring-npm/package-json, URLs with the following format should be supported, but they are not:
```
git+ssh://git@github.com:npm/cli.git#v1.0.27
git+ssh://git@github.com:npm/cli#semver:^5.0
```
Paths in these URLs are started with colon (:) instead of slash (/). So changing them to / fixes the issue, but they should be supported by yarn 2 as well. yarn 1 is fine.

**To Reproduce**
```json
{
  "name": "test-yarn",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react-native-admob": "git+ssh://git@github.com:halaei/react-native-admob.git#multipleInterstitial"
  }
}
```
`yarn install` gives the following error:
```
YN0001: │ TypeError [ERR_INVALID_URL]: Invalid URL: git@github.com:halaei/react-native-admob.git
at onParseError (internal/url.js:259:9)
at new URL (internal/url.js:335:5)
at Module.d (test-yarn/.yarn/releases/yarn-berry.cjs:2:413750)
at b (test-yarn/.yarn/releases/yarn-berry.cjs:2:137539)
at v (test-yarn/.yarn/releases/yarn-berry.cjs:2:138053)
at F.resolvers.getCandidates (test-yarn/.yarn/releases/yarn-berry.cjs:2:141729)
at n.getCandidates (test-yarn/.yarn/releases/yarn-berry.cjs:2:337366)
at n.getCandidates (test-yarn/.yarn/releases/yarn-berry.cjs:2:337366)
at test-yarn/.yarn/releases/yarn-berry.cjs:2:359022
at Module.w (test-yarn/.yarn/releases/yarn-berry.cjs:2:418493)
```
**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 18.04
 - Node version: v14.16.1
 - Yarn version: 2.4.1

**Comment by merceyz** [comment] 2021-05-11 13:47
Duplicate of https://github.com/yarnpkg/berry/issues/2240

Fixed in https://github.com/yarnpkg/berry/pull/2295 but it hasn't been released yet, you can run `yarn set version from sources` to use it before then

**Closed by merceyz** 2021-05-11 13:47 UTC
Labels: bug

**Comment by halaei** [comment] 2021-05-11 14:05
Great. I thought #2240 was not relevant because it is a bit old and not yet in the latest release. Sorry to bother.
