### ISSUE TITLE
Auto-install when running commands

### ISSUE THREAD

**Issue by aleksandarcolic88** [yarnpkg/berry#5335] opened 2023-03-22 14:04 UTC
**User story**
As a senior developer I often need to work on different type of solutions, and some of them are not my primary language. 
In case I want to make some minor edits and tweaks to solution backed by yarn I cannot simply start unit tests by typing something like `yarn test` (given that there is such script set up in package.json) to make sure that my changes didn't brake something. I must first run  'yarn install'.  If I miss to run `yarn install` before trying `yarn test` error messages can be vague and misleading. 

**Solution**
IF user runs `yarn test` or similar command,  then IF `yarn install` was not done before, RUN yarn install with no flags. 

Similar feature is available in `dotnet` where you can restore packages by running `dotnet restore` but if you want to build solution or run unit tests simply typing `dotnet build` or `dotnet test` will first restore packages. 

This will enable better experience for developers that are not using nodejs+yarn as their primary tools.

**Alternatives**
Improve error messaging

**Comment by merceyz** [comment] 2023-06-03 22:16
Duplicate of https://github.com/yarnpkg/berry/issues/4720

**Closed by merceyz** 2023-06-03 22:16 UTC
Labels: enhancement
