### ISSUE TITLE
[Bug?]: Can't run tsc (& other)

### ISSUE THREAD

**Issue by qumusabel** [yarnpkg/berry#4665] opened 2022-07-25 21:52 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I can't run tsc (or anything).

Tried from scratch multiple times, no success. How can this not work right away?!

### To reproduce

```
yarn init -2
yarn add --dev typescript
yarn install

yarn tsc # nope!
```

### Environment

The command doesn't work. Same error. I am baffled.
yarn 3.2.2

### Additional context

```
 $ yarn tsc
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/home/PROJECT/.yarn/cache/typescript-patch-fc259c5d56-9096d8f6c1.zip/node_modules/typescript/bin/tsc'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.6.0
```

also did `corepack enable`

**Comment by merceyz** [comment] 2022-07-25 22:14
I can't reproduce this, tested with the following commands and it prints the information for `tsc` as expected.
```console
docker run --rm -it node:18.6.0 bash
mkdir foo
cd foo
yarn init -2
yarn add --dev typescript
yarn tsc
```

**Comment by qumusabel** [comment] 2022-07-25 22:22
The Docker image comes with yarn, right?.. On my Arch Linux I had to `sudo npm i -g yarn`. Then the same steps.
Reinstalled yarn, still getting the error.

NPM version is 8.15.0

**Comment by qumusabel** [comment] 2022-07-26 13:07
Oh wow, that was a weird issue. Purging nodejs and all node_modules somehow helped. Works like a charm now...

**Comment by qumusabel** [comment] 2022-07-26 13:27
Hmm, maybe this is an issue in `espruino` library... Besause as soon as I've installed it the error popped up again...

**Comment by merceyz** [comment] 2022-07-26 14:23
Duplicate of https://github.com/yarnpkg/berry/issues/3458

**Closed by merceyz** 2022-07-26 14:23 UTC
Labels: bug, waiting for feedback
