### ISSUE TITLE
[Bug] workspaces commands stop after 1 package on Apple Silicon M1 Macs

### ISSUE THREAD

**Issue by pudgeball** [yarnpkg/berry#2296] opened 2020-12-31 21:25 UTC
- [x] I'd be willing to implement a fix

**Describe the bug**

When using the workspace commands on M1 Macs, yarn 2 will stop processing after running on the first package, eg: `yarn workspaces foreach run build` will only ever build one package.

**To Reproduce**

In a mono-repo with at least 2 packages (1 that depends on the other) running the command `yarn workspaces foreach run build` will only run the command for one package.

As you can see with my sample repo, you can see the expected output and the M1 Mac output
https://github.com/pudgeball/yarn-2-workspaces-bug

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: macOS 11.1 on M1 Mac Mini
 - Node version v15.3.0
 - Yarn version 2.4.0

**Additional context**

My colleagues at 1Password are not running into this issue while using the same commands on non-M1 based CPUs

**Comment by merceyz** [comment] 2020-12-31 21:26
Duplicate of https://github.com/yarnpkg/berry/issues/2074 and https://github.com/yarnpkg/berry/issues/2214

**Closed by merceyz** 2020-12-31 21:26 UTC
Labels: bug

**Comment by pudgeball** [comment] 2020-12-31 21:31
Ahhh!  Thank you!
