### ISSUE TITLE
[Bug] Yarn 2 fails to install github dependencies with preDeploy build hooks

### ISSUE THREAD

**Issue by bryanvaz** [yarnpkg/berry#2732] opened 2021-04-11 17:00 UTC
**Describe the bug**

Yarn 2 fails to `add` when using a github repo that has a Babel build as a predeploy step, while the process works fine with Yarn 1. 

From the error message, appears that Yarn 2 is looking for the output in the wrong location.

**To Reproduce**

Yarn 1 works.
```shell
mkdir y1
cd y1
yarn init
yarn add 'serverless-offline@dherault/serverless-offline'
# works \o/
```

Yarn 2 fails:
```shell
➜ mkdir y2
➜ cd y2
➜ yarn init -2
{
  name: 'y2'
}
➜ yarn --version
2.4.1
➜ yarn add serverless-offline@dherault/serverless-offline
➤ YN0000: ┌ Resolution step
➤ YN0013: │ serverless-offline@https://github.com/dherault/serverless-offline.git#commit=b55c846a0f0cdae14b320f50c1f6c8e9acb80c70 can't be found in the cache and will be fetched from GitHub
➤ YN0013: │ serverless-offline@https://github.com/dherault/serverless-offline.git#commit=b55c846a0f0cdae14b320f50c1f6c8e9acb80c70 can't be found in the cache and will be fetched from the remote repository
➤ YN0001: │ Error: serverless-offline@https://github.com/dherault/serverless-offline.git#commit=b55c846a0f0cdae14b320f50c1f6c8e9acb80c70: ENOENT: no such file or directory, rename '/private/var/folders/jy/fjx0nrnn4vv7g_1f034npxk80000gn/T/xfs-a2659a20/Successfully compiled 102 files with Babel (1559ms).
serverless-offline-6.9.0.tgz' -> '/private/var/folders/jy/fjx0nrnn4vv7g_1f034npxk80000gn/T/xfs-a2659a20/package.tgz'
➤ YN0000: └ Completed in 1m 60s
➤ YN0000: Failed with errors in 1m 60s
```

<details>
  <summary>Reproduction</summary>
 
  ```js repro
  // Sherlock reproduction. For instance:
  const installPromise = packageJsonAndInstall({
    dependencies: {
      [`serverless-offline`]: `serverless-offline@github:dherault/serverless-offline`
    }
  });
await expect(installPromise).resolves.toBeTruthy();
```
</details>

**Environment:**

- OS: OSX 11.2.3
- Node version 14.16.1
- Yarn version 2.4.1

**Comment by merceyz** [comment] 2021-04-11 18:25
Duplicate of https://github.com/yarnpkg/berry/issues/1989

**Closed by merceyz** 2021-04-11 18:25 UTC
Labels: bug
