### ISSUE TITLE
[Bug?]: yarn up replaces "link:" protocol

### ISSUE THREAD

**Issue by magnattic** [yarnpkg/berry#4096] opened 2022-02-10 00:06 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I used `yarn up "*"` to update all my dependencies and it replaced links to local folders (created with `link:`) with a package version from npm.

### To reproduce

- Create an empty project with yarn 3.
- Add this to the package.json:
```
  "dependencies": {
    "lodash": "^4.0.0",
    "src": "link:./src"
  },
```
- Run `yarn up "*"`

The package.json now contains:
```
  "dependencies": {
    "lodash": "^4.17.21",
    "src": "^1.1.2"
  },
```

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.2 - /tmp/xfs-4e00130a/node
    Yarn: 3.1.1 - /tmp/xfs-4e00130a/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
```

### Additional context

I just found a related issue, this talks about git dependencies but could potentially have the same fix: https://github.com/yarnpkg/berry/issues/1492

**Comment by merceyz** [comment] 2022-02-10 11:22
Duplicate of https://github.com/yarnpkg/berry/issues/1492

**Closed by merceyz** 2022-02-10 11:22 UTC
Labels: bug
