### ISSUE TITLE
Manifest “bin” ignored of private github packag

### ISSUE THREAD

**Issue by hylmar** [yarnpkg/berry#1796] opened 2020-09-03 17:29 UTC
I’m not sure if this is a bug, so I post it as a blank issue. Today I installed a private github package in a project using yarn 2. The package contains a “bin” command in its manifest. But to my surprise the command is ignored by Yarn. Even yarn.lock doesn’t contain the bin line next to my package, where other depencies containing a bin work as expected. Does anyone have a clue what could be the issue?

**Comment by merceyz** [comment] 2020-09-03 17:30
Duplicate of https://github.com/yarnpkg/berry/issues/1608

**Closed by merceyz** 2020-09-03 17:30 UTC
