### ISSUE TITLE
[Case Study] Grunt

### ISSUE THREAD

**Issue by segrey** [yarnpkg/berry#571] opened 2019-11-09 10:25 UTC
**What package is covered by this investigations?**

[grunt](https://www.npmjs.com/package/grunt)

**Describe the goal of the investigation**

It was a popular build tool in past. But now it's not that widespread.
Providing a current status here would be great.

**Investigation report**

```package.json
{
  "dependencies": {
    "grunt": "^1.0.4"
  }
}
```

```javascript
// Gruntfile.js
module.exports = function(grunt) {
    grunt.registerTask('default', () => {
        console.log("Hello, World");
    });
};
```

Running grunt doesn't work
```
$ yarn run grunt
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
```

Related issue: https://github.com/gruntjs/grunt/issues/1676

**Comment by arcanis** [comment] 2019-11-09 10:55
The problem is that `grunt-cli` has a dependency on `resolve@~1.1.0`, and `resolve` only supports PnP starting from 1.9.0 (we're now at 1.12.0) 🤔

We probably should add a special rule to prefer post-1.9.0 releases when valid per semver (as `~1.1.0` is). As a workaround you can add a `resolutions` entry in your `package.json` file to force Yarn to use the latest version:

```json
{
  "resolutions": {
    "grunt-cli/resolve": "^1.12.0"
  }
}
```

**Comment by segrey** [comment] 2019-11-09 13:24
@arcanis Thanks for the workaround. It works! Preferring post-1.9.0 releases would be nice indeed.
Related issue in IntelliJ / WebStorm: https://youtrack.jetbrains.com/issue/WEB-42295

**Comment by merceyz** [comment] 2022-05-22 12:36
Closing as Grunt seems to work now.

**Closed by merceyz** 2022-05-22 12:36 UTC
Labels: case study
