### ISSUE TITLE
[Feature] run local dependency binary only

### ISSUE THREAD

**Issue by segrey** [yarnpkg/berry#565] opened 2019-11-05 12:36 UTC
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

It'd be great to be able to run a local dependency binary without additional options coming from [`scripts`](https://next.yarnpkg.com/configuration/manifest#scripts).
For example, `"eslint": "eslint sources scripts"` (from [pnp-sample-app/package.json#L51](https://github.com/yarnpkg/pnp-sample-app/blob/b133036b094bd62830d1c1dc72a632df8117a41e/package.json#L51)) prevents running `yarn run eslint --print-config .eslintrc.js`
```
$ yarn run eslint --print-config .eslintrc.js
The --print-config option must be used with exactly one file name.
```
Removing the `eslint` script from the package.json fixes the error.

**Describe the solution you'd like**

Maybe a new flag for `run` command, for example `yarn run --local-dependency-binary-only eslint --print-config .eslintrc.js`?
Or, maybe a new command, for example `yarn runLocalDependencyBinary eslint  --print-config .eslintrc.js`?
Any solution would work for me.

**Describe the drawbacks of your solution**

Seems introducing a new flag or a new command shouldn't break any of existent use cases.

**Describe alternatives you've considered**

Don't see any alternatives currently. I could be wrong here.

**Additional context**

Based on previous discussion: https://github.com/yarnpkg/berry/issues/499#issuecomment-537137054
>In general, redefining commands is usually needed to specify some custom options. Then, if IDE passes the same options, it's unclear what will happen (the first wins, the latter wins or an error is thrown). I will let you know once I have a particular case.

Found the case with ESLint => created this issue.

**Comment by arcanis** [comment] 2019-11-08 12:36
Fixed in #570 🎉

**Closed by arcanis** 2019-11-08 12:36 UTC
Labels: enhancement

**Comment by segrey** [comment] 2020-01-22 21:21
Seems it doesn't work with scoped packages.
```
{
  "dependencies": {
    "@vue/cli-service": "^4.1.2",
    "karma": "^4.4.1"
  }
}
```

This command works as expected: `yarn run --binaries-only karma --help`
But this doesn't: `yarn run --binaries-only @vue/cli-service --help`

@arcanis Should I file a new issue?

**Comment by arcanis** [comment] 2020-01-22 22:28
@segrey it's not a bug, the `bin` that `@vue/cli-service` exposes is called [`vue-cli-service`](https://cdn.jsdelivr.net/npm/@vue/cli-service@4.1.2/package.json), so the right command would be:

```
yarn run --binaries-only vue-cli-service --help
```

I guess the next question is "how to know what's the name of the binary for a given package", to which the answer is "it's theoretically hard to do it perfectly because there might be multiple binaries for one package" 😛

That being said, I'll improve `yarn bin` in the next release to support a `--json` flag which will provide this information (which package provides which binary). I guess it'll be good enough in most cases (where 1 package = 1 binary).

**Comment by segrey** [comment] 2020-01-23 09:09
Ah, you're right! Sorry for the noise. IDE has capability to list all binaries provided by a package by reading its package.json, but `--json` won't hurt.
