### ISSUE TITLE
[Bug?]: yarn set version stable failed

### ISSUE THREAD

**Issue by bluelovers** [yarnpkg/berry#4784] opened 2022-08-20 18:18 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

current yarn is 1.22.19 ( form npm )

> yarn set version stable

current yarn is 3.2.2

> yarn set version classic

current yarn is 1.23.0-20220130.1630 ( from nightly or git maybe )

> yarn set version stable <== bug happen

because git version ( 1.23.0-20220130.1630 ) is old than npm ( 1.22.19 )

https://github.com/yarnpkg/yarn/blob/6db39cf0ff684ce4e7de29669046afb8103fce3d/src/cli/commands/policies.js#L119-L136

https://github.com/yarnpkg/yarn/blob/6db39cf0ff684ce4e7de29669046afb8103fce3d/src/cli/commands/policies.js#L46-L55

### To reproduce

```js repro
await yarn(`set`, `version`, `stable`);
await yarn(`set`, `version`, `classic`);
await yarn(`set`, `version`, `stable`); // <== bug happen
```

### Environment

```shell
yarn-3.2.2
yarn-1.23.0-20220130.1630
```

**Comment by arcanis** [comment] 2022-08-20 18:54
Duplicate of https://github.com/yarnpkg/berry/issues/4751

Please don't open duplicates of issues that are already missing all useful information.

**Closed** 2022-08-20 18:54 UTC
Labels: bug
