### ISSUE TITLE
[Bug?]: workspace version command crashing

### ISSUE THREAD

**Issue by npenin** [yarnpkg/berry#3478] opened 2021-09-23 09:36 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

in a workspace, I am willing to update the version to a new patch. but I am getting the following error message when I type `yarn workspace @akala/automate version patch` (@akala/automate being one of my workspaces)
```
Type Error: e.every is not a function
    at test (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:10:36997)
    at I.validateAndExecute (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:197:527)
    at async ts.run (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:211:1846)
    at async Gp.validateAndExecute (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:197:620)
    at async ts.run (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:211:1846)
    at async ts.runExit (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:211:2013)
    at async i (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:310:12327)
    at async r (/home/nicolas/dev/akala/.yarn/releases/yarn-3.0.2.cjs:310:10567)
```

### To reproduce

have a repo with at least 2 workspaces and try to bump version on it

### Environment

```shell
System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 14.17.1 - /tmp/xfs-a41a5828/node
    Yarn: 3.0.2 - /tmp/xfs-a41a5828/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
```

**Comment by merceyz** [comment] 2021-09-23 10:21
Duplicate of https://github.com/yarnpkg/berry/issues/3108

**Closed by merceyz** 2021-09-23 10:21 UTC
Labels: bug

**Comment by mxro** [comment] 2021-09-25 01:41
This happend to me as well, first with plugin-workspace-tools and then for the version one. I wonder if it would make sense to have yarn update all plugins automatically upon running `yarn set version latest` or adding this more prominently in the docs? https://yarnpkg.com/getting-started/install#updating-to-the-latest-versions

Happy to raise a feature request if required.

**Comment by merceyz** [comment] 2021-09-25 08:45
There is already a feature request for it https://github.com/yarnpkg/berry/issues/3343
