### ISSUE TITLE
[Bug?]: Cannot destructure property `withFileTypes` in `PosixFS.readdirPromise` as it is null

### ISSUE THREAD

**Issue by andywampir** [yarnpkg/berry#3236] opened 2021-08-06 07:25 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In some cases function `PosixFS.readdirPromise` in `.pnp.js` accepts `null` as second parameter, because of this occurs this error:
`TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.`

I'd tried yarn `v3.0.0`, but error still occurs.

As temporary bug fixing i'm change that function from this:
```js
async readdirPromise(p, {
	withFileTypes
} = {}) {
	return this.baseFs.readdirPromise(this.mapToBase(p), {
  		withFileTypes: withFileTypes
	});
}
```

to this:
```js
async readdirPromise(p, args) {
	if (!args) args = {};

	return this.baseFs.readdirPromise(this.mapToBase(p), {
  		withFileTypes: args.withFileTypes
	});
}

```
After this error gone.

### To reproduce

I can only show list of dependencies, because project is owned by company and i can't share it fully.
```
{
	"name": "@megacount-react/alert",
	"version": "0.1.2",
	"dependencies": {
		"@megacount-javascript/omegacount-services": "^0.30.1",
		"@megacount-react/ripple-button": "^0.3.0",
		"core-js": "^3.16.0",
		"react": "^17.0.2",
		"react-dom": "^17.0.2",
		"react-i18next": "^11.11.4",
		"react-is": "^17.0.2",
		"regenerator-runtime": "^0.13.9",
		"styled-components": "^5.3.0"
	},
	"main": "build/index.js",
	"scripts": {
		"start": "node --max-old-space-size=8192 -r ts-node/register scripts/start-dev.ts",
		"build": "del-cli build && webpack --config webpack.prod.config.ts && tsc --project tsconfig.declaration-only.json"
	},
	"files": [
		"build"
	],
	"browserslist": {
		"production": [
			">0.2%",
			"not dead",
			"not op_mini all"
		],
		"development": [
			"last 1 chrome version",
			"last 1 firefox version",
			"last 1 safari version"
		]
	},
	"devDependencies": {
		"@babel/core": "^7.15.0",
		"@babel/plugin-proposal-class-properties": "^7.14.5",
		"@babel/preset-env": "^7.15.0",
		"@babel/preset-react": "^7.14.5",
		"@babel/preset-typescript": "^7.15.0",
		"@megacount-javascript/eslint-config": "^0.1.5",
		"@pmmmwh/react-refresh-webpack-plugin": "next",
		"@types/mini-css-extract-plugin": "^2.0.1",
		"@types/node": "^16.4.12",
		"@types/prettier": "^2.3.2",
		"@types/react": "^17.0.15",
		"@types/react-dom": "^17.0.9",
		"@types/react-is": "^17.0.2",
		"@types/styled-components": "^5.1.12",
		"@types/webpack-dev-server": "^3.11.5",
		"@typescript-eslint/eslint-plugin": "^4.29.0",
		"@typescript-eslint/parser": "^4.29.0",
		"@welldone-software/why-did-you-render": "^6.2.0",
		"babel-loader": "^8.2.2",
		"babel-plugin-styled-components": "^1.13.2",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"clean-webpack-plugin": "^3.0.0",
		"css-loader": "^6.2.0",
		"del-cli": "^3.0.1",
		"dotenv": "^10.0.0",
		"eslint": "^7.32.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-import-resolver-node": "^0.3.4",
		"eslint-plugin-flowtype": "^5.9.0",
		"eslint-plugin-i18next": "^5.1.1",
		"eslint-plugin-import": "^2.23.4",
		"eslint-plugin-jsx-a11y": "^6.4.1",
		"eslint-plugin-react": "^7.24.0",
		"eslint-plugin-react-hooks": "^4.2.0",
		"eslint-webpack-plugin": "^3.0.1",
		"html-webpack-plugin": "^5.3.2",
		"json-perf-loader": "^1.1.0",
		"mini-css-extract-plugin": "^2.2.0",
		"postcss": "^8.3.6",
		"postcss-loader": "^6.1.1",
		"postcss-preset-env": "^6.7.0",
		"prettier": "^2.3.2",
		"react-refresh": "^0.10.0",
		"sass": "^1.37.5",
		"sass-loader": "^12.1.0",
		"style-loader": "^3.2.1",
		"svg-inline-loader": "^0.8.2",
		"ts-node": "^10.1.0",
		"type-fest": "^1.3.0",
		"typescript": "^4.3.5",
		"webpack": "^5.48.0",
		"webpack-cli": "^4.7.2",
		"webpack-dev-server": "^3.11.2"
	},
	"resolutions": {
		"webpack": "^5",
		"babel-plugin-styled-components": "1.13.2"
	},
	"packageManager": "yarn@2.4.2"
}
```

### Environment

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
Binaries:
    Node: 12.22.1 - ~\AppData\Local\Temp\xfs-47df2373\node.EXE
    Yarn: 2.4.2 - ~\AppData\Local\Temp\xfs-47df2373\yarn.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD

**Comment by merceyz** [comment] 2021-08-06 08:19
Duplicate of https://github.com/yarnpkg/berry/issues/3234

**Closed by merceyz** 2021-08-06 08:19 UTC
Labels: bug

**Comment by andywampir** [comment] 2021-08-06 08:21
Sorry didn't noticed that issue already exists.
