### ISSUE TITLE
[Bug] unable to add argon2

### ISSUE THREAD

**Issue by zdm** [yarnpkg/berry#1376] opened 2020-05-20 10:01 UTC
**What package is covered by this investigations?**
argon2

**Describe the goal of the investigation**
I am unable to add argon2. Previously it worked, but after node or yarn berry upgrade - stopped.
Currently this package can be installed with npm without erorrs, but with yarn - failed.
I don't know, how to debug this error, need help.

Software used:
windows 10
nodejs 14.2
yarn rc-33

**Investigation report**
```
yarn add argon2
➤ YN0000: ┌ Resolution step
➤ YN0032: │ node-addon-api@npm:2.0.0: Implicit dependencies on node-gyp are discouraged
➤ YN0060: │ @softvisio/core@workspace:. provides eslint@npm:7.0.0 with version 7.0.0 which doesn't satisfy ^5.0.0 || ^6.0.0 requested by eslint-plugin-vue@npm:6.2.2
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ argon2@npm:0.26.2 must be built because it never did before or the last one failed
➤ YN0009: │ argon2@npm:0.26.2 couldn't be built successfully (exit code 1, logs can be found here: /C:/Users/zdm/AppData/Local/Temp/xfs-d43641c8/build.log)
➤ YN0009: │ argon2@npm:0.26.2 couldn't be built successfully (exit code 1, logs can be found here: /C:/Users/zdm/AppData/Local/Temp/xfs-d43641c8/build.log)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors
```
```
# This file contains the result of Yarn building a package (argon2@npm:0.26.2)
# Script name: install

Error: Manifest not found
    at Function.find (C:\Users\zdm\.yarn\releases\yarn-berry.js:10:151748)
    at async C:\Users\zdm\.yarn\releases\yarn-berry.js:16:6508
    at async Function.openPromise (C:\Users\zdm\.yarn\releases\yarn-berry.js:16:263766)
    at async y (C:\Users\zdm\.yarn\releases\yarn-berry.js:16:5949)
    at async C:\Users\zdm\.yarn\releases\yarn-berry.js:16:5421
    at async s.mktempPromise (C:\Users\zdm\.yarn\releases\yarn-berry.js:2:5648)
    at async Object.B [as executePackageScript] (C:\Users\zdm\.yarn\releases\yarn-berry.js:16:5355)
    at async C:\Users\zdm\.yarn\releases\yarn-berry.js:42:120559
    at async s.mktempPromise (C:\Users\zdm\.yarn\releases\yarn-berry.js:2:5648)
    at async C:\Users\zdm\.yarn\releases\yarn-berry.js:42:120313
```

What Manifest? How to debug it?

**Comment by arcanis** [comment] 2020-05-20 10:09
Please make a repro w/ Sherlock - I tried using the [playground](http://yarnpkg.com/playground), it didn't reproduce.

**Comment by zdm** [comment] 2020-05-20 10:33
```
await packageJsonAndInstall({});

const output = await yarn("add", "argon2");

expect(output).not.toContain("Failed with errors");

```

**Comment by zdm** [comment] 2020-05-20 10:34
@arcanis I created repro for sherlock, but you need to run it under windows to get error.

**Comment by merceyz** [comment] 2020-05-20 10:53
Tested on Windows, runs fine. You're missing details here, create a repo that reproduces your problem if you can't with sherlock

**Comment by zdm** [comment] 2020-05-20 11:04
I just use two commands:
## fail
```
yarn init
yarn add argon2
```
## ok
```
yarn init
npm i argon2
```
What is your environment?
Node, yarn, python, vc versions?

**Comment by paul-soporan** [comment] 2020-05-20 13:19
I also tested it on Windows and I can't reproduce it.
- Yarn Version: `2.0.0-rc.33`
- Node Version: `v13.5.0`

Can you create a container with your reproduction? If 3 people can't reproduce your problem, you probably have something weird going on somewhere.

Note: Can you also try `yarn set version from sources` to see if the problem persists?

**Comment by zdm** [comment] 2020-05-20 13:29
The problem is in node v14.xx.
I tried with node v13.3 - it works.

**Comment by paul-soporan** [comment] 2020-05-20 13:45
Can you also try with Yarn from master? (`yarn set version from sources`)

**Comment by zdm** [comment] 2020-05-20 14:05
Unable to update yarn from sources, it is freezes and nothing happening.
```
yarn set version from sources
➤ YN0000: Cloning the remote repository

  $ git init C:\Users\zdm\AppData\Local\Temp\yarnpkg-sources
  $ git remote add origin https://github.com/yarnpkg/berry.git
  $ git fetch origin master
  $ git reset --hard FETCH_HEAD

➤ YN0000: Building a fresh bundle

Usage Error: Unrecognized or legacy configuration settings found: changesetIgnorePatterns - run "yarn config -v" to see the list of settings supported in Yarn (in /C:/Users/zdm/AppData/Local/Temp/yarnpkg-sources/.yarnrc.yml)

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
➤ YN0001: Error: Child "yarn" exited with exit code 1
    at ChildProcess.<anonymous> (C:\Users\zdm\.yarn\releases\yarn-berry.js:10:394568)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.e.emit (C:\Users\zdm\.yarn\releases\yarn-berry.js:16:297811)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
➤ YN0000: Failed with errors
```

**Comment by merceyz** [comment] 2020-06-15 16:02
Closing as we can't reproduce your issue

**Closed by merceyz** 2020-06-15 16:02 UTC
Labels: bug, can't repro
