### ISSUE TITLE
[Bug?]: Script glob pattern path errors after yarn upgrade

### ISSUE THREAD

**Issue by fossbrandon** [yarnpkg/berry#3720] opened 2021-11-10 18:19 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I had a few projects that were utilizing older versions of yarn (yarn v1 and yarn v2.4.1). These projects include scripts for various tasks such as linting and cleaning the repo. For example, my cleaning script at the root of the repo looks like this: `"clean": "rimraf ./**/node_modules"`.

Before upgrading, this script ran fine without any issues, but after upgrading yarn to v3.1.0, I get this issue:

```
PS C:/user/repo> yarn clean
The command line is too long.
```

If I remove the glob pattern it works fine for the root `node_modules` folder, but I expect the glob pattern to be able to handle any number of nested `node_modules` folders like previous versions do.

### To reproduce

Setup a React app with yarn v 3.1.0 specifying `nodeLinker: node-modules` and add the following script to the `package.json` file in the root of the repo. Run the script with `yarn clean` and it will produce the error output `The command line is too long`.

`package.json`

```json
{
  "name": "Example",
  "scripts": {
    "clean": "rimraf ./**/node_modules",
}
```

`.yarnrc.yml`

```yml
nodeLinker: node-modules
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  Binaries:
    Node: 16.9.1 - ~\AppData\Local\Temp\xfs-f2569795\node.CMD
    Yarn: 3.1.0 - ~\AppData\Local\Temp\xfs-f2569795\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: 26.6.3 => 26.6.3
```

**Comment by merceyz** [comment] 2021-11-10 19:15
Duplicate of https://github.com/yarnpkg/berry/issues/1792

**Closed by merceyz** 2021-11-10 19:15 UTC
Labels: bug

**Comment by fossbrandon** [comment] 2021-11-10 19:35
Thanks for pointing me to that issue, the suggested change there fixed the error!

I changed the `package.json` script from `"clean": "rimraf ./**/node_modules"` to `"clean": "rimraf './**/node_modules'"`
