### ISSUE TITLE
Cannot destructure property `withFileTypes` of 'undefined' or 'null'. ERR!     at URLFS.readdirPromise

### ISSUE THREAD

**Issue by jerrynim** [yarnpkg/berry#3237] opened 2021-08-06 09:48 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hello, i'm tring to use yarn berry with storybook. when run start-storybook
this error make build fail

Error Message
```
info @storybook/react v6.3.6
info 
info => Loading presets
WARN We found no files matching any of the following globs:
WARN 
WARN ./src
WARN 
WARN Maybe your glob was invalid?
WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
info => Using PostCSS preset with postcss@7.0.36
info => Using default Webpack4 setup
13% building 25/34 modules 9 active ...-user/Desktop/repo/.yarn/cache/airbnb-js-shims-npm-2.2.1-431dc070fb-bdd96e4cac.zip/node_modules/airbnb-js-shims/target/es2018.jsWARN Force closed preview build
ERR! TypeError: Cannot destructure property `withFileTypes` of 'undefined' or 'null'.
ERR!     at URLFS.readdirPromise (/Users/jerrynim-user/Desktop/repo/.pnp.cjs:49130:27)
ERR!     at /Users/jerrynim-user/Desktop/repo/.pnp.cjs:52327:20
ERR!     at processTicksAndRejections (internal/process/task_queues.js:75:11)
ERR!  TypeError: Cannot destructure property `withFileTypes` of 'undefined' or 'null'.
ERR!     at URLFS.readdirPromise (/Users/jerrynim-user/Desktop/repo/.pnp.cjs:49130:27)
ERR!     at /Users/jerrynim-user/Desktop/repo/.pnp.cjs:52327:20
ERR!     at processTicksAndRejections (internal/process/task_queues.js:75:11) {
ERR!   stack: "TypeError: Cannot destructure property `withFileTypes` of 'undefined' or 'null'.\n" +
ERR!     '    at URLFS.readdirPromise (/Users/jerrynim-user/Desktop/repo/.pnp.cjs:49130:27)\n' +
ERR!     '    at /Users/jerrynim-user/Desktop/repo/.pnp.cjs:52327:20\n' +
ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:75:11)'
ERR! }
```

and in pnp.cjs
```
  async readdirPromise(p, {
    withFileTypes
  } = {}) {
    return this.baseFs.readdirPromise(this.mapToBase(p), {
      withFileTypes: withFileTypes
    });
  }

  readdirSync(p, {
    withFileTypes
  } = {}) {
    return this.baseFs.readdirSync(this.mapToBase(p), {
      withFileTypes: withFileTypes
    });
  }
```

destructure property in empty object  looks weird

### To reproduce

  async readdirPromise(p, {
    withFileTypes
  } = {}) {
    return this.baseFs.readdirPromise(this.mapToBase(p), {
      withFileTypes: withFileTypes // << i think this should be undefined
    });
  }

### Environment

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.13.0 - /private/var/folders/95/kf79g5gx6bj6nz7j_gkl7jq80000gp/T/xfs-029a4da4/node
    Yarn: 3.0.0 - /private/var/folders/95/kf79g5gx6bj6nz7j_gkl7jq80000gp/T/xfs-029a4da4/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm

**Comment by merceyz** [comment] 2021-08-06 09:53
Duplicate of https://github.com/yarnpkg/berry/issues/3234

**Closed by merceyz** 2021-08-06 09:53 UTC
Labels: bug
