### ISSUE TITLE
[Bug?]: VS Code TS PnP integration appears to be broken

### ISSUE THREAD

**Issue by rcketscientist** [yarnpkg/berry#3788] opened 2021-11-23 19:04 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After following the direction for setting up a project with VS Code typescript and pnp the IDE cannot find modules, for example:

Cannot find module 'react' or its corresponding type declarations.

### To reproduce

https://github.com/rcketscientist/vs-code-pnp-test

Same behavior with a project from scratch:

1. yarn init
2. yarn add -D typescript @yarnpkg/sdks
3. yard add react
2. yarn tsc init
3. yarn sdks vscode

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 16.13.0 - C:\Users\ANTHON~1.MAN\AppData\Local\Temp\xfs-33e4d110\node.CMD
    Yarn: 3.1.0 - C:\Users\ANTHON~1.MAN\AppData\Local\Temp\xfs-33e4d110\yarn.CMD  
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

VS Code: 

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by merceyz** [comment] 2021-11-23 19:34
Duplicate of https://github.com/yarnpkg/berry/issues/3722

**Closed by merceyz** 2021-11-23 19:34 UTC
Labels: bug
