### ISSUE TITLE
[Bug?]: Plug'n'Play causes Jest to detect open handles

### ISSUE THREAD

**Issue by ziggy6792** [yarnpkg/berry#3719] opened 2021-11-10 11:03 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After migrating to Yarn v2 with `pnp` I get warnings when I run my jest tests 
`Jest has detected the following 28 open handles potentially keeping Jest from exiting:`

```
  ●  ZLIB

      35991 |           });
      35992 |         } else {
    > 35993 |           const decompressedData = external_zlib_default().inflateRawSync(data);
            |                                                            ^
      35994 |           this.fileSources.set(index, decompressedData);
      35995 |           return decompressedData;
      35996 |         }

      at ZipFS.getFileSource (../../.pnp.cjs:35993:60)
      at ZipFS.readFileBuffer (../../.pnp.cjs:36337:17)
      at ZipFS.readFileSync (../../.pnp.cjs:36322:23)
      at ../../.pnp.cjs:37222:20
      at ../../.pnp.cjs:37338:58
      at ZipOpenFS.getZipSync (../../.pnp.cjs:37497:14)
      at ZipOpenFS.makeCallSync (../../.pnp.cjs:37338:17)
      at ZipOpenFS.readFileSync (../../.pnp.cjs:37210:17)
      at VirtualFS.readFileSync (../../.pnp.cjs:34551:26)
      at PosixFS.readFileSync (../../.pnp.cjs:34551:26)
      at URLFS.readFileSync (../../.pnp.cjs:34551:26)
      at Object.<anonymous> (../../.yarn/__virtual__/@typegoose-typegoose-virtual-49617552b9/0/cache/@typegoose-typegoose-npm-9.0.1-fea7ea2ec0-8a3a767513.zip/node_modules/@typegoose/typegoose/src/typegoose.ts:21:1)
      at Object.<anonymous> (../lambda-gq-resolver/src/resolvers/user.resolver.test.ts:2:1)
 ```
 
 Seems to be the issue as reported [here](https://issueexplorer.com/issue/yarnpkg/berry/3376)

### To reproduce

I can create a sample repo if needed.
However one have already been provided [here](https://issueexplorer.com/issue/yarnpkg/berry/3376) and a sample repo [here](https://github.com/WesCossick/reproduce-zlib-open-handle)

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.3.0 - /private/var/folders/3g/_cc094fn55ldf2zjstjbq5hr0000gn/T/xfs-4b018e45/node
    Yarn: 3.1.0 - /private/var/folders/3g/_cc094fn55ldf2zjstjbq5hr0000gn/T/xfs-4b018e45/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
```

### Additional context

I am very sorry if you are already working on this issue but I couldn't find it under https://github.com/yarnpkg/berry/issues

Also I am not sure if this is a problem with yarn or a problem with jest

**Comment by arcanis** [comment] 2021-11-10 11:06
Duplicate of https://github.com/yarnpkg/berry/issues/3376

**Closed by arcanis** 2021-11-10 11:06 UTC
Labels: bug
