### ISSUE TITLE
[Bug?]: Yarn 3+ errors silently on memory constrained containers/systems

### ISSUE THREAD

**Issue by siosphere** [yarnpkg/berry#5065] opened 2022-11-15 20:11 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When running a yarn install inside of a docker container, it continually failed at different packages in my yarn install, but the exit code was 0, and no error was displayed.

After debugging for a while, I figured out it was due to low memory, but there is no `Killed` message, or any message to point to what the issue was.

I would expect a non successful error code, pointing to a process being killed due to OOM

### To reproduce

Start a docker container with a constrained amount of memory:
```
docker run -it -w /app -m 128m --rm node:16 sh
```
Switch to yarn berry, and init a repo, and then attempt to add webpack as dev dependency:
```
yarn set version berry
yarn init
yarn add --dev webpack
```
The output will stop in the middle of fetching packages, but the exit code will be 0:
```
echo $?
```
![](https://i.gyazo.com/8153dd29d39570377fddab4010d8abc3.png)

No updates will have been made to the package.json, as it errored silently

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (5) arm64 unknown
  Binaries:
    Node: 16.18.1 - /tmp/xfs-d6f3346f/node
    Yarn: 3.2.4 - /tmp/xfs-d6f3346f/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

**Comment by arcanis** [comment] 2022-11-15 21:20
The process is killed by the kernel; neither Yarn nor even Node.js can do anything about it as far as I know (although it's surprising the exit code is 0 - usually it's 143 🤔)

**Comment by merceyz** [comment] 2022-11-15 21:24
It's a bug in Yarn 1, if you use Corepack (`corepack enable`) it doesn't reproduce.
Duplicate of https://github.com/yarnpkg/berry/issues/3996

**Closed by merceyz** 2022-11-15 21:24 UTC
Labels: bug, not a bug, waiting for feedback

**Comment by siosphere** [comment] 2022-11-15 21:31
> The process is killed by the kernel; neither Yarn nor even Node.js can do anything about it as far as I know (although it's surprising the exit code is 0 - usually it's 143 🤔)

For other processes, other than yarn, when they hit that limit, they do get a non-zero exit code, and usually "Killed" is output in the terminal. It seems specific to yarn, that there is no error code, and no output to inform you that it was killed due to OOM.

For example:
```docker run -it -w /app -m 16m --rm node:16 sh
# npm add webpack
Killed
# echo $?
137
# 
```

So to me, it seems the bug is still specific to Yarn, somehow swallowing the error code and output.
