### ISSUE TITLE
[Bug?]: Yarn fails to add a package from a GitHub repository URL

### ISSUE THREAD

**Issue by stephenhmarsh** [yarnpkg/berry#5000] opened 2022-10-28 22:57 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn fails to add a package from a GitHub repository URL

```
➜  web git:(main) ✗ yarn add @metmuseum/marble@https://github.com/metmuseum/marble.git
➤ YN0000: ┌ Resolution step
➤ YN0013: │ @metmuseum/marble@https://github.com/metmuseum/marble.git#commit=afc4e14cf962f119771f030a1b5bd584094d4182 can't be found in the cache and will be fetched from GitHub
➤ YN0013: │ @metmuseum/marble@https://github.com/metmuseum/marble.git#commit=afc4e14cf962f119771f030a1b5bd584094d4182 can't be found in the cache and will be fetched from the remote repository
➤ YN0001: │ Error: @metmuseum/marble@https://github.com/metmuseum/marble.git#commit=afc4e14cf962f119771f030a1b5bd584094d4182: Assertion failed: Unsupported workflow
    at /Users/stephen/dev/met-js/web/.yarn/releases/yarn-3.2.4.cjs:422:1542
    at async $t.mktempPromise (/Users/stephen/dev/met-js/web/.yarn/releases/yarn-3.2.4.cjs:377:68868)
    at async /Users/stephen/dev/met-js/web/.yarn/releases/yarn-3.2.4.cjs:419:14
    at async $t.mktempPromise (/Users/stephen/dev/met-js/web/.yarn/releases/yarn-3.2.4.cjs:377:68868)
    at async /Users/stephen/dev/met-js/web/.yarn/releases/yarn-3.2.4.cjs:414:3013
➤ YN0000: └ Completed in 38s 419ms
➤ YN0000: Failed with errors in 38s 420ms
```

### To reproduce

- [ ] `corepack enable`
- [ ] `yarn set version stable` (=> 3.2.4)
- [ ] `yarn add @metmuseum/marble@https://github.com/metmuseum/marble.git`

### Environment

```shell
➜  web git:(main) ✗ yarn dlx -q envinfo --preset jest

  System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.10.0 - /private/var/folders/50/qp97s0zs165fh_1mrzw4n4lh0000gn/T/xfs-26e82e26/node
    Yarn: 3.2.4 - /private/var/folders/50/qp97s0zs165fh_1mrzw4n4lh0000gn/T/xfs-26e82e26/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
```

**Comment by stephenhmarsh** [comment] 2022-10-28 23:04
Oh, sorry I think I made a duplicate of: https://github.com/yarnpkg/berry/issues/3169

I thought I searched `Assertion failed: Unsupported workflow` first but I guess not or maybe I was looking at the legacy Yarn repo.

**Comment by merceyz** [comment] 2022-10-29 12:01
Yeah, duplicate of https://github.com/yarnpkg/berry/issues/3169

**Closed by merceyz** 2022-10-29 12:01 UTC
Labels: bug
