### ISSUE TITLE
[Bug?]: typescript 4.4.2 not working with yarn sdk in vscode

### ISSUE THREAD

**Issue by LOLBRUHNICE** [yarnpkg/berry#3372] opened 2021-09-01 08:02 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I upgrade typescript version of my project to 4.4.2, vscode cant detect any dependencies installed / everything in @types/node (such as process), but when I degrade to 4.3.x, it works again

### To reproduce

in description

### Environment

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Binaries:
    Node: 16.8.0 - C:\Users\ADMINI~1\AppData\Local\Temp\xfs-8b0d29d3\node.CMD
    Yarn: 3.0.1 - C:\Users\ADMINI~1\AppData\Local\Temp\xfs-8b0d29d3\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD

**Comment by merceyz** [comment] 2021-09-01 08:21
Duplicate of https://github.com/yarnpkg/berry/issues/3350

**Comment by merceyz** [comment] 2021-09-01 08:21
The fix is to run the following command
```sh
yarn set version canary && yarn
```

**Closed by merceyz** 2021-09-01 08:21 UTC
Labels: bug
