### ISSUE TITLE
[Bug] No longer works with snowpack (p.match is not a function) because yarn does not support file URLs in fs.readFile

### ISSUE THREAD

**Issue by alubbe** [yarnpkg/berry#2229] opened 2020-12-10 09:23 UTC
**Describe the bug**

See the bug report at https://github.com/snowpackjs/snowpack/discussions/1878

This might also be related to https://github.com/yarnpkg/berry/issues/1889

In short, we think snowpack can no longer be used with yarn 2 because its fs.readFile implementation does not support file URLs, like node's implementation does.

Are we understanding this issue correctly? Is there some way to work around it or is this something that might get fixed by yarn itself?

With a little bit of guidance we could also try to fix it ourselves and submit a PR, any pointers would be appreciated.

**Comment by merceyz** [comment] 2020-12-10 10:02
Duplicate of https://github.com/yarnpkg/berry/issues/899

**Closed by merceyz** 2020-12-10 10:02 UTC
Labels: bug

**Comment by alubbe** [comment] 2021-01-05 11:24
I can confirm that snowpack works with the latest master 👍

**Comment by arcanis** [comment] 2021-01-05 11:32
Nice! By any chance, would you be interested to add a Snowpack E2E test to [our battery](https://github.com/yarnpkg/berry/tree/master/.github/workflows)? Would be great to early catch other potential regressions.

**Comment by alubbe** [comment] 2021-01-07 10:58
Sure thing - here it is: https://github.com/yarnpkg/berry/pull/2341
