### ISSUE TITLE
[Bug] VSCode jump to definition fails

### ISSUE THREAD

**Issue by xealot** [yarnpkg/berry#937] opened 2020-02-11 22:26 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

When using code navigation features in VSCode any class/object that's in a file which resides in the `.yarn/cache` area fails to load. 

It's often extremely useful to see the typings or the sources for imported 3rd party code. Or even code of your own from another project.

```
Unable to open 'environment.d.ts': 
Unable to read file '/<project_root>/.yarn/$$virtual/@ihm-sdk-virtual-0b018953b6/0/cache/@ihm-sdk-npm-8.1.7-3deea91f6a-2.zip/node_modules/@ihm/sdk/tools/environment.d.ts' 
(Error: Unable to resolve non-existing file '/<project_root>/.yarn/$$virtual/@ihm-sdk-virtual-0b018953b6/0/cache/@ihm-sdk-npm-8.1.7-3deea91f6a-2.zip/node_modules/@ihm/sdk/tools/environment.d.ts').
```

**To Reproduce**

1. Setup VSCode according to the instructions on yarnpkg.com
2. Install dependencies
3. Use "Jump to Definition" function in VSCode.

**Environment if relevant (please complete the following information):**

 - OS: [MacOS]
 - Node version [12]
 - Yarn version [2.0.0.0-rc.29]

**Comment by arcanis** [comment] 2020-02-11 22:35
Duplicate of #806

**Closed** 2020-02-12 00:01 UTC
Labels: bug

**Comment by xealot** [comment] 2020-02-12 00:04
Indeed, root issue is here: https://github.com/microsoft/vscode/issues/75559

**Comment by danreg** [comment] 2020-07-02 13:31
Also does not work in Visual Studio (not vscode) Any ideas? It can't even find any type definitions from node modules folder because they are not there.

**Comment by ferm10n** [comment] 2021-07-25 04:51
@arcanis I'm not sure this is a duplicate, Also the error message is slightly different "Unable to resolve non-existing file"

I'm currently using the vscode-zipfs extension and getting this error, and not totally sure how to debug or tell if the extension is being invoked. Sometimes it works though, haven't nailed down why yet.

**Comment by merceyz** [comment] 2021-07-25 15:14
Please open a new issue with a reproduction
