### ISSUE TITLE
[Bug]: yarn workspaces foreach: Unknown Syntax Error: Command not found

### ISSUE THREAD

**Issue by trusktr** [yarnpkg/berry#5798] opened 2023-10-17 09:13 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

```
PS D:\src\lume+lume> yarn workspaces foreach run build
Unknown Syntax Error: Command not found; did you mean:

$ yarn workspaces list [--since] [-R,--recursive] [--no-private] [-v,--verbose] [--json]
While running workspaces foreach run build
```

### To reproduce

In PowerShell:

```
git clone git@github.com:lume/lume.git
git checkout d690d0549afeb257c98c5960caa7e3b61ade713c
git submodule update --init
yarn workspaces foreach run build
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 20.5.0 - ~\AppData\Local\Temp\xfs-c41552f2\node.CMD
    Yarn: 3.6.4 - ~\AppData\Local\Temp\xfs-c41552f2\yarn.CMD
    npm: 9.8.0 - D:\Program Files (x86)\nodejs\npm.CMD
```

**Comment by merceyz** [comment] 2023-10-17 09:16
Duplicate of https://github.com/yarnpkg/berry/issues/5767

**Closed by merceyz** 2023-10-17 09:16 UTC
Labels: bug
