### ISSUE TITLE
[Bug?]: Module not found: Can't resolve '@sentry/utils/esm/buildPolyfills'

### ISSUE THREAD

**Issue by HoJin9622** [yarnpkg/berry#5489] opened 2023-06-06 15:03 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Sentry gets an error when using yarn berry.
There was no problem with the version of yarn 1.x.x, but there is a problem with berry.
When entering the page, the error `Can't resolve '@sentry/utils/esm/buildPolyfills'` appears.

### To reproduce

[Reproduction app](https://github.com/HoJin9622/next-sentry-error-example)

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.1 - /private/var/folders/0l/pfyzs64132zg_wwf69czqrnw0000gn/T/xfs-5036e623/node
    Yarn: 3.6.0 - /private/var/folders/0l/pfyzs64132zg_wwf69czqrnw0000gn/T/xfs-5036e623/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
```

### Additional context

https://github.com/getsentry/sentry-javascript/issues/8180

_No response_

**Comment by Huespal** [comment] 2023-06-08 07:10
Hello.
Our team is experiencing the same.
Do you have a date when it will be fixed?
Thank you.

**Comment by merceyz** [comment] 2023-06-08 07:44
This is not a bug in Yarn and is behaving as expected.

Something in your build pipeline is injecting unresolved imports to `@sentry/utils` which requires you to declare it as a dependency to access it.
Since that isn't a great developer experience the preferred solution is for the import to be resolved before getting injected.

Console output in debug mode:
```console
$ PNP_DEBUG_LEVEL=1 yarn build

Your application tried to access @sentry/utils, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

  In ← '@sentry/utils'
  In ← '/app/next-sentry-error-example/src/app/'
  In ← { considerBuiltins: false }
```

> There was no problem with the version of yarn 1.x.x, but there is a problem with berry.

That's because Yarn 1.x hoists `@sentry/utils` so it's accessible to your project, Berry can do that as well if you run

```sh
yarn config set nodeLinker node-modules
yarn
```

See https://yarnpkg.com/advanced/rulebook/#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies for more information on hoisting.

**Closed by merceyz** 2023-06-08 07:44 UTC
Labels: bug
