### ISSUE TITLE
[Feature] yarn install should install missing plugins

### ISSUE THREAD

**Issue by rightaway** [yarnpkg/berry#4464] opened 2022-05-17 06:52 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Some projects don't include the plugins directory or even the whole .yarn directory in their git repo. When you run any yarn command you get an error. It could also happen if the plugins directory or .yarn directory gets deleted for some reason.

```
Internal Error: Cannot find module '.yarn/plugins/@yarnpkg/plugin-outdated.cjs'
Require stack:
- yarn/3.2.1/yarn.js
Require stack:
- yarn/3.2.1/yarn.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/usr/lib/node_modules/corepack/dist/vcc.js:170:20) 
    at wJ (yarn/3.2.1/yarn.js:395:12617) 
    at Ng (yarn/3.2.1/yarn.js:395:13471) 
    at k (yarn/3.2.1/yarn.js:396:21561)
    at Function.find (yarn/3.2.1/yarn.js:396:22173)
    at async i (yarn/3.2.1/yarn.js:449:11336)
    at async r (yarn/3.2.1/yarn.js:449:10914)
```

**Describe the solution you'd like**

`.yarnrc.yml` already has all the information it needs to install all plugins. It should do that when running `yarn install` so that anyone setting up a new project gets all the plugins they need and not an error.

It's like how corepack uses packageManager in package.json to automatically get that version of yarn when it doesn't exist. It wouldn't make much sense for it to fail and say that it can't find that version of yarn when it has all the information it needs to install it.

**Describe the drawbacks of your solution**

There shouldn't be a problem for people who already have the plugins installed since it can check which ones exist and skip those.

**Describe alternatives you've considered**

I could parse the yarnrc file and run `yarn plugin import` for each of them but it makes sense for it to be in yarn so everyone can have a smoother experience working with a new project. It also makes it more reliable when onboarding new contributors.

**Comment by RDIL** [comment] 2022-05-19 23:03
In Yarn 4 (currently on master branch), all the default plugins are built directly into the Yarn binary, so this shouldn’t be too much of an issue after that.

**Comment by rightaway** [comment] 2022-05-20 07:33
@RDIL Can https://github.com/mskelton/yarn-plugin-outdated be included as a default plugin? Yarn 1 had this feature but it was removed with no replacement built in.

> so this shouldn’t be too much of an issue after that.

This will still be an issue for all the plugins that aren't default. It will improve the developer experience and doesn't have any major disadvantage.

**Comment by arcanis** [comment] 2022-05-20 07:50
It feels like a good idea - if a package is missing and the `spec` field points to a URL, auto-import it 🤔

The tricky part is that we'd want the http queries to go through `httpUtils` for consistency, which requires a `Configuration` instance, which currently requires loading the plugins (in order to know what are the configuration settings). We could however imagine that the builtin settings are extracted before the third-party ones, which would be enough for `httpUtils` to work.

**Comment by Eeemil** [comment] 2022-05-23 09:33
I just created a duplicate of this, https://github.com/yarnpkg/berry/issues/4479 , this affects me too :laughing: 

I'd also like to point out that the `plugins:`-field in `.yarnrc.yml` is undocumented https://yarnpkg.com/configuration/yarnrc

Also it would be nice to be able to pin the version of a plugin in `yarnrc.yml`, so that nothing breaks between builds if a plugin is updated at the remote path.

**Comment by darksinge** [comment] 2022-06-10 21:31
What is the recommended workaround until this gets implemented? I keep feeling like I'm missing something obvious but haven't been able to find an answer anywhere. I've started looking into yarn because it has better support for workspaces than npm, but this has become a point of friction. It seems if I add a plugin, then remove `.yarn`, then any subsequent `yarn` commands fail with:
```
Internal Error: Cannot find module '/path/to/project/.yarn/plugins/@yarnpkg/<some_plugin>.cjs'
Require stack:
- /Users/craig/.yarn/releases/yarn-3.2.1.cjs
...
```

The only way I've been able to work around this is by removing the `plugins` array from `.yarnrc.yml`, then running `yarn`, then running `yarn plugin import ...` for each plugin I just removed. That seems... wrong?

I'm new to yarn, so maybe there's something going completely over my head 😅. Would really appreciate some guidance.

**Comment by RDIL** [comment] 2022-06-11 02:15
@darksinge you're currently meant to keep .yarn, and commit parts of it to version control.

**Comment by arcanis** [comment] 2022-06-13 12:57
> @RDIL That shouldn't be a requirement. package.json, yarn.lock and .yarnrc.yml have all the information needed to populate .yarn.

Right, but at the moment it is, so it's a valid answer to "what is the recommended workaround until this gets implemented".

**Closed** 2022-10-14 08:45 UTC
Labels: enhancement, help wanted

**Comment by landsman** [comment] 2023-07-08 16:50
@darksinge Good workaround, but definitely not the final solution for me.

> !.yarn/plugins

I really don't want to add version control for 3rd-party code that can be downloaded from external repository. That's anti-pattern for dependency managers 🤦

**Comment by TheEhsanSarshar** [comment] 2023-11-19 17:09
as a workaround I ( I mean GPT ) created this script to read plugins from `.yarnrc.yml` and install them 😛
btw before running this script first comment plugins section
```js
const fs = require('fs');
const { spawnSync } = require('child_process');

const boboYml = fs.readFileSync('.yarnrc.yml', 'utf8');

const pluginLines = boboYml.match(/spec: '([^']+)'/g);
const pluginNames = pluginLines.map(line => line.match(/spec: '([^']+)'/)[1]);

// Install each plugin
pluginNames.forEach(pluginName => {
    console.log(`Installing plugin: ${pluginName}`);
    const result = spawnSync('yarn', ['plugin', 'import', pluginName], { stdio: 'inherit' });

    if (result.status !== 0) {
        console.error(`Failed to install plugin: ${pluginName}`);
        console.error(result.stderr.toString());
        process.exit(1);
    }
});
```
