### ISSUE TITLE
[Feature] Removing .yarn folder should yield an understandable error

### ISSUE THREAD

**Issue by scarlac** [yarnpkg/berry#1733] opened 2020-08-21 02:09 UTC
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Removing `node_modules` folder is NodeJS equivalent of "have you tried restarting your pc"? 
I daily see this recommended in discussions, on forums, in offices environments.

So if a user tries to do the equivalent of:
```
rm -rf node_modules
```
The natural assumption would be:
```
rm -rf .yarn
```

Which fully screws up their entire project, including yarn, putting them into an unusable state:
```
18:48:38 ~/projects/myproject ⚡️ yarn
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module '/Users/scarlac/projects/myproject/.yarn/releases/yarn-2.1.1.cjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

The user now has normal way to recover, and they have to resort to git or backups. This is a terrible experience, and it's often not an issue beyond configuration to remove dot-folders with other tools. With Yarn 2 the story is now that it's fatal. There is no clear yarn command that leads to recovery (`yarn doctor` will cause the same error).

**Describe the solution you'd like**

The issue is that the binary is shipped with the configuration folder. Given this design decision, the `yarn` command should either:
1. Still function
2. Display a human-readable error, saying why it won't function
3. Display a human-readable error, saying how the human can fix the issue
4. Fix itself and display a warning

Currently, we are bleeding the out onto the screen, showing internal javascript.

Examples of error message that may be helpful:
- `Yarn binary not found (.yarn/releases/yarn-2.1.1.cjs). Did you remove it?`
- `Yarn2 needs the .yarn folder to function. Please run XXXX to generate it from scratch`
- `Local yarn binary not found. .yarn/ folder may not be removed like node_modules/. Run XXXX to generate it`

**Describe the drawbacks of your solution**

Increases code complexity slightly.

**Describe alternatives you've considered**

Automatically re-generating the `.yarn` folder from scratch with the latest binary would be **ideal** but I am not sure you guys agree (as I imagine the decision to put the binary next to the cache was an elaborate informed choice and removal of .yarn was considered to be 'wontfix' regardless).

**Comment by scarlac** [comment] 2020-08-25 02:47
@arcanis Provided that you use git and that you have it set up in git, which I did not have as I was trying to migrate. 
The file not found can be figured out if one bothers to read the entire thing but the solution isn't obvious.
I am merely asking for an error message that is solution oriented kinda like ~"This is what went wrong. Here's how to fix it".

Yarn2 is already a hard sell given the defaults. I'd just like users to be able to not have to understand the internals to recover from a fairly easily encountered situation.

I'll leave it at that. If you feel it's a wontfix, feel free to mark it as such.

**Comment by lehni** [comment] 2020-11-03 19:37
I'm experiencing the same problem as @FallingSnow: With `nodeLinker: node-modules`, I keep getting this error, and even resetting `.yarn` does not seem to help

**Comment by merceyz** [comment] 2020-11-03 19:45
@lehni Unrelated to the topic of this issue, please open a seperate issue with a reproduction

**Comment by cdestiawan** [comment] 2020-11-19 02:23
@paul-soporan 
> We've made it clear that the .yarn/ folder contains the Yarn 2 binary + plugins. Why would anyone blindly rm -rf the entire .yarn/ folder? Did you actually want to only clear the cache? (rm -rf .yarn/cache aka yarn cache clean) I don't see any reason why anybody would want to remove absolutely everything.
Yes, I was one of them, and now I can't even use yarn 2 (and even yarn 1) anymore. Don't know how to use it again. Yarn should have a way to recover itself, in case if there are some stupid user (like me) removing .yarn folder by accident. And now I switch to pnpm, instead of yarn.

**Comment by devoto13** [comment] 2020-11-19 06:43
@cdestiawan I assume `yarn set version berry` will restore the executable if it was deleted by accident.

**Comment by merceyz** [comment] 2020-11-21 19:49
I'll close this as there is nothing we can do about it from Yarn V2's side.

---

Until it has been released with Node (if it gets accepted) you can use https://github.com/nodejs/corepack to handle this.
```sh
npm uninstall yarn -g
npm install corepack -g
```
Add this to your `package.json` instead of adding the binary locally
```
  "packageManager": "yarn@2.3.3",
```

**Closed by merceyz** 2020-11-21 19:49 UTC
Labels: enhancement

**Comment by dorianmariefr** [comment] 2021-12-13 20:59
went back to yarn 1, not going to check in a large js file in my repo

**Comment by wbarksdale** [comment] 2022-01-14 07:18
> @cdestiawan I assume `yarn set version berry` will restore the executable if it was deleted by accident.

I see the same error when attempting to recover this way :(

Seem to be stuck here having not wanted to commit .yarn to my repo, and then removing it thinking it was similar to removing node_modules just as original issue descirbed

**Comment by amoliski** [comment] 2022-02-16 16:17
Not sure why the maintainers in this thread are acting like it's some impossibility to rebuild the folder, they have to build it in the first place, don't they? 

Instead of running `yarn set version berry` in a new project and copying the folder over, just delete the line "yarnPath: .yarn/releases/yarn..." From your .yarnrc.yml file and rerun `yarn set version berry` again.

**Comment by Austio** [comment] 2022-05-02 04:13
Echoing here, but same.  I understand the decision here but is not the path of least surprise for me.  So used to removing node_modules due to npm instability and didn't think that clearning the .yarn folder would cause yarn to be unusable.

**Comment by syrepol** [comment] 2022-05-19 08:18
The this whole "yarn pnp"  thing works right now is just awful. You should've stuck with the way yarn v1 worked. Definitely gonna switch to something else

**Comment by pencilcheck** [comment] 2022-08-08 00:39
wow, removing .yarn completely broke yarn for me. Can't do any command from yarn anymore, this sucks. I really can't believe yarn is doing this, making a very fundamental programmer error.
