### ISSUE TITLE
[Bug] Usage Error: Invalid version descriptor "berry"

### ISSUE THREAD

**Issue by njj** [yarnpkg/berry#1265] opened 2020-04-28 19:40 UTC
**Describe the bug**

When yarn is already set to version 2+ and you try to run `yarn set version berry` it produces and error. Invalid version descriptor "berry".

**To Reproduce**

```
$ yarn set version berry
$ yarn -v
$ 2.0.0-rc.32
$ yarn set version berry
$ Usage Error: Invalid version descriptor "berry"
$ yarn set version <version>
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Yarn version: berry

**Comment by paul-soporan** [comment] 2020-04-28 19:49
Duplicate of #1130 and not actually a bug. Support for ranges has been removed in #1114, as the former implementation was limited by the GitHub API.

**Closed by paul-soporan** 2020-04-28 19:49 UTC
Labels: bug

**Comment by arcanis** [comment] 2020-04-28 19:54
Note that ranges were removed, but I've added `berry` back in master as an alias for `latest` (since `latest`, like other branch names, doesn't require to query the full tag list).

**Comment by paul-soporan** [comment] 2020-04-28 20:08
@arcanis Didn't know that you've added `berry` back in master, speaking of which, I couldn't find the code responsible for it 😄 (searched because I was curious how I managed to miss it): https://github.com/yarnpkg/berry/blob/1d5bbb1a8731ef8b77c28ccb22fb2a464870a38f/packages/plugin-essentials/sources/commands/set/version.ts#L39

**Comment by arcanis** [comment] 2020-04-28 20:10
Hm yeah, it's actually in my does-far-too-many-things-at-once PR that adds support for Git dependencies... 🤔

**Comment by njj** [comment] 2020-04-28 20:16
@paul-soporan @arcanis 

This issue came up for me when I run an `Makescript` that does an initial setup of my app, but when I run it again (after berry is installed) it errors out.  What would you recommend I do other than `yarn set version berry` to prevent this error from happening?

**Comment by arcanis** [comment] 2020-04-28 20:20
@njj For now it's a bit tricky since the 1.x and 2.x version of `yarn set version` have nothing in common, definitely something we should improve 🙁 I'll soon release a build that adds back `berry` to 2.x, so you'll be able to safely use that across both versions.

**Comment by njj** [comment] 2020-04-28 20:21
@arcanis Ok nice!  So would you recommend not using this for production in that case?
