### ISSUE TITLE
[Feature] Configure coc.nvim plugins with pnpify --sdk

### ISSUE THREAD

**Issue by esetnik** [yarnpkg/berry#1441] opened 2020-06-04 19:34 UTC
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**
For vscode users `yarn dlx @yarnpkg/pnpify --sdk` will create a `.vscode/settings.json` extension configuration for `eslint,prettier,etc.` compatible with pnp. `coc.nvim` uses `.vim/coc-settings.json` as it's configuration file and has many plugins which can be configured in a similar manner.

**Describe the solution you'd like**
Automatically generate `.vim/coc-configuration.json` for `coc.nvim` users based on the same rules used to generate it for vscode.

**Describe the drawbacks of your solution**
Not all developers use `coc.nvim` and not all developers use `vscode`. The sdk could be extended with additional configuration parameters to decide whether or not it should generate an IDE configuration. E.g. `yarn dlx @yarnpkg/pnpify --sdk --vscode-settings --coc-settings`.

**Describe alternatives you've considered**
Manual configuration of `.vim/coc-settings.json` following documented instructions, but it's a bit tedious.

**Additional context**
https://yarnpkg.com/advanced/editor-sdks

**Comment by arcanis** [comment] 2020-06-04 20:41
Duplicate of #1231 but you ticked the first box so we can leave it open 😄

It's a good idea. The way I could see it work:

- On new projects, `yarn dlx @yarnpkg/pnpify --sdk` will just create the vscode SDK
- Additional SDKs can be added with `yarn dlx @yarnpkg/pnpify --sdk=vim|atom|...`
- Running `yarn dlx @yarnpkg/pnpify --sdk` will update all the existing SDKs if found

This way we keep the current behavior by default (which I think makes sense, VSCode is the most popular editor by far right now), but still provide a way for users to add their own at little maintenance costs. Even infra teams just have a single command to run to update all the SDKs at once.

**Comment by paul-soporan** [comment] 2020-06-18 19:36
Resolved by #1446 and #1481.

**Closed by paul-soporan** 2020-06-18 19:36 UTC
Labels: enhancement
