### ISSUE TITLE
[Bug?]: fs.readdirSync(".") returns ENOENT under yarn 3

### ISSUE THREAD

**Issue by sverweij** [yarnpkg/berry#3227] opened 2021-08-05 15:14 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Running fs.readdirSync(".") under yarn 3 (and on an existing folder) returns an ENEONT

<details>
<summary>error & stack trace</summary

```
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir
    at Object.readdirSync (node:fs:1381:3)
    at NodeFS.readdirSync (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:6665:26)
    at makeCallSync.subPath.subPath (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:9639:26)
    at ZipOpenFS.makeCallSync (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:9739:26)
    at ZipOpenFS.readdirSync (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:9638:17)
    at VirtualFS.readdirSync (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:6972:24)
    at PosixFS.readdirSync (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:6972:24)
    at URLFS.readdirSync (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/.pnp.cjs:6972:24)
    at Object.<anonymous> (/Users/tylerdurden/prg/js/dependency-cruiser-repro-repo/480/index.js:3:37)
    at Module._compile (node:internal/modules/cjs/loader:1109:14) {
  errno: -2,
  syscall: 'scandir',
  code:

```

</details>

### To reproduce

- create a package with an index.js containing `console.log(fs.readdirSync("."))`
- call the index.js it from yarn (e.g. with a package script)

_minimal_ repro repo will follow but this one tells the story already: https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/480

### Environment

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 16.1.0 - /private/var/folders/jg/rndps86x62s5q2khdmrwj3wc0000gn/T/xfs-fcd89bed/node
    Yarn: 3.0.0 - /private/var/folders/jg/rndps86x62s5q2khdmrwj3wc0000gn/T/xfs-fcd89bed/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm

### Additional context

- Might be the root cause for #3198
- Might be caused by #3136

**Comment by merceyz** [comment] 2021-08-05 15:15
Duplicate of https://github.com/yarnpkg/berry/issues/3136

**Closed by merceyz** 2021-08-05 15:15 UTC
Labels: bug
