### ISSUE TITLE
[Bug] Can't move to yarn 2

### ISSUE THREAD

**Issue by statictype** [yarnpkg/berry#2761] opened 2021-04-15 13:51 UTC
**Describe the bug**

I installed yarn today with `npm -g install yarn` and no matter which project folder i try to set the new version by running `yarn set version berry` or `yarn set version latest` i get an error.

`error Command "set" not found.`

I tried to uninstall node and nvm and start fresh, but same behaviour, with or without nvm.

**Screenshots**

<img width="845" alt="Screenshot 2021-04-15 at 15 45 15" src="https://user-images.githubusercontent.com/42985153/114879719-bdb76200-9e01-11eb-904d-2325671c9a06.png">

**Environment if relevant (please complete the following information):**

 - OS: macOS Big Sur 11.2.3
 - Node version - tried with 15, 14 and 12
 - Yarn version 1.7.0 

**Additional context**

I couldn't find any similar issues and is probably hard to reproduce, but any help would be much appreciated.

**Comment by merceyz** [comment] 2021-04-15 13:54
Duplicate of https://github.com/yarnpkg/berry/issues/2713

**Closed by merceyz** 2021-04-15 13:54 UTC
Labels: bug

**Comment by arcanis** [comment] 2021-04-15 14:04
I don't think it's a duplicate: the problem here is just that `npm install -g yarn` doesn't upgrade Yarn (cf the screenshot, which mentions 1.7 instead of the expected 1.22, as what was installed). This is usually caused by your `$PATH` containing another Yarn (for example one you would have installed via `brew` or something like that).

Try running `which yarn` to figure out where your current global binary comes from.

**Comment by statictype** [comment] 2021-04-15 14:23
I haven't installed it from another source. It was the `.yarnrc` i had in my home folder without knowing. So the issue is actually a duplicate. Thanks!
