### ISSUE TITLE
[Bug?] Can't `yarn add jspdf`: Error: file-saver@github:eligrey/FileSaver.js#1.3.8 isn't supported by any available resolver

### ISSUE THREAD

**Issue by nkalinov** [yarnpkg/berry#832] opened 2020-01-29 14:32 UTC
- [x] I'd be willing to implement a fix

**Describe the bug**

While trying to add the `jspdf` package yarn fails with: 
```
$ yarn add jspdf
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: file-saver@github:eligrey/FileSaver.js#1.3.8 isn't supported by any available resolver
    at t.MultiResolver.getResolverByDescriptor (/Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:41628)
    at t.MultiResolver.bindDescriptor (/Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:41082)
    at t.OverrideResolver.bindDescriptor (/Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:862333)
    at /Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:583324
    at async Promise.all (index 76)
    at async N.resolveEverything (/Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:582677)
    at async /Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:599416
    at async l.startTimerPromise (/Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:45528)
    at async N.install (/Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:599028)
    at async /Users/nkalinov/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:50:77074
➤ YN0000: └ Completed in 0.14s
➤ YN0000: Failed with errors in 0.14s
```

**To Reproduce**

`yarn add jspdf`

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: **OSX**
 - Node version **12.14.1**
 - Yarn version **2.0.0-rc.27**

**Comment by bgotink** [comment] 2020-01-29 20:14
I can reproduce this on version 2.0.0-rc.27 but it works on 2.0.0-rc.28.
Could you update to the latest version and see if that fixes it?

**Comment by merceyz** [comment] 2020-01-29 21:12
Duplicate of https://github.com/yarnpkg/berry/issues/777
Fixed in https://github.com/yarnpkg/berry/pull/783

**Closed by merceyz** 2020-01-29 21:12 UTC
Labels: bug

**Comment by raspy8766** [comment] 2020-01-29 21:36
@bgotink @merceyz I have a similar issue. Although it appears the release tag has been pushed in [github](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F2.0.0-rc.28), it looks like version 2.0.0-rc.28 hasn't been published to npm yet:

![image](https://user-images.githubusercontent.com/8533429/73398080-9b3b3680-4299-11ea-9615-ef8cf65a27dd.png)

I'm trying to install the `grommet-cli` which has a transitive dependency on [vorpal](https://github.com/grommet/grommet-cli/blob/v3.0.0/package.json#L41). It fails to pull the tarball from the `EXIT_ON_PARSE` branch:

![image](https://user-images.githubusercontent.com/8533429/73398371-2f0d0280-429a-11ea-8b66-12bb04bcc8c8.png)

When should we expect 2.0.0-rc.28 to rollout?

**Comment by merceyz** [comment] 2020-01-29 21:45
You can always grab the latest version from master using `yarn set version from sources`

**Comment by raspy8766** [comment] 2020-01-29 21:47
Nice! I was going to manually copy/paste the new tarball in my AppData/Roaming/npm folder. But that is much cleaner. Thanks!

**Comment by raspy8766** [comment] 2020-01-29 22:10
https://github.com/yarnpkg/berry/issues/835

**Comment by nkalinov** [comment] 2020-01-30 08:09
Thanks guys, just confirming that it is working with the master version.
