### ISSUE TITLE
[Bug] 'yarn workspace' command looking for a script called workspace

### ISSUE THREAD

**Issue by orta** [yarnpkg/berry#595] opened 2019-11-20 13:14 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

I switched the v2 branch of the TS website to use Yarn 2, and tried to use the existing scripts:

```json
  "scripts": {
    "bootstrap": "yarn build-tsconfig-reference-md",
    "start": "yarn workspace typescriptlang-org start",
    "build-site": "yarn workspace typescriptlang-org build",
    "build-tsconfig-reference-md": "yarn workspace tsconfig-reference build",
    "build": "yarn build-tsconfig-reference-md && yarn build-site",
    "update-snapshots": "yarn workspace typescriptlang-org update-snapshots",
    ...
```

Some maybe useful logs
```sh
➤ YN0007: │ gatsby@npm:2.17.11 [5df2e] must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 12.2s
➤ YN0000: Done with warnings in 5.06m

orta@Perl ~/d/t/new-typescript-website> yarn build
Usage Error: Couldn't find a script named "workspace".
$ yarn run <scriptName> ...

orta@Perl ~/d/t/new-typescript-website> yarn workspace --help
Usage Error: Couldn't find a script named "workspace".
$ yarn run <scriptName> ...

orta@Perl ~/d/t/new-typescript-website> yarn -v
2.0.0-rc.12

orta@Perl ~/d/t/new-typescript-website> yarn workspaces
Unknown Syntax Error: Command not found; did you mean:

$ yarn workspaces list [-v,--verbose] [--json]
While running workspaces "\u0000"
```

**To Reproduce**

```sh
git clone https://github.com/microsoft/TypeScript-Website
git checkout v2
yarn policies set-version v2
yarn

yarn build
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v10.16.0
 - Yarn version: 2.0.0-rc.12

**Comment by arcanis** [comment] 2019-11-20 13:25
The [`yarn workspace`](https://next.yarnpkg.com/cli/workspace) command is currently shipped separately along with `plugin-workspace-tools`. Try running the following:

```
yarn plugin import @yarnpkg/plugin-workspace-tools
```

I think we'll want to move it to the essential tools given how useful it is, though 🤔

Also ref #511 for discovery

**Comment by orta** [comment] 2019-11-20 14:18
Make sense! 

If not - berry could ship with a list of known subcommand strings and recommend folks the plugin

**Comment by arcanis** [comment] 2019-12-01 15:17
Closing #595 as duplicate of #511! 🙂

**Closed by arcanis** 2019-12-01 15:17 UTC
Labels: bug
