### ISSUE TITLE
Install package gloabally

### ISSUE THREAD

**Issue by levirs565** [yarnpkg/berry#916] opened 2020-02-07 10:06 UTC
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I just installed yarn 2 and i want to install Gridsome. However, i couldnot install `@gridsome/cli` globally. You can see this output

```
PS E:\DaunKoder\daunkoder> yarn global add @gridsome/cli
Usage Error: Couldn't find a script named "global".

$ yarn run <scriptName> ...
PS E:\DaunKoder\daunkoder>
```

**Describe the solution you'd like**

I want yarn 2 to be able to install package globally

**Describe the drawbacks of your solution**

I do not know this solution drawback.

**Describe alternatives you've considered**

The alternative solution is make a cli that install package in user global packages folder.

**Comment by arcanis** [comment] 2020-02-07 10:38
Duplicate of https://github.com/yarnpkg/berry/issues/821

**Closed by arcanis** 2020-02-07 10:38 UTC
Labels: enhancement
