### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by npenin** [yarnpkg/berry#1295] opened 2020-05-05 07:44 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

When referencing @yarnpkg/core or @yarnpkg/cli from another typescript project, it fails because of some cross yarn prject reference

**To Reproduce**

- create a new typescript project
- add @yarnpkg/core and @yarnpkg/cli
- reference them in index.ts
- run typescript compilation

**Additional context**

Here are the errors generated by typescript:
```

node_modules/@yarnpkg/core/lib/MultiFetcher.d.ts:7:64 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

7     getLocalPath(locator: Locator, opts: FetchOptions): import("../../yarnpkg-fslib/sources").PortablePath | null;
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/core/lib/structUtils.d.ts:91:66 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

91 export declare function slugifyLocator(locator: Locator): import("../../yarnpkg-fslib/sources").Filename;
                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts:6:64 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

6     getLocalPath(locator: Locator, opts: FetchOptions): import("../../yarnpkg-fslib/sources").PortablePath | null;
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts:8:35 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

8         packageFs: AliasFS<import("../../yarnpkg-fslib/sources").PortablePath>;
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts:10:28 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

10         prefixPath: import("../../yarnpkg-fslib/sources").PortablePath;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts:11:28 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

11         localPath?: import("../../yarnpkg-fslib/sources").PortablePath | null | undefined;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts:15:50 - error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

15     getLocatorFilename(locator: Locator): import("../../yarnpkg-fslib/sources").Filename;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@yarnpkg/cli/lib/tools/openWorkspace.d.ts:3:104 - error TS2307: Cannot find module '../../../yarnpkg-core/sources'.

3 export declare function openWorkspace(configuration: Configuration, cwd: PortablePath): Promise<import("../../../yarnpkg-core/sources").Workspace>;
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by arcanis** [comment] 2020-05-05 07:50
Yep, duplicate of #1278

**Closed by arcanis** 2020-05-05 07:50 UTC
Labels: bug
