### ISSUE TITLE
[Feature] Scripting `yarn npm login`

### ISSUE THREAD

**Issue by TheKnarf** [yarnpkg/berry#2837] opened 2021-05-03 13:12 UTC
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

When using a self-hosted npm repository (we use [Nexus](https://www.sonatype.com/products/repository-oss)) `yarn` needs to be able to login to the repository before installing packages. This is possible using `yarn npm login`. However we're also using a build server, and the build server also needs to run this command to login.

In older versions of this worked fine, as yarn would simply pickup whatever was in `.npmrc`. That way we could use the [npm-cli-adduser](https://github.com/ksafavi/npm-cli-adduser) tool to script login on the buildserver.

Newer versions of yarn does not read `.npmrc` and do not provide a non-interactive way of running `yarn npm login`.

**Describe the solution you'd like**

I would like the command `yarn npm login` to take the following command line options and be able to ran in the following way:

```
echo "$MY_NEXUS_PASSWORD" | yarn npm login --no-interactive --email "my.email@mail.com" --username "nexus.username" --stdin-password
```

That way I can add the above line to my build scripts that run on a buildserver so that it can fetch packages.
It's important for buildservers that it takes all input as parameters and runs in a non-interactive way.

**Describe the drawbacks of your solution**

There is no drawbacks to my proposed solution.

**Describe alternatives you've considered**

This is something that everyone that uses a custom repository manager needs to be able to run builds on a build server.
The alternative would be to add back support in yarn to parse `.npmrc` and get login information the way it used to work.

**Comment by merceyz** [comment] 2021-05-03 14:05
Duplicate of https://github.com/yarnpkg/berry/issues/2035

**Closed by merceyz** 2021-05-03 14:05 UTC
Labels: enhancement
