### ISSUE TITLE
[Bug?]: Can't add a dependency from a private github repo where the dep uses pnpm

### ISSUE THREAD

**Issue by catsalive** [yarnpkg/berry#4212] opened 2022-03-11 15:31 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Using yarn 3.2.0

Unable to install a dependency from a private github repo that itself uses pnpm as it's package manager. This worked fine in yarn 1.*.

command used: `yarn add <package-name>@git@github.com:<org-name>/<package-name>.git#<branch-name>`

As soon as I converted the dep package to yarn - it worked fine. I have to assume this is a bug.

Totally guessing, but in `https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/scriptUtils.ts`
the PackageManager enum has pnpm in it. But later on in the code the workflows map variable has no entry for pnpm in it - which appears to be the issue and why it emits the error: `Assertion failed: Unsupported workflow`.

### To reproduce

- Create a Yarn Berry repo (3.2.0)
- Try to `yarn add` a dependency from a private github repo which itself uses pnpm as it's package manager
- Witness failure to import with `Assertion failed: Unsupported workflow` error

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 12.22.6 - ~\AppData\Local\Temp\xfs-b1a8c68b\node.CMD
    Yarn: 3.2.0 - ~\AppData\Local\Temp\xfs-b1a8c68b\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by merceyz** [comment] 2022-03-11 15:44
Duplicate of https://github.com/yarnpkg/berry/issues/3169

**Closed by merceyz** 2022-03-11 15:44 UTC
Labels: bug

**Comment by catsalive** [comment] 2022-03-11 15:54
> Duplicate of #3169

Gotcha! Sorry for the dupe.
