### ISSUE TITLE
[Bug] ts-node fails to traverse workspaces

### ISSUE THREAD

**Issue by TheGrimSilence** [yarnpkg/berry#1542] opened 2020-07-04 23:15 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

When using `ts-node` and workspaces, it errors stating it can't due to a faulty configuration, but TypeScript and VS Code work fine.

```
(node:4068) UnhandledPromiseRejectionWarning: TypeError: Unable to require file: packages\noderalis-core\sources\index.ts
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or other executable extension with loader attached before `ts-node` available.
    at getOutput (C:\Users\adria\Desktop\Grim\projects\noderalis\.yarn\$$virtual\ts-node-virtual-2da6e4f75e\0\cache\ts-node-npm-8.10.2-b4fe5a56b0-cd6e023e07.zip\node_modules\ts-node\src\index.ts:586:17)
    at Object.compile (C:\Users\adria\Desktop\Grim\projects\noderalis\.yarn\$$virtual\ts-node-virtual-2da6e4f75e\0\cache\ts-node-npm-8.10.2-b4fe5a56b0-cd6e023e07.zip\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (C:\Users\adria\Desktop\Grim\projects\noderalis\.yarn\$$virtual\ts-node-virtual-2da6e4f75e\0\cache\ts-node-npm-8.10.2-b4fe5a56b0-cd6e023e07.zip\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\adria\Desktop\Grim\projects\noderalis\.yarn\$$virtual\ts-node-virtual-2da6e4f75e\0\cache\ts-node-npm-8.10.2-b4fe5a56b0-cd6e023e07.zip\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.external_module_.Module._load (C:\Users\adria\Desktop\Grim\projects\noderalis\.pnp.js:20654:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\adria\Desktop\Grim\projects\noderalis\.noderalis.ts:1:1)
(node:4068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

Install `ts-node` and attempt to use it in workspaces, where those workspaces depend on each other.

**Comment by arcanis** [comment] 2020-07-04 23:16
Duplicate of https://github.com/TypeStrong/ts-node/issues/1021

**Closed by arcanis** 2020-07-04 23:16 UTC
Labels: bug
