### ISSUE TITLE
[Bug?]: Doctor reports TS path aliases as undeclared dependency

### ISSUE THREAD

**Issue by simPod** [yarnpkg/berry#3946] opened 2022-01-05 10:37 UTC
### Describe the bug

I'm using TS with path aliases.

When running `yarn dlx @yarnpkg/doctor`, all aliases are reported as undeclared dependency

> ➤ YN0000: │ /path/src/components/A.tsx:11:1: Undeclared dependency on @components/A

E.g. nextjs resolves those by default https://nextjs.org/docs/advanced-features/module-path-aliases

### To reproduce

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": ["src/components/*"],
```

```tsx
import { A } from '@components/A';
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.13.1 - /private/var/folders/59/hp4vslds6mj0qrtqh5x5_0r80000gp/T/xfs-87d67754/node
    Yarn: 3.1.1 - /private/var/folders/59/hp4vslds6mj0qrtqh5x5_0r80000gp/T/xfs-87d67754/yarn
    npm: 8.1.2 - /usr/local/Cellar/node@16/16.13.1/bin/npm
  npmPackages:
    jest: ^27.2.5 => 27.2.5
```

**Comment by merceyz** [comment] 2022-01-05 10:38
Duplicate of https://github.com/yarnpkg/berry/issues/889

**Closed by merceyz** 2022-01-05 10:38 UTC
Labels: bug
