### ISSUE TITLE
[Feature] [interactive-tools] Show workspace names when upgrading

### ISSUE THREAD

**Issue by ffxsam** [yarnpkg/berry#3281] opened 2021-08-12 16:07 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I want an easy way to interactively upgrade packages across workspaces in a monorepo.

**Describe the solution you'd like**

It would be great if `yarn upgrade-interactive` were to show the workspace name, as this is not clear:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/12532733/129230220-43c46c54-a82d-45eb-b3c7-312c43e4d06a.png">

**Describe the drawbacks of your solution**

One issue is that this plugin is running out of horizontal space. It's already rather cramped, and in a 80-char wide terminal it's difficult to see everything that's important.

As a side note: `yarn workspace myworkspace upgrade-interactive` does not work as expected, either. It still seems to run at project root, as it shows the two different versions of `faker`.

**Comment by merceyz** [comment] 2021-08-12 16:07
See https://github.com/yarnpkg/berry/pull/3260

**Comment by merceyz** [comment] 2021-08-12 16:08
Duplicate of https://github.com/yarnpkg/berry/issues/2591

**Closed by merceyz** 2021-08-12 16:08 UTC
Labels: enhancement
