### ISSUE TITLE
[Bug?]: Can't install v3; can't get past corepack enable

### ISSUE THREAD

**Issue by tomByrer** [yarnpkg/berry#3807] opened 2021-11-28 08:04 UTC
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Can't install v3;
```bash
$ corepack enable
Internal Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm'
Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm'
```

### To reproduce

`corepack enable`

### Environment

```shell
Win10
node v17.1.0
I'm stuck on v1.x of yarn
```

### Additional context

I'm not alone:
https://www.reddit.com/r/node/comments/qz6u86/help_cant_enable_corepack/

**Comment by arcanis** [comment] 2021-11-28 08:44
Duplicate of https://github.com/nodejs/corepack/issues/71

**Closed by arcanis** 2021-11-28 08:44 UTC
Labels: bug
