### ISSUE TITLE
[Bug] Cannot install typescript 4.3.2 with yarn 2 / node_modules linker

### ISSUE THREAD

**Issue by xaviergonz** [yarnpkg/berry#2935] opened 2021-05-26 22:19 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

While installing TS 4.3.2 with the node_modules linker yarn 2.4.1 fails with:
```
➤ YN0013: │ typescript@npm:4.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@patch:typescript@npm%3A4.3.2#builtin<compat/typescript>::version=4.3.2&hash=a45b0e can't be found in the cache and 
➤ YN0013: │ typescript@npm:4.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.3.2#builtin<compat/typescript>::version=4.3.2&hash=a45b0e: Cannot apply hunk #2 (set enableInlineHunks for details)
```

**To Reproduce**

``` 
{
  "version": "0.59.0",
  "devDependencies": {
    "typescript": "^4.3.0"
  }
}
```

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 16.2.0
 - Yarn version 2.4.1

**Comment by merceyz** [comment] 2021-05-26 22:21
Fixed in https://github.com/yarnpkg/berry/pull/2543 / `3.0.0-rc.2`
```
yarn set version 3.0.0-rc.2
```

**Comment by xaviergonz** [comment] 2021-05-26 22:21
Will the fix be backported to yarn 2?

**Closed by merceyz** 2021-05-26 22:21 UTC
Labels: bug

**Comment by LouisSung** [comment] 2021-05-27 03:57
Hi @merceyz ,
I tried the yarn@3.0.0-rc.2 but still meet the problem QQ
```bash
$ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /app/.yarn/releases/yarn-berry.cjs...
Updating /app/.yarnrc.yml...
Done!

$ yarn set version 3.0.0-rc.2
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/%40yarnpkg/cli/3.0.0-rc.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.0.0-rc.2.cjs
➤ YN0000: Done in 1s 565ms
```

```ts
➤ YN0066: │ typescript@patch:typescript@npm%3A4.3.2#~builtin<compat/typescript>::version=4.3.2&hash=34ad7d: Cannot apply hunk #2
➤ YN0000: │           }
➤ YN0000: │       }
➤ YN0000: │       ts.getEffectiveTypeRoots = getEffectiveTypeRoots;
➤ YN0028: │ -     function getDefaultTypeRoots(currentDirectory, host) {
➤ YN0028: │ +     function getNodeModulesTypeRoots(currentDirectory, host) {
➤ YN0000: │           if (!host.directoryExists) {
➤ YN0000: │               return [ts.combinePaths(currentDirectory, nodeModulesAtTypes)];
➤ YN0000: │           }
➤ YN0028: │ -         var typeRoots;
➤ YN0028: │ +         var typeRoots = [];
➤ YN0000: │           ts.forEachAncestorDirectory(ts.normalizePath(currentDirectory), function (directory) {
➤ YN0000: │               var atTypes = ts.combinePaths(directory, nodeModulesAtTypes);
➤ YN0000: │               if (host.directoryExists(atTypes)) {
➤ YN0028: │ -                 (typeRoots || (typeRoots = [])).push(atTypes);
➤ YN0028: │ +                 typeRoots.push(atTypes);
➤ YN0000: │               }
➤ YN0000: │               return undefined;
➤ YN0000: │           });
➤ YN0000: │           return typeRoots;
➤ YN0000: │       }
➤ YN0000: │       var nodeModulesAtTypes = ts.combinePaths("node_modules", "@types");
➤ YN0028: │ +     function getPnpTypeRoots(currentDirectory) {
➤ YN0028: │ +         var pnpapi = getPnpApi(currentDirectory);
➤ YN0028: │ +         if (!pnpapi) {
➤ YN0028: │ +             return [];
➤ YN0028: │ +         }
➤ YN0028: │ +         currentDirectory = ts.sys.resolvePath(currentDirectory);
➤ YN0028: │ +         var currentPackage = pnpapi.findPackageLocator(currentDirectory + "/");
➤ YN0028: │ +         if (!currentPackage) {
➤ YN0028: │ +             return [];
➤ YN0028: │ +         }
➤ YN0028: │ +         var packageDependencies = pnpapi.getPackageInformation(currentPackage).packageDependencies;
➤ YN0028: │ +         var typeRoots = [];
➤ YN0028: │ +         for (var _i = 0, _a = Array.from(packageDependencies.entries()); _i < _a.length; _i++) {
➤ YN0028: │ +             var _b = _a[_i], name = _b[0], referencish = _b[1];
➤ YN0028: │ +             if (name.startsWith(typesPackagePrefix) && referencish !== null) {
➤ YN0028: │ +                 var dependencyLocator = pnpapi.getLocator(name, referencish);
➤ YN0028: │ +                 var packageLocation = pnpapi.getPackageInformation(dependencyLocator).packageLocation;
➤ YN0028: │ +                 typeRoots.push(ts.getDirectoryPath(packageLocation));
➤ YN0028: │ +             }
➤ YN0028: │ +         }
➤ YN0028: │ +         return typeRoots;
➤ YN0028: │ +     }
➤ YN0028: │ +     ts.getPnpTypeRoots = getPnpTypeRoots;
➤ YN0028: │ +     var typesPackagePrefix = "@types/";
➤ YN0028: │ +     function getDefaultTypeRoots(currentDirectory, host) {
➤ YN0028: │ +         var nmTypes = getNodeModulesTypeRoots(currentDirectory, host);
➤ YN0028: │ +         var pnpTypes = getPnpTypeRoots(currentDirectory);
➤ YN0028: │ +         if (nmTypes.length > 0 || pnpTypes.length > 0) {
➤ YN0028: │ +             return __spreadArray(__spreadArray([], nmTypes), pnpTypes);
➤ YN0028: │ +         }
➤ YN0028: │ +     }
➤ YN0000: │       function resolveTypeReferenceDirective(typeReferenceDirectiveName, containingFile, options, host, redirectedReference) {
➤ YN0000: │           var traceEnabled = isTraceEnabled(options, host);
➤ YN0000: │           if (redirectedReference) {
➤ YN0000: └ Completed in 36s 384ms
```

**Comment by merceyz** [comment] 2021-05-28 06:54
> Will the fix be backported to yarn 2?
> @xaviergonz

That specific feature of making them optional probably wont be, no

> I tried the yarn@3.0.0-rc.2 but still met the problem QQ
> @LouisSung

That's expected, it wont be able to apply the patch but 3.0.0-rc.2 makes it optional which is fine for OP as they're using the node_modules linker

> I tried to run my project and the typescript not work.
> @fyfirman 

The patch was updated in https://github.com/yarnpkg/berry/pull/2889
```
yarn set version from sources
```

**Comment by LouisSung** [comment] 2021-05-29 15:39
@merceyz I'm using node_modules liker too, not sure if I have to do more things to c?
Is there any plan on the date to release the patch? Seems impact a lot? (at least #2935, #2938, #2944, and #2952)

I can confirm it has been fixed with `yarn set version from sources` though, thank you for the quick fix : )

**Comment by Leksat** [comment] 2021-06-02 09:02
Why Yarn still tries to patch TypeScript when `nodeLinker` is set to `node-modules`? Shouldn't this setting disable PNP completely?

**Comment by arcanis** [comment] 2021-06-02 10:11
> Why Yarn still tries to patch TypeScript when `nodeLinker` is set to `node-modules`? Shouldn't this setting disable PNP completely?

No, because it would cause switching between nm and pnp linkers to alter the cached files, which isn't something we want to do (it's a valid use case; some people run nm locally and pnp on their CI).

> Is there any plan on the date to release the patch?

It'll be part of 3.0.0-rc.4 which I'm currently working on releasing.

**Comment by charles-allen** [comment] 2021-06-03 05:18
I'm a bit stuck on this -- both solutions hit other issues:

### 3.0.0-rc.2 => Invalid semver version (no issue?)
> Fixed in #2543
> ```
> yarn set version 3.0.0-rc.2
> ```
```sh
❯ yarn set version 3.0.0-rc.2         
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/%40yarnpkg/cli/3.0.0-rc.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0001: Error: Invalid semver version
```
### sources => [lodash.zip gets confused for a zip archive](https://github.com/yarnpkg/berry/issues/2975)
> The patch was updated in #2889
> ```
> yarn set version from sources
> ```
```sh
❯ yarn set version from sources
...
❯ yarn                         
...
➤ YN0001: │ Error: While persisting [...]/.yarn/cache/lodash.zip-npm-4.2.0-5299417ec8-41fd8dc1af.zip/node_modules/lodash.zip/ -> [...]/node_modules/lodash.zip ENOTDIR: not a directory, scandir '[...]/.yarn/cache/lodash.zip-npm-4.2.0-5299417ec8-41fd8dc1af.zip/node_modules/lodash.zip'
```
### Context:
```
❯ yarn -v                              
2.4.1
❯ cat .yarnrc.yml
nodeLinker: node-modules # also tried with this commented out

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
❯ sw_vers   
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
```

**Comment by merceyz** [comment] 2021-06-03 10:35
The patch has been released in 2.4.2

**Comment by charles-allen** [comment] 2021-06-03 19:00
> The patch has been released in 2.4.2

That fixed mine -- successful upgrade to Yarn 2 :)

```sh
➤ YN0000: Done with warnings in 1m 44s
```

**Comment by qrilka** [comment] 2021-07-15 10:21
> The patch has been released in 2.4.2
Is this release even available?
I see
```
$ yarn set version 2.4.2
Resolving 2.4.2 to a url...
error An unexpected error occurred: "Release not found: 2.4.2".
info If you think this is a bug, please open a bug report with the information provided in "/home/kirill/project-path/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.

```

**Comment by merceyz** [comment] 2021-07-15 10:23
@qrilka You need to be on v2 to use a specific version
```
yarn set version berry && yarn set version 2.4.2
```

**Comment by Eomm** [comment] 2021-09-01 10:39
I have the same error within this `package.json` and yarn `2.4.2`. Is this a regression?

```
{
  "version": "0.59.0",
  "devDependencies": {
    "typescript": "^4.4.2"
  },
  "packageManager": "yarn@2.4.2"
}
```

```
➤ YN0000: ┌ Fetch step
➤ YN0013: │ typescript@npm:4.4.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@patch:typescript@npm%3A4.4.2#builtin<compat/typescript>::version=4.4.2&hash=ddfc1b can't be foun
➤ YN0013: │ typescript@npm:4.4.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.4.2#builtin<compat/typescript>::version=4.4.2&hash=ddfc1b: Cannot apply hunk #14 (set enableInlineHunks for details)
```

To reproduce:

```
code package.json
yarn --version
yarn set version berry && yarn set version 2.4.2
echo "nodeLinker: node-modules" >> .yarnrc.yml
yarn install
```

**Comment by clemsos** [comment] 2021-09-01 15:00
yes this bug still happen with 2.4.2

**Comment by merceyz** [comment] 2021-09-01 16:05
It's not that it's "still happening" nor a "regression", TypeScript released a new version so we need to update the PnP patch. The patch was updated in https://github.com/yarnpkg/berry/pull/3297 which was released in `3.1.0-rc.2` and we haven't done a full release / backport yet, until we do that the fix is to run the following:

```sh
yarn set version berry && yarn set version canary && yarn
```

**Comment by Eomm** [comment] 2021-09-02 07:10
Thanks for the explanation

> TypeScript released a new version so we need to update the PnP patch

Will this happen for future TS minor releases?

**Comment by merceyz** [comment] 2021-09-02 07:14
> Will this happen for future TS minor releases?

Most likely if we look at the pattern https://github.com/yarnpkg/berry/blob/464618c2f7baba46a79d66849c1eda00cad1132e/packages/plugin-compat/extra/typescript/gen-typescript-patch.js#L18-L80
