### ISSUE TITLE
[Bug?]: `yarn config` commands break common YAML styling

### ISSUE THREAD

**Issue by mcandre** [yarnpkg/berry#6566] opened 2024-10-21 16:05 UTC
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When a developer runs `yarn config`..., then any opening or closing YAML document delimiters (`---`, `...`) get stripped from the .yarnrc.yml file. This breaks integration with other tools like yamllint, which often have style settings enforcing the use of these delimiters for safety and clarity. Please preserve any opening and/or closing YAML document delimiters when machine altering .yarnrc.yml.

Also, `yarn config`... forces a blank line between each key. Most other YAML files, especially hand-written YAML files, do not do this. Please preserve the existing number of blank lines between keys when machine altering .yarnrc.yml.

### To reproduce

```console
$ yarn config set httpProxy http://foo.bar:123
$ yarn config set httpsProxy http://foo.bar:123
```

### Environment

$ yarn dlx -q envinfo --preset jest

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 20.17.0 - /private/var/folders/xc/s20l07yj76x8m3h20lmy5jlc0000gn/T/xfs-e6f1c6f1/node
    Yarn: 4.3.1 - /private/var/folders/xc/s20l07yj76x8m3h20lmy5jlc0000gn/T/xfs-e6f1c6f1/yarn
    npm: 10.8.2 - ~/.asdf/plugins/nodejs/shims/npm

**Comment by arcanis** [comment] 2024-10-21 16:47
Duplicate of #1463

**Closed by arcanis** 2024-10-21 16:47 UTC
Labels: bug
