### ISSUE TITLE
[Bug] `yarn workspaces foreach run <script-name>` prints usage error for missing script

### ISSUE THREAD

**Issue by AlCalzone** [yarnpkg/berry#3048] opened 2021-06-27 10:23 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

I am using `yarn workspaces foreach run <script-name>` to run scripts that are present in some of my workspaces, but not all of them. The [documentation](https://yarnpkg.com/cli/workspaces/foreach#details) states:
> If the command is `run` and the script being run does not exist the child workspace will be skipped without error.

However, I'm getting a bunch of error logs in the command output:
```
➤ YN0000: Usage Error: Couldn't find a script named "lint:config".
➤ YN0000:
➤ YN0000: $ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```

Granted, the command succeeds without error, but this output seems unintended to me.
**Edit:** it actually fails with code 1.

**To Reproduce**

Sorry, the codesandbox is crashing, so I can't provide a repro there. Basically you need:
1. a monorepo with at least 2 packages
2. yarn `3.0.0-rc.6` with the `workspaces` plugin
3. define a package.json script in one of the packages, but not the other
4. run `yarn workspaces foreach run <script-name>`

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 16.2.0
 - Yarn version 3.0.0-rc.6

**Additional context**

**Comment by merceyz** [comment] 2021-06-27 11:29
It's throwing because script names containing a colon (`:`) are global and you have multiple scripts with the same name so it doesn't know which one to run so it throws, the error message should be improved though

**Comment by AlCalzone** [comment] 2021-06-27 11:50
Oh, I see. I used to separate similar scripts with a slightly different focus with a colon, but this makes sense.

**Comment by KoltesDigital** [comment] 2021-08-23 12:20
For the record: https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces

> Little-known Yarn feature: any script with a colon in its name (build:foo) can be called from any workspace.

**Comment by carlevans719** [comment] 2021-09-09 23:08
Having this issue too - @merceyz it sounds like you're saying this is working as intended so what is the correct way to avoid the issue? Should we rename workspace scripts to use a different delimiter from a colon? 

e.g. change "lint:ci" to "lint-ci" or something?

**Comment by seansfkelley** [comment] 2021-09-10 20:53
> It's throwing because script names containing a colon (`:`) are global and you have multiple scripts with the same name so it doesn't know which one to run so it throws, the error message should be improved though

This is very surprising and is throwing a wrench into my efforts to switch away from Lerna to workspace-tools. I make heavy use of [npm-run-all and its globbing behavior](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/npm-run-all.md#glob-like-pattern-matching-for-script-names) which uses colons as scope/specificity, as was mentioned in https://github.com/yarnpkg/berry/issues/3048#issuecomment-869148812.

Is there a way to configure/disable this behavior, even just for specific invocations of Yarn?

**Comment by merceyz** [comment] 2021-09-10 21:39
> @merceyz it sounds like you're saying this is working as intended

@carlevans719 It most definitely isn't and I didn't. I explained what was happening and added the `upholded` label which has the definition `Real issues without formal reproduction`

**Comment by merceyz** [comment] 2021-09-10 22:15
Fixed in https://github.com/yarnpkg/berry/pull/3423, you can run the following commands to test it
```sh
yarn set version berry
yarn plugin import from sources workspace-tools --branch 3423
```

**Closed** 2021-09-12 09:03 UTC
Labels: bug, upholded
