### ISSUE TITLE
[Bug] packageExtensions not working 

### ISSUE THREAD

**Issue by jeffsee55** [yarnpkg/berry#1255] opened 2020-04-25 00:12 UTC
**Describe the bug**

Some packages still aren't able to resolve the warning even after fixing them with the `packageExtension config in .yarnrc.yml`

```
Error: apollo-utilities tried to access graphql (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

In my `.yarnrc.yml` I have the following:

```
packageExtensions:
  "apollo-utilities@*":
    dependencies:
      "graphql": "^15.0.0"
```

**To Reproduce**

Checkout - https://github.com/jeffsee55/yarn-2-package-extension-issue

1. `yarn install`
2. `yarn generate` - you should see the error above

To see it working without pnp:

1. Checkout to previous commit (https://github.com/jeffsee55/yarn-2-package-extension-issue/commit/ae60a37c6f4b6b36e8585b020c6aab5fc65821f8) which will change it to not use pnp.
2. `yarn install` 
3. `yarn generate` - you should see the `graphql-codegen` cli start in your terminal.

I understand this is ultimately an issue with the package manager but would like to learn me about why this sometimes still doesn't work and how I might be able to dig into it deeper.

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
 - Node version 12.16.0
 - Yarn version 2.0.0-rc.30

**Additional context**

Also - if this is in a monorepo it hurts worse because that means I need to undo all of my pnp setup for other packages. Is there any way to just disable pnp for a single package in a workspace?

**Comment by DanCouper** [comment] 2020-05-15 00:20
I and a colleague have spent several hours on this issue over the past two days, getting increasingly frustrated. I don't _think_ what you're seeing is a bug, I think the fix you're trying in `packageExtensions` just isn't correct.

run `yarn`. You'll get this message:

```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ apollo-upload-client@npm:13.0.0 doesn't provide graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0 requested by apollo-link@npm:1.2.14
➤ YN0002: │ apollo-upload-client@npm:13.0.0 doesn't provide graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 requested by apollo-link-http-common@npm:0.2.16
➤ YN0060: │ apollo-link@npm:1.2.14 [74d3c] provides graphql@npm:15.0.0 with version 15.0.0 which doesn't satisfy ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 requested by apollo-utilities@npm:1.3.3
➤ YN0000: └ Completed
```

I can't reproduce your issue -- it seems to run fine. But I suspect if you fix the first warning there (ie give "apollo-link@*" a dependency on graphql) it should sort the issue.
The reason I say this is that what I've been fighting with today and yesterday is a React app built with Webpack. I install Apollo according to the Apollo React docs recommendation, try to build, and I get your error:

> `Error: apollo-utilities tried to access graphql (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.`

We tried all kinds of variations on your solution, except that apollo-utilities wasn't really the problem: we added apollo-client and apollo-utilities as dependents of @apollo/react-hooks, ran yarn, got a slightly different warning, added graphql as a dependency of "apollo-link-error@*" and everything just worked perfectly once that was done.

I think this is the solution here, I'm just going off me and my colleague fighting with Yarn for ages until we actually read the warnings it gives on install properly. Also, I assume [loose mode](https://yarnpkg.com/features/pnp#pnp-loose-mode) would fix the issues as well, but I've literally only just seen it in the docs.

**Comment by arcanis** [comment] 2020-05-15 10:51
Package extensions are correct, they add the dependency to the right package. The problem is that for peer dependencies, there might be multiple problematic intermediaries. Take this:

```
. -> A -> B -> C -> D -peer-> X
  -> X
```

Since C doesn't provide X, Yarn throws an error saying that D is trying to access a dependency it doesn't list. However, it falls short of telling you that the reason for that is that C doesn't provide it! 

```
D tried to access X (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: X (via "X")
Required by: D@1.0.0 (via /path/to/D/index.js)
```

Making it difficult to fix, since you need to use `yarn why` to understand who's dependending on D, and which one is omitting to list a peer dependency on X. Then once you figure it out, you need to start again because `B` doesn't list it either, so you get the same problem 😞

This will be fixed with https://github.com/yarnpkg/berry/pull/1362, which will cause Yarn to list the also broken peer dependency links when throwing the error:

```
D tried to access X (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: X (via "X")
Required by: D@1.0.0 (via /path/to/D/index.js)
Ancestor breaking the chain: C@1.0.0
```

**Comment by jeffsee55** [comment] 2020-05-16 01:43
Thanks to both of you for the input, @arcanis that's helpful to know - I tried just about every combination I could think of but the complexity in your example explains why I wasn't going to get it right any time soon. 

TIL - `yarn why` is what would have helped me solve this on my own. Thanks again!

**Closed** 2020-05-21 16:02 UTC
Labels: bug

**Comment by xenoterracide** [comment] 2020-10-09 00:49
hmm... I guess I'm still not getting it right...

```
➤ YN0000: [@bb/apollo-test-util]: ../../../../.yarn/cache/apollo-engine-reporting-protobuf-npm-0.5.2-15aa08f143-f49534868b.zip/node_modules/apollo-engine-reporting-protobuf/dist/protobuf.d.ts(1,23): error TS2307: Cannot find module 'long' or its corresponding type declarations.
```

```
> yarn why -R apollo-engine-reporting-protobuf
├─ @bb/apollo-test-util@workspace:app-lib/graph/packages/apollo-test-util
│  └─ apollo-server-types@npm:0.5.1 [98c53] (via npm:^0.5 [98c53])
│     └─ apollo-engine-reporting-protobuf@npm:0.5.2 (via npm:^0.5.2)
```

this is the last thing I've tried...
`/.yarnrc.yml`
```yaml
packageExtensions:
  '@bb/apollo-test-util@*':
    dependencies:
      apollo-server-types@^0.5:
        dependencies:
          apollo-engine-reporting-protobuf@0.5:
            dependencies:
              long: '^4'
            devDependencies:
              '@types/long': '^4'
```

**Comment by xenoterracide** [comment] 2020-10-09 02:11
oh I figured it out, I guess in my first iteration I missed a carat so I tried the above

```
packageExtensions:
  apollo-engine-reporting-protobuf@^0.5:
    dependencies:
      long: '^4'
      '@types/long': '^4'
```

**Comment by AlvinLaiPro** [comment] 2021-02-04 08:23
Good to know!
