### ISSUE TITLE
[Bug?]: EACCES error installing esbuild with `nodeLinker: pnpm`

### ISSUE THREAD

**Issue by sndrs** [yarnpkg/berry#5914] opened 2023-11-01 11:12 UTC
### Self-service

- [x] I'd be willing to implement a fix (but I'll need some guidance!)

### Describe the bug

When using `nodeLinker: pnpm` to install `esbuild`, the linking process fails with an `EACCES` error.

### To reproduce

Here is a repo that reproduces it https://github.com/sndrs/yarn-4-node-linker-pnpm-esbuild-repro.

The relevant bits (I _think_) are:

```jsonc
// package.json
{
	"packageManager": "yarn@4.0.1",
	"dependencies": {
		"esbuild": "^0.19.5"
	}
}
```

```yml
# .yarnrc.yml
nodeLinker: pnpm
```

You can see the error when running `yarn install` in github actions at https://github.com/sndrs/yarn-4-node-linker-pnpm-esbuild-repro/actions/runs/6718820675/job/18259264644#step:4:97.

I get an identical error locally.

### Environment

```shell
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 20.6.0 - /private/var/folders/68/5j1j3h353mn3h52r62jfklrm0000gp/T/xfs-34312e26/node
    Yarn: 4.0.1 - /private/var/folders/68/5j1j3h353mn3h52r62jfklrm0000gp/T/xfs-34312e26/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/8075_1698836213758/bin/npm
```

### Additional context

Trying to add `yarn 4` to a large project, other packages that needed to be built were fine, so I don't know if it's an `esbuild` issue or a more general issue that so far i've only seen affect `esbuild`.

**Comment by arcanis** [comment] 2023-11-01 18:51
Closing as duplicate of #5165

**Closed by arcanis** 2023-11-01 18:51 UTC
Labels: bug

**Comment by sndrs** [comment] 2023-11-01 18:55
sorry @arcanis, I totally missed that. thanks
