### ISSUE TITLE
[Bug] [ERR_INVALID_URL]: Invalid URL: git@git.xxx.com:xxx/xxx.git

### ISSUE THREAD

**Issue by kirill-konshin** [yarnpkg/berry#3018] opened 2021-06-10 20:19 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

Error occurs when trying to install `git+ssh` dependency using Yarn 2.4.2:

```
➤ YN0001: │ TypeError [ERR_INVALID_URL]: Invalid URL: git@git.xxx.com:xxx/xxx.git
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at Module.d (/Users/xxx/.yarn/releases/yarn-2.4.2.cjs:2:419330)
```

**To Reproduce**

Have a following entry in `package.json`:

```json
{
  "dependencies": {
    "xxx": "git+ssh://git@git.xxx.com:xxx/xxx.git#xxx_21.5.1"
  }
}
```

Run `yarn install`

**Environment if relevant (please complete the following information):**

 - OS: Mac 11.3.1
 - Node version: 14.17.0
 - Yarn version: 2.4.2

**Comment by merceyz** [comment] 2021-06-10 20:34
Duplicate of #2240

Fixed in 3.0.0-rc.5
```
yarn set version 3.0.0-rc.5
```

**Closed by merceyz** 2021-06-10 20:34 UTC
Labels: bug

**Comment by kirill-konshin** [comment] 2021-06-11 19:09
@merceyz thank you. The only problem is that `3.x` creates `.pnp.cjs` instead of `.pnp.js` which is not picked up by our `eslint@6.8.0`... I can't blanket-upgrade at the moment, so can you suggest any `2.x` version that has the fix?

**Comment by merceyz** [comment] 2021-06-11 19:59
> The only problem is that 3.x creates .pnp.cjs instead of .pnp.js which is not picked up by our eslint@6.8.0.

That seems odd, if you mean the SDK doesn't then run `yarn dlx @yarnpkg/pnpify --sdk vscode` to update it.

> I can't blanket-upgrade at the moment, so can you suggest any 2.x version that has the fix?

I can't as it hasn't been backported

**Comment by kirill-konshin** [comment] 2021-06-11 21:04
@merceyz I don't think ESLint is using the SDK, seems that they simply import `.pnp.js`... I can't find the exact code in their codebase though... I'll keep looking.
