### ISSUE TITLE
[Feature] Yarn debug cmd to make debugging easier.

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/berry#1136] opened 2020-03-31 02:16 UTC
- [ X] I'd be willing to implement this feature
** I really want to implement this feature by myself with some guidance/help from others.**
- [ X] This feature can already be implemented through a plugin

**Describe the user story**

It's very hard to find issues in your code when others don't give you enough info. And it's a pain to send comments back and forth asking for info.

**Describe the solution you'd like**

We make a command, ```yarn debug --copy``` and it generates a report of the common details needed such as your operating system, binary versions, browsers, installed languages, and more
Literally, I don't see why this shouldn't be implemented. It will make it easier for us and the user reporting the issue.

**Describe the drawbacks of your solution**

I don't think it changes yarn drastically.

**Describe alternatives you've considered**

**I don't know about any**

**Additional context**
None.

**Comment by arcanis** [comment] 2020-03-31 08:41
I agree with the sentiment, but I don't think a command as described would help. Few issues are caused by the operating systems or installed languages - they are much more commonly related to the specific set of packages being installed and the files layout on the disk. Two things we cannot just send on GitHub for privacy reasons.

I think a better solution would be to enforce Sherlock somehow, but we can only do this once the  user experience has improved (with a playground, for example).

**Comment by NotMoni** [comment] 2020-03-31 15:02
@arcanis I don't think information like this will hurt privacy.
```
 System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 2.97 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Servers:
    Apache: 2.4.34 - /usr/sbin/apachectl
    Nginx: 1.13.12 - /usr/local/bin/nginx
  Languages:
    Bash: 4.4.23 - /usr/local/bin/bash
    Elixir: 1.6.2 - /usr/local/bin/elixir
    Go: 1.11.1 - /usr/local/bin/go
    Java: 1.8.0_192 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Python3: 3.7.2 - /usr/local/bin/python3
    R: 3.6.0 - /usr/local/bin/R
    Ruby: 2.3.7 - /usr/bin/ruby
    Rust: 1.16.0 - /Users/tabrindle/.cargo/bin/rustup
  npmPackages:
    apollo-client: ^2.3.1 => 2.3.1
    jest: ^22.2.1 => 22.2.1
    ...
    react: ^16.3.2 => 16.3.2
    react-apollo: ^2.1.4 => 2.1.4
    run4staged: ^1.1.1 => 1.1.1
    solidarity: 2.0.5 => 2.0.5
  npmGlobalPackages:
    create-react-app: 1.5.2
    create-react-native-app: 1.0.0
    envinfo: 5.10.0
    exp: 49.2.2
    gatsby-cli: 1.1.52
    npm: 5.6.0
    react-native-cli: 2.0.1
    solidarity: 2.1.0
    typescript: 2.8.1
```
Anyways its is a userinvoked command. 
They have to do ```yarn debug --copy```  
We can only require it if its really needed.

**Comment by paul-soporan** [comment] 2020-03-31 21:04
IMO this information seems (more than) a bit excessive. What we need to be attached to issues are minimal reproduction cases. I don't see any possible use for fields like `Servers`. `Languages` may only be useful in cases where issues are caused by packages that ship native code and have a build step. Also, Yarn isn't even a global package manager anymore, so `npmGlobalPackages` isn't useful.
I believe that the only useful information would be fields like `OS`, `Node Version`, `Yarn Version`, which are already included in the Bug Report template.
I agree with @arcanis, about enforcing Sherlock. Currently only 20 / 167 open issues have a Sherlock reproduction attached. I'll make working on a Sherlock playground my priority.

**Comment by NotMoni** [comment] 2020-03-31 21:36
Ok but even some of these should be easy to get with a command. And its very easy to with a command rather than runnning several command like `node -v`and `yarn --version`

**Comment by NotMoni** [comment] 2020-05-21 13:49
cc/ @paul-soporan , @arcanis

**Comment by arcanis** [comment] 2020-05-21 15:38
Closing, since we don't think it would be useful enough.

**Closed by arcanis** 2020-05-21 15:38 UTC
Labels: enhancement

**Comment by NotMoni** [comment] 2020-05-21 15:58
alright
